force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location (NWFB)</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations (NWFB)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Location__c/fields/TaxRate__c.field-meta.xml
<CustomField>
    <fullName>TaxRate__c</fullName>
    <inlineHelpText>Enter the tax rate percentage (eg 10.5)</inlineHelpText>
    <label>TaxRate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/LocationSelector.cls
public with sharing class LocationSelector {

    private static LocationSelector instance = null;

    public static LocationSelector getInstance() {
        if (instance == null) {
        instance = new LocationSelector();
        }
        return instance;
    }

    public Map<Id, Location__c> getLocationByIds(Set<Id> locationIdSet){
        return new Map<Id, Location__c>([
                SELECT Id, TaxRate__c                
                FROM Location__c 
                WHERE Id =: locationIdSet
        ]);
    }

    public List<Location__c> getLocationByCityName(Set<String> citiesName) {
        return new List<Location__c>([
            SELECT
                    Id,
                    Name,
                    City__c
            FROM Location__c
            WHERE City__c IN :citiesName
        ]);
    }
}