force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location (NWFB)</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations (NWFB)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Location__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <formula>Street__c + &apos;, &apos; 
+ City__c + &apos;, &apos; + State__c + &apos;, &apos; + PostalCode__c + &apos;.&apos;</formula>
    <label>Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service__c/Service__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/ContactName__c.field-meta.xml
<CustomField>
    <fullName>ContactName__c</fullName>
    <formula>Contact__r.Full_Contact_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contact Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Copilot2Name__c.field-meta.xml
<CustomField>
    <fullName>Copilot2Name__c</fullName>
    <formula>Trip__r.CoPilot2__r.FirstName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Copilot 2 Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/CopilotName__c.field-meta.xml
<CustomField>
    <fullName>CopilotName__c</fullName>
    <formula>Trip__r.CoPilot1__r.FirstName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Copilot Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/DriverName__c.field-meta.xml
<CustomField>
    <fullName>DriverName__c</fullName>
    <formula>Trip__r.Driver__r.FirstName + &apos; &apos; + Trip__r.Driver__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Driver Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>Request</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Stop__c.field-meta.xml
<CustomField>
    <fullName>Stop__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Stop</label>
    <referenceTo>Stop__c</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Trip__c.field-meta.xml
<CustomField>
    <fullName>Trip__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Trip</label>
    <referenceTo>Trip__c</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stop__c/Stop__c.object-meta.xml
<CustomObject>
    <label>Stop</label>
    <nameField>
        <label>Stop Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stops</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stop__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <formula>Service__r.Address__c + &apos; &apos; + Service__r.City__c  + &apos; &apos; + Service__r.State__c + &apos; &apos; + Service__r.Zip__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stop__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <formula>Service__r.City__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>City</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stop__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Stops</relationshipLabel>
    <relationshipName>Stops</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stop__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>Service__c</referenceTo>
    <relationshipLabel>Stops</relationshipLabel>
    <relationshipName>Stops</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stop__c/fields/StopComplete__c.field-meta.xml
<CustomField>
    <fullName>StopComplete__c</fullName>
    <label>Stop Complete</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Stop__c/fields/StopOrder__c.field-meta.xml
<CustomField>
    <fullName>StopOrder__c</fullName>
    <label>Stop order</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stop__c/fields/StopStartedMessage__c.field-meta.xml
<CustomField>
    <fullName>StopStartedMessage__c</fullName>
    <label>Stop Started Message</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Stop__c/fields/TravelTime__c.field-meta.xml
<CustomField>
    <fullName>TravelTime__c</fullName>
    <label>Travel Time</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stop__c/fields/Trip__c.field-meta.xml
<CustomField>
    <fullName>Trip__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Trip</label>
    <referenceTo>Trip__c</referenceTo>
    <relationshipLabel>Stops</relationshipLabel>
    <relationshipName>Stops</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stop__c/fields/TripStartedMessage__c.field-meta.xml
<CustomField>
    <fullName>TripStartedMessage__c</fullName>
    <label>Trip Started Message</label>
    <length>100000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Trip__c/Trip__c.object-meta.xml
<CustomObject>
    <label>Trip</label>
    <nameField>
        <label>Trips Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trips</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Trip__c/fields/CoPilotName__c.field-meta.xml
<CustomField>
    <fullName>CoPilotName__c</fullName>
    <formula>copilot__r.Full_Contact_Name__c</formula>
    <label>Co-pilot Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trip__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Trips</relationshipLabel>
    <relationshipName>Trips</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trip__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>Service__c</referenceTo>
    <relationshipLabel>Trips</relationshipLabel>
    <relationshipName>Trips</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/StopSelector.cls
public without sharing class StopSelector {

    private static StopSelector instance = null;

    public static StopSelector getInstance() {
        if (instance == null) {
        instance = new StopSelector();
        }
        return instance;
    }

    public List<Stop__c> getStopsByTripId(Set<Id> tripId){
        return [
                SELECT
                        Id,
                        Address__c,
                        StopOrder__c,
                        TravelTime__c,
                        Trip__c,
                        Customer__c,
                        StopStartedMessage__c,
                        TripStartedMessage__c,
                        Customer__r.MobilePhone,
                        StopComplete__c,
                        Customer__r.FirstName,
                        Customer__r.LastName,
                        Service__r.ContactName__c,
                        Service__r.DriverName__c,
                        Service__r.CopilotName__c,
                        Service__r.Copilot2Name__c,
                        Service__r.Location__r.City__c
                FROM Stop__c
                WHERE Trip__c IN :tripId
                ORDER BY StopOrder__c ASC
        ];
    }

    public List<Stop__c> byId(Set<Id> stopIds){
        return [
                SELECT
                        Id,
                        Address__c,
                        StopOrder__c,
                        TravelTime__c,
                        TripStartedMessage__c,
                        StopStartedMessage__c,
                        Customer__c,
                        Trip__c,
                        Customer__r.MobilePhone,
                        Customer__r.FirstName,
                        Customer__r.LastName,
                        Service__r.ContactName__c,
                        Service__r.DriverName__c,
                        Service__r.CopilotName__c,
                        Service__r.Copilot2Name__c
                FROM Stop__c
                WHERE Id IN :stopIds
                ORDER BY StopOrder__c ASC
        ];
    }


    public List<Stop__c> getIncompleteStopsById(Set<Id> tripIds){
        return [
                SELECT
                        Id,
                        Address__c,
                        StopOrder__c,
                        TravelTime__c,
                        TripStartedMessage__c,
                        StopStartedMessage__c,
                        StopComplete__c,
                        Customer__c,
                        Trip__c,
                        Customer__r.MobilePhone,
                        Customer__r.FirstName,
                        Customer__r.LastName,
                        Service__r.Location__r.City__c,
                        Service__r.ContactName__c,
                        Service__r.DriverName__c,
                        Service__r.CopilotName__c,
                        Service__r.Copilot2Name__c
                FROM Stop__c
                WHERE Trip__c IN :tripIds AND StopComplete__c = NULL
                ORDER BY StopOrder__c DESC
        ];
    }
}