force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location (NWFB)</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations (NWFB)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pickup__c/Pickup__c.object-meta.xml
<CustomObject>
    <label>Pickup</label>
    <nameField>
        <label>Pickup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pickups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pickup__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>Date (1st Choice)</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Pickup__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Pickups</relationshipLabel>
    <relationshipName>Pickups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pickup__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pickup__c/fields/Stop__c.field-meta.xml
<CustomField>
    <fullName>Stop__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Stop</label>
    <referenceTo>Stop__c</referenceTo>
    <relationshipLabel>Pickups</relationshipLabel>
    <relationshipName>Pickups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service__c/Service__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>Request</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Processing</fullName>
                <default>true</default>
                <label>Processing</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Routing</fullName>
            </value>
            <value>
                <fullName>Shopping</fullName>
            </value>
            <value>
                <fullName>Delivery</fullName>
            </value>
            <value>
                <fullName>Pick Up</fullName>
            </value>
            <value>
                <fullName>Review</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
                <isActive>false</isActive>
                <label>Active</label>
            </value>
            <value>
                <fullName>Complete</fullName>
                <isActive>false</isActive>
                <label>Complete</label>
            </value>
            <value>
                <fullName>Draft</fullName>
                <isActive>false</isActive>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Expiring</fullName>
                <isActive>false</isActive>
                <label>Expiring</label>
            </value>
            <value>
                <fullName>Items Owed</fullName>
                <isActive>false</isActive>
                <label>Items Owed</label>
            </value>
            <value>
                <fullName>No Call / No Show</fullName>
                <isActive>false</isActive>
                <label>No Call / No Show</label>
            </value>
            <value>
                <fullName>Re-Delivery</fullName>
                <isActive>false</isActive>
                <label>Re-Delivery</label>
            </value>
            <value>
                <fullName>Served</fullName>
                <isActive>false</isActive>
                <label>Served</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service__c/fields/Stop__c.field-meta.xml
<CustomField>
    <fullName>Stop__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Stop</label>
    <referenceTo>Stop__c</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Trip__c.field-meta.xml
<CustomField>
    <fullName>Trip__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Trip</label>
    <referenceTo>Trip__c</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stop__c/Stop__c.object-meta.xml
<CustomObject>
    <label>Stop</label>
    <nameField>
        <label>Stop Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stops</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stop__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <formula>Service__r.City__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>City</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stop__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>Service__c</referenceTo>
    <relationshipLabel>Stops</relationshipLabel>
    <relationshipName>Stops</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stop__c/fields/Trip__c.field-meta.xml
<CustomField>
    <fullName>Trip__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Trip</label>
    <referenceTo>Trip__c</referenceTo>
    <relationshipLabel>Stops</relationshipLabel>
    <relationshipName>Stops</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trip__c/Trip__c.object-meta.xml
<CustomObject>
    <label>Trip</label>
    <nameField>
        <label>Trips Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trips</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Trip__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Trips</relationshipLabel>
    <relationshipName>Trips</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trip__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>Service__c</referenceTo>
    <relationshipLabel>Trips</relationshipLabel>
    <relationshipName>Trips</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trip__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Started</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TripTabComponentController.cls
public without sharing class TripTabComponentController {
    public TripTabComponentController() {

    }
    @AuraEnabled(cacheable = true)
    public static List<Tab> getLocations(){
        try {
            Map<String,Tab> tabs = new Map<String,Tab>();
            List<Location__c> locations = [SELECT Id,Name FROM Location__c];
            Map<Id,Trip__c> trips = new Map<Id,Trip__c>([SELECT Id,Name, Date__c, Location__c, Status__c, (SELECT Id FROM Stops__r) FROM Trip__c]);
            Map<Id,Stop__c> stopMap = new Map<Id,Stop__c>([SELECT Id FROM Stop__c WHERE Trip__c IN : trips.keySet()]);
            List<Service__c> requests = ServiceSelector.getInstance().getServicesByStopsIds(stopMap.keySet()); 
            List<Pickup__c> pickups = PickupSelector.getInstance().getPickupsByStopsIds(stopMap.keySet());
            Map<String,Trip> tripsMap = new Map<String,Trip>();
            
            for(Trip__c trip : trips.values()){
                tripsMap.put(trip.Id, new Trip(trip.Id));
                System.debug(new Trip(trip.Id));
            }

            for(Service__c request : requests){
                Trip trip = tripsMap.get(request.Stop__r.Trip__c) != null ? tripsMap.get(request.Stop__r.Trip__c) : new Trip(request.Stop__r.Trip__c);
                trip.deliveries += 1;
                //trip.destination += request.City__c;
                trip.destination += trip.destination == '' ? request.Name : ', ' + request.Name;
                tripsMap.put(trip.id, trip);
            }

            for(Pickup__c pickup : pickups){
                Trip trip = tripsMap.get(pickup.Stop__r.Trip__c) != null ? tripsMap.get(pickup.Stop__r.Trip__c) : new Trip(pickup.Stop__r.Trip__c);
                trip.pickups += 1;
                //trip.destination += pickup.City__c;
                
                trip.destination += trip.destination == '' ? pickup.Name : ', ' + pickup.Name;
                tripsMap.put(trip.id, trip);
            }

            for(Trip trip : tripsMap.values()){
                trip.tripDate = trips.get(trip.id).Date__c;
                trip.locationId = trips.get(trip.id).Location__c;
                trip.status = trips.get(trip.id).Status__c;
                trip.trip = trips.get(trip.id);
                tripsMap.put(trip.id, trip);
                System.debug(trip);
            }
            System.debug(tripsMap);
            
            for(Location__c loc : locations){
                Tab tab = new Tab();
                tab.name = loc.Name;
                tab.id = loc.Id;
                tabs.put(tab.id,tab);
            }
            
            for(Trip trip : tripsMap.values()){
                Tab tab = tabs.get(trip.locationId);
                if(trip.status == 'Active'){
                    tab.activeData.add(trip);
                } else if(trip.status == 'Completed'){
                    tab.completeData.add(trip);
                } else if(trip.status == 'Pending'){
                    tab.pendingData.add(trip);
                }
                tabs.put(trip.locationId, tab);
            }

            return tabs.values();
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    public class Tab {
        @AuraEnabled
        public List<Trip> activeData {get;set;}
        @AuraEnabled
        public List<Trip> completeData {get;set;}
        @AuraEnabled
        public List<Trip> pendingData {get;set;}
        @AuraEnabled
        public Object name {get;set;}
        @AuraEnabled
        public Id id {get;set;}

        Tab(){
            this.activeData = new List<Trip>();
            this.completeData = new List<Trip>();
            this.pendingData = new List<Trip>();
        }
    }
    public class Trip {
        @AuraEnabled
        public Date tripDate {get;set;}
        @AuraEnabled
        public Id locationId {get;set;}
        @AuraEnabled
        public Trip__c trip {get;set;}
        @AuraEnabled
        public Id id {get;set;}
        @AuraEnabled
        public String destination {get;set;}
        @AuraEnabled
        public String status {get;set;}
        @AuraEnabled
        public Integer pickups {get;set;}
        @AuraEnabled
        public Integer deliveries {get;set;}

        Trip(Id id){
            this.id = id;
            this.pickups = 0;
            this.deliveries = 0;
            this.destination = '';
        }
    }
}