force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location (NWFB)</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations (NWFB)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Location__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <formula>Street__c + &apos;, &apos; 
+ City__c + &apos;, &apos; + State__c + &apos;, &apos; + PostalCode__c + &apos;.&apos;</formula>
    <label>Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service__c/Service__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/ContactName__c.field-meta.xml
<CustomField>
    <fullName>ContactName__c</fullName>
    <formula>Contact__r.Full_Contact_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contact Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Copilot2Name__c.field-meta.xml
<CustomField>
    <fullName>Copilot2Name__c</fullName>
    <formula>Trip__r.CoPilot2__r.FirstName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Copilot 2 Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/CopilotName__c.field-meta.xml
<CustomField>
    <fullName>CopilotName__c</fullName>
    <formula>Trip__r.CoPilot1__r.FirstName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Copilot Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/DriverName__c.field-meta.xml
<CustomField>
    <fullName>DriverName__c</fullName>
    <formula>Trip__r.Driver__r.FirstName + &apos; &apos; + Trip__r.Driver__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Driver Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>Request</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/RecordTypeName__c.field-meta.xml
<CustomField>
    <fullName>RecordTypeName__c</fullName>
    <formula>RecordType.DeveloperName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>RecordType Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Processing</fullName>
                <default>true</default>
                <label>Processing</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Routing</fullName>
            </value>
            <value>
                <fullName>Shopping</fullName>
            </value>
            <value>
                <fullName>Delivery</fullName>
            </value>
            <value>
                <fullName>Pick Up</fullName>
            </value>
            <value>
                <fullName>Review</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
                <isActive>false</isActive>
                <label>Active</label>
            </value>
            <value>
                <fullName>Complete</fullName>
                <isActive>false</isActive>
                <label>Complete</label>
            </value>
            <value>
                <fullName>Draft</fullName>
                <isActive>false</isActive>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Expiring</fullName>
                <isActive>false</isActive>
                <label>Expiring</label>
            </value>
            <value>
                <fullName>Items Owed</fullName>
                <isActive>false</isActive>
                <label>Items Owed</label>
            </value>
            <value>
                <fullName>No Call / No Show</fullName>
                <isActive>false</isActive>
                <label>No Call / No Show</label>
            </value>
            <value>
                <fullName>Re-Delivery</fullName>
                <isActive>false</isActive>
                <label>Re-Delivery</label>
            </value>
            <value>
                <fullName>Served</fullName>
                <isActive>false</isActive>
                <label>Served</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service__c/fields/Stop__c.field-meta.xml
<CustomField>
    <fullName>Stop__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Stop</label>
    <referenceTo>Stop__c</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Trip__c.field-meta.xml
<CustomField>
    <fullName>Trip__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Trip</label>
    <referenceTo>Trip__c</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service__c/recordTypes/DonationPickup.recordType-meta.xml
<RecordType>
    <fullName>DonationPickup</fullName>
    <active>true</active>
    <label>Donation Pickup</label>
</RecordType>

force-app/main/default/objects/ServiceItem__c/ServiceItem__c.object-meta.xml
<CustomObject>
    <label>Service Item</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Service Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ServiceItem__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product__c.Archived__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Service Items</relationshipLabel>
    <relationshipName>ServiceItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceItem__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <label>Service</label>
    <referenceTo>Service__c</referenceTo>
    <relationshipLabel>Service Items</relationshipLabel>
    <relationshipName>ServiceItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ServiceItem__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
                <default>true</default>
                <label>Requested</label>
            </value>
            <value>
                <fullName>Not Available</fullName>
            </value>
            <value>
                <fullName>Staged</fullName>
            </value>
            <value>
                <fullName>Not Loaded</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Loaded</fullName>
            </value>
            <value>
                <fullName>Shopping Declined</fullName>
            </value>
            <value>
                <fullName>Not Delivered</fullName>
            </value>
            <value>
                <fullName>Item Rejected</fullName>
            </value>
            <value>
                <fullName>Backlog</fullName>
                <isActive>false</isActive>
                <label>Backlog</label>
            </value>
            <value>
                <fullName>Declined</fullName>
                <isActive>false</isActive>
                <label>Declined</label>
            </value>
            <value>
                <fullName>Delivered</fullName>
                <isActive>false</isActive>
                <label>Delivered</label>
            </value>
            <value>
                <fullName>Received</fullName>
                <isActive>false</isActive>
                <label>Received</label>
            </value>
            <value>
                <fullName>Referred</fullName>
                <isActive>false</isActive>
                <label>Referred</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServiceItem__c/fields/Stop__c.field-meta.xml
<CustomField>
    <fullName>Stop__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Stop</label>
    <referenceTo>Stop__c</referenceTo>
    <relationshipLabel>Service Items</relationshipLabel>
    <relationshipName>ServiceItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stop__c/Stop__c.object-meta.xml
<CustomObject>
    <label>Stop</label>
    <nameField>
        <label>Stop Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stops</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stop__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <formula>Service__r.Address__c + &apos; &apos; + Service__r.City__c  + &apos; &apos; + Service__r.State__c + &apos; &apos; + Service__r.Zip__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stop__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>Service__c</referenceTo>
    <relationshipLabel>Stops</relationshipLabel>
    <relationshipName>Stops</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stop__c/fields/StopComplete__c.field-meta.xml
<CustomField>
    <fullName>StopComplete__c</fullName>
    <label>Stop Complete</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Stop__c/fields/StopStartedMessage__c.field-meta.xml
<CustomField>
    <fullName>StopStartedMessage__c</fullName>
    <label>Stop Started Message</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Stop__c/fields/StopTime__c.field-meta.xml
<CustomField>
    <fullName>StopTime__c</fullName>
    <label>Stop Time</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stop__c/fields/Trip__c.field-meta.xml
<CustomField>
    <fullName>Trip__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Trip</label>
    <referenceTo>Trip__c</referenceTo>
    <relationshipLabel>Stops</relationshipLabel>
    <relationshipName>Stops</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stop__c/fields/TripStartedMessage__c.field-meta.xml
<CustomField>
    <fullName>TripStartedMessage__c</fullName>
    <label>Trip Started Message</label>
    <length>100000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Trip__c/Trip__c.object-meta.xml
<CustomObject>
    <label>Trip</label>
    <nameField>
        <label>Trips Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trips</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Trip__c/fields/CoPilotName__c.field-meta.xml
<CustomField>
    <fullName>CoPilotName__c</fullName>
    <formula>copilot__r.Full_Contact_Name__c</formula>
    <label>Co-pilot Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trip__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Trips</relationshipLabel>
    <relationshipName>Trips</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trip__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>Service__c</referenceTo>
    <relationshipLabel>Trips</relationshipLabel>
    <relationshipName>Trips</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trip__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Started</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/StopDao.cls
public without sharing class StopDao extends GenericDao {
    @TestVisible
    private static StopDao mock;

    public StopDao() {
    }

    private StopDao(List<SObject> stops, Map<Id, SObject> oldStopsById) {
        super(stops, oldStopsById);
    }
    private StopDao(List<SObject> stops) {
        super(stops);
    }

    public static StopDao getInstance() {
        if (Test.isRunningTest() && mock != null) {
            return mock;
        } else {
            return new StopDao(new List<Stop__c>());
        }
    }

    public class Factory implements TriggerHandlerFactory {
        public TriggerHandler create(List<SObject> objects, Map<Id, SObject> oldStopsById) {
            return new StopDao(objects, oldStopsById);
        }
    }

    public override void afterInsert() {
        setTripStartedMessage();
        rollup();
    }

    public override void beforeInsert() {
        setStopName();
        calculateStopTime();
    }

    public override void beforeUpdate() {
        setStopName();
        calculateStopTime();
    }
    public override void afterUpdate() {
        stopComplete();
        setTripStartedMessage();
        rollup();
    }
    public override void afterDelete() {
        rollup();
    }

    private void rollup() {
        Database.update(dlrs.RollupService.rollup(this.records), false);
    }

    private void setStopName() {
        for (Stop__c stop : (List<Stop__c>) this.records) {
            stop.Name = stop.Address__c;
        }
    }

    private void calculateStopTime() {
        Set<Id> serviceIds = new Set<Id>();

        for (Stop__c stop : (List<Stop__c>) records) {
            if (stop.Service__c == null) continue;
            serviceIds.add(stop.Service__c);
        }

        Map<Id, SObject> serviceByIds = Utils.listToMap(
                'Id',
                ServiceSelector.getInstance().getServiceByIds(serviceIds)
        );

        List<String> usuallyItems = new List<String>{
                'Lamp',
                'Kitchen Items (boxed/bagged)',
                'Linens (boxed/bagged)',
                'Framed Art',
                'Appliance',
                'Mirror',
                'Accessories'
        };

        for (Stop__c stop : (List<Stop__c>) records) {
            Service__c currentService = (Service__c) serviceByIds.get(stop.Service__c);
            if (currentService == null) continue;

            if (currentService.RecordTypeName__c != 'DonationPickup') {
                stop.StopTime__c = 30;
                continue;
            }

            if (currentService.ServiceItems__r == null || currentService.ServiceItems__r.isEmpty()) continue;

            Decimal totalItems = 0;

            for (ServiceItem__c serviceItem : currentService.ServiceItems__r) {
                if (usuallyItems.contains(serviceItem.Product__r.Name)) {
                    totalItems++;
                    continue;
                }

                totalItems += serviceItem.Quantity__c;
            }

            if (totalItems >= 1 && totalItems <= 3) {
                stop.StopTime__c = 15;
            } else if (totalItems >= 4 && totalItems <= 5) {
                stop.StopTime__c = 20;
            } else if (totalItems >= 6 && totalItems <= 8) {
                stop.StopTime__c = 30;
            } else if (totalItems >= 9 && totalItems <= 12) {
                stop.StopTime__c = 45;
            } else if (totalItems >= 13) {
                stop.StopTime__c = 60;
            }
        }
    }

    private void setTripStartedMessage() {
        Map<Id, Stop__c> stopById = new Map<Id, Stop__c>((List<Stop__c>) records);
        List<Stop__c> stops = new StopSelector().byId(stopById.keySet());
        List<Stop__c> pendingStops = new List<Stop__c>();

        for (Stop__c stop : stops) {
            if (!String.isEmpty(stop.TripStartedMessage__c)) continue;

            String driverName = stop.Service__r.DriverName__c != null
                ? stop.Service__r.DriverName__c
                : '';

            String copilotName = stop.Service__r.CopilotName__c != null
                ? stop.Service__r.CopilotName__c
                : '';

            String copilot2Name = stop.Service__r.Copilot2Name__c != null
                ? stop.Service__r.Copilot2Name__c
                : '';

            String tripStartedMessage = 'Hello ' + stop.Service__r.ContactName__c + ',\n' +
                    '\n' +
                    'The NW Furniture Bank truck has been dispatched from the warehouse for pick-up and delivery service.  ' +
                    'Below is the crew that will be providing service today.  ' +
                    'We will send a text message when are leaving to head your way.\n' +
                    '\n' +
                    'Driver: ' + driverName + '\n' +
                    'Copilot: ' + copilotName + '\n' +
                    'Copilot 2: ' + copilot2Name ;

            String stopStartedMessage = 'This is NW Furniture Bank’s truck crew. We are on our way to your location. ' +
                    'We’ll see you shortly!';

            stop.StopStartedMessage__c = stopStartedMessage;
            stop.TripStartedMessage__c = tripStartedMessage;
            pendingStops.add(stop);
        }

        TriggerManagement.disableTrigger('StopTrigger');
        update pendingStops;
        TriggerManagement.enableTrigger('StopTrigger');
    }

    private void stopComplete() {
        Map<Id, Stop__c> oldStops = (Map<Id, Stop__c>) this.oldRecordsById;
        Set<Id> tripIds = new Set<Id>();

        Schema.DescribeSObjectResult describeService = Service__c.SObjectType.getDescribe();
        Map<String, Schema.RecordTypeInfo> recordTypeInfoMap = describeService.getRecordTypeInfosByName();

        String generalPickUpDeveloperName = recordTypeInfoMap.get('General Pickup').getDeveloperName();
        String donationPickupDeveloperName = recordTypeInfoMap.get('Donation Pickup').getDeveloperName();

        for (Stop__c stop : (List<Stop__c>) this.records) {
            Stop__c oldStop = oldStops.get(stop.Id);
            Boolean wasChanged = (stop.StopComplete__c != null && (oldStop.StopComplete__c != stop.StopComplete__c));
            
            if (!wasChanged) continue;
            Date stopCompletedDate = stop.StopComplete__c.date();

            if (stopCompletedDate > Date.today()) continue;

            tripIds.add(stop.Trip__c);
        }
        
        Map<Id, Trip__c> tripMap = new Map<Id, Trip__c>(TripSelector.getInstance().getTripByIdSet(tripIds));
        Map<Id, Service__c> servicesToUpdate = new Map<Id, Service__c>();

        sendSMSToNextStop(tripIds);
        
        for (Stop__c stop : (List<Stop__c>) this.records) {
            String serviceStatus = tripMap?.get(stop.Trip__c)?.Service__r.Status__c;
            String serviceRecordType = tripMap?.get(stop.Trip__c)?.Service__r.RecordType.DeveloperName;

            if (serviceStatus != 'Pick Up' && serviceStatus != 'Delivery') continue;
            if (serviceRecordType != generalPickUpDeveloperName && serviceRecordType != donationPickupDeveloperName) continue;
           
            Service__c service = new Service__c (
                Id = tripMap?.get(stop.Trip__c)?.Service__c,
                Status__c = 'Review'
            );

            servicesToUpdate.put(service.Id, service);
        }

        if (servicesToUpdate == null || servicesToUpdate.isEmpty()) return;
        TriggerManagement.disableTrigger('ServiceTrigger');
        Database.update(servicesToUpdate.values(), false);
        TriggerManagement.enableTrigger('ServiceTrigger');
    }

    private static void sendSMSToNextStop(Set<Id> tripIds) {
        Map<Id, SObject> stopsById = Utils.listToMap(
            'Trip__c',
            new StopSelector().getIncompleteStopsById(tripIds)
        );

        for (Id tripId : tripIds) {
            Stop__c nextStop = (Stop__c) stopsById.get(tripId);

            if (nextStop == null || nextStop.StopComplete__c != null) continue;

            if (!Test.isRunningTest()) {
                System.enqueueJob(
                        new SendSMSQueueable(
                                nextStop.Service__r.Location__r.City__c,
                                nextStop.Customer__r.MobilePhone,
                                nextStop.StopStartedMessage__c
                        )
                );
            }
        }
    }
}