force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location (NWFB)</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations (NWFB)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Location__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <formula>Street__c + &apos;, &apos; 
+ City__c + &apos;, &apos; + State__c + &apos;, &apos; + PostalCode__c + &apos;.&apos;</formula>
    <label>Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pickup__c/Pickup__c.object-meta.xml
<CustomObject>
    <label>Pickup</label>
    <nameField>
        <label>Pickup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pickups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pickup__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Pickups</relationshipLabel>
    <relationshipName>Pickups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pickup__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>Date (1st Choice)</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Pickup__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Pickups</relationshipLabel>
    <relationshipName>Pickups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pickup__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pickup__c/fields/Stop__c.field-meta.xml
<CustomField>
    <fullName>Stop__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Stop</label>
    <referenceTo>Stop__c</referenceTo>
    <relationshipLabel>Pickups</relationshipLabel>
    <relationshipName>Pickups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service__c/Service__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Client contact record attached to this request</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Services (Contact)</relationshipLabel>
    <relationshipName>Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>Request</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Processing</fullName>
                <default>true</default>
                <label>Processing</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Routing</fullName>
            </value>
            <value>
                <fullName>Shopping</fullName>
            </value>
            <value>
                <fullName>Delivery</fullName>
            </value>
            <value>
                <fullName>Pick Up</fullName>
            </value>
            <value>
                <fullName>Review</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
                <isActive>false</isActive>
                <label>Active</label>
            </value>
            <value>
                <fullName>Complete</fullName>
                <isActive>false</isActive>
                <label>Complete</label>
            </value>
            <value>
                <fullName>Draft</fullName>
                <isActive>false</isActive>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Expiring</fullName>
                <isActive>false</isActive>
                <label>Expiring</label>
            </value>
            <value>
                <fullName>Items Owed</fullName>
                <isActive>false</isActive>
                <label>Items Owed</label>
            </value>
            <value>
                <fullName>No Call / No Show</fullName>
                <isActive>false</isActive>
                <label>No Call / No Show</label>
            </value>
            <value>
                <fullName>Re-Delivery</fullName>
                <isActive>false</isActive>
                <label>Re-Delivery</label>
            </value>
            <value>
                <fullName>Served</fullName>
                <isActive>false</isActive>
                <label>Served</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service__c/fields/Stop__c.field-meta.xml
<CustomField>
    <fullName>Stop__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Stop</label>
    <referenceTo>Stop__c</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/SubType__c.field-meta.xml
<CustomField>
    <fullName>SubType__c</fullName>
    <label>Sub Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Will Call</fullName>
            </value>
            <value>
                <fullName>Delivery</fullName>
            </value>
            <value>
                <fullName>Hope Run</fullName>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>Hope Del.</fullName>
            </value>
            <value>
                <fullName>Donation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service__c/fields/Trip__c.field-meta.xml
<CustomField>
    <fullName>Trip__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Trip</label>
    <referenceTo>Trip__c</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stop__c/Stop__c.object-meta.xml
<CustomObject>
    <label>Stop</label>
    <nameField>
        <label>Stop Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stops</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stop__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <formula>Service__r.Address__c + &apos; &apos; + Service__r.City__c  + &apos; &apos; + Service__r.State__c + &apos; &apos; + Service__r.Zip__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stop__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>Service__c</referenceTo>
    <relationshipLabel>Stops</relationshipLabel>
    <relationshipName>Stops</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stop__c/fields/Trip__c.field-meta.xml
<CustomField>
    <fullName>Trip__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Trip</label>
    <referenceTo>Trip__c</referenceTo>
    <relationshipLabel>Stops</relationshipLabel>
    <relationshipName>Stops</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trip__c/Trip__c.object-meta.xml
<CustomObject>
    <label>Trip</label>
    <nameField>
        <label>Trips Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trips</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Trip__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Trips</relationshipLabel>
    <relationshipName>Trips</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trip__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Trips</relationshipLabel>
    <relationshipName>Trips</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trip__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>Service__c</referenceTo>
    <relationshipLabel>Trips</relationshipLabel>
    <relationshipName>Trips</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trip__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Started</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trip__c/fields/Truck__c.field-meta.xml
<CustomField>
    <fullName>Truck__c</fullName>
    <label>Truck</label>
    <referenceTo>Truck__c</referenceTo>
    <relationshipLabel>Trips</relationshipLabel>
    <relationshipName>Trips</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Truck__c/Truck__c.object-meta.xml
<CustomObject>
    <label>Truck</label>
    <nameField>
        <label>Truck Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trucks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Truck__c/fields/LicensePlate__c.field-meta.xml
<CustomField>
    <fullName>LicensePlate__c</fullName>
    <label>License Plate</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Truck__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Trucks</relationshipLabel>
    <relationshipName>Trucks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TruckSchedulerControllerTest.cls
/**
 * Created by Gustavo on 05/01/24.
 */

@IsTest
private class TruckSchedulerControllerTest {
    @IsTest
    static void testBehavior() {

        TruckSchedulerController.Marker marker = new TruckSchedulerController.Marker();
        TruckSchedulerController.Location location = new TruckSchedulerController.Location();

        location.PostalCode='123';
        location.Street='street';
        location.Country='country';
        location.State = 'state';





        Schema.DescribeSObjectResult describeService = Service__c.SObjectType.getDescribe();
        Map<String, Schema.RecordTypeInfo> recordTypeInfoMap = describeService.getRecordTypeInfosByName();

        Location__c locations = new Location__c(
                Name = 'Test - NWFB'
        );
        insert locations;

        Truck__c truck = new Truck__c(
                LicensePlate__c = '00001',
                Active__c = true
        );
        insert truck;
        Pickup__c pick = new Pickup__c();
        insert pick;
        Trip__c trip = new Trip__c(
                Name = 'Test Trip',
                Date__c = Date.today(),
                Location__c = locations.Id,
                Status__c = 'Active',
                Truck__c = truck.Id
        );
        insert trip;
        Contact contact = new Contact(
                FirstName = 'Test',
                LastName = 'Test'
        );
        insert contact;

        Service__c service = new Service__c(
                Contact__c = contact.Id,
                Address__c = 'Teste',
                Status__c = 'Routing',
                RecordTypeId = recordTypeInfoMap.get('General Pickup').getRecordTypeId(),
                SubType__c = 'Event',
                Date__c = System.today()
        );
        insert service;


        Stop__c stop = new Stop__c(
                Service__c = service.Id
        );
        insert stop;

        TruckSchedulerController.getPickupsAndRequests(System.today());

        marker.isChecked = true;
        marker.id=pick.Id;
        marker.contact='contact';
        marker.contactName='name';
        marker.eta='10';
        marker.items='items';
        marker.label='label';
        marker.value='value';
        marker.timeFrame='timeframe';
        marker.title='Pickup';
        marker.description='description';
        marker.location=location;
        marker.mapIcon='mapIcon';
        marker.icon='icon';
        marker.numberOfItems='number';
        marker.isAddable='isAdd';
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new MapApiCallMock());
        TruckSchedulerController.createStop(marker, trip.Id);
        marker.title = 'Delivery';
        marker.id =service.id;
        Test.setMock(HttpCalloutMock.class, new MapApiCallMock());
        TruckSchedulerController.createStop(marker, trip.Id);
        Test.stopTest();
    }

    @IsTest
    static void testBehaviorCalculate() {

        TruckSchedulerController.Marker marker = new TruckSchedulerController.Marker();
        TruckSchedulerController.Location location = new TruckSchedulerController.Location();

        location.PostalCode='123';
        location.Street='street';
        location.Country='country';
        location.State = 'state';





        Schema.DescribeSObjectResult describeService = Service__c.SObjectType.getDescribe();
        Map<String, Schema.RecordTypeInfo> recordTypeInfoMap = describeService.getRecordTypeInfosByName();

        Location__c locations = new Location__c(
                Name = 'Test - NWFB'
        );
        insert locations;

        Truck__c truck = new Truck__c(
                LicensePlate__c = '00001',
                Active__c = true
        );
        insert truck;
        Pickup__c pick = new Pickup__c();
        insert pick;
        Trip__c trip = new Trip__c(
                Name = 'Test Trip',
                Date__c = Date.today(),
                Location__c = locations.Id,
                Status__c = 'Active',
                Truck__c = truck.Id
        );
        insert trip;
        Contact contact = new Contact(
                FirstName = 'Test',
                LastName = 'Test'
        );
        insert contact;

        Service__c service = new Service__c(
                Contact__c = contact.Id,
                Address__c = 'Teste',
                Status__c = 'Routing',
                RecordTypeId = recordTypeInfoMap.get('General Pickup').getRecordTypeId(),
                SubType__c = 'Event',
                Date__c = System.today()
        );
        insert service;


        Stop__c stop = new Stop__c(
                Service__c = service.Id
        );
        insert stop;

        TruckSchedulerController.getPickupsAndRequests(System.today());

        marker.isChecked = true;
        marker.id=pick.Id;
        marker.contact='contact';
        marker.contactName='name';
        marker.eta='10';
        marker.items='items';
        marker.label='label';
        marker.value='value';
        marker.timeFrame='timeframe';
        marker.title='Pickup';
        marker.description='description';
        marker.location=location;
        marker.mapIcon='mapIcon';
        marker.icon='icon';
        marker.numberOfItems='number';
        marker.isAddable='isAdd';
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new MapApiCallMock());
        TruckSchedulerController.calculateTrip(trip.Id);
        Test.stopTest();
    }
}