force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location (NWFB)</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations (NWFB)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service__c/Service__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service__c/fields/Delivery_Type__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Type__c</fullName>
    <label>Delivery Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hope Delivery</fullName>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>Will Call</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>Request</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Processing</fullName>
                <default>true</default>
                <label>Processing</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Routing</fullName>
            </value>
            <value>
                <fullName>Shopping</fullName>
            </value>
            <value>
                <fullName>Delivery</fullName>
            </value>
            <value>
                <fullName>Pick Up</fullName>
            </value>
            <value>
                <fullName>Review</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
                <isActive>false</isActive>
                <label>Active</label>
            </value>
            <value>
                <fullName>Complete</fullName>
                <isActive>false</isActive>
                <label>Complete</label>
            </value>
            <value>
                <fullName>Draft</fullName>
                <isActive>false</isActive>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Expiring</fullName>
                <isActive>false</isActive>
                <label>Expiring</label>
            </value>
            <value>
                <fullName>Items Owed</fullName>
                <isActive>false</isActive>
                <label>Items Owed</label>
            </value>
            <value>
                <fullName>No Call / No Show</fullName>
                <isActive>false</isActive>
                <label>No Call / No Show</label>
            </value>
            <value>
                <fullName>Re-Delivery</fullName>
                <isActive>false</isActive>
                <label>Re-Delivery</label>
            </value>
            <value>
                <fullName>Served</fullName>
                <isActive>false</isActive>
                <label>Served</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service__c/fields/Stop__c.field-meta.xml
<CustomField>
    <fullName>Stop__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Stop</label>
    <referenceTo>Stop__c</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Trip__c.field-meta.xml
<CustomField>
    <fullName>Trip__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Trip</label>
    <referenceTo>Trip__c</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service__c/recordTypes/ClientRequest.recordType-meta.xml
<RecordType>
    <fullName>ClientRequest</fullName>
    <active>true</active>
    <label>Client Request</label>
</RecordType>

force-app/main/default/objects/Stop__c/Stop__c.object-meta.xml
<CustomObject>
    <label>Stop</label>
    <nameField>
        <label>Stop Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stops</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stop__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <formula>Service__r.City__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>City</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stop__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Stops</relationshipLabel>
    <relationshipName>Stops</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stop__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>Service__c</referenceTo>
    <relationshipLabel>Stops</relationshipLabel>
    <relationshipName>Stops</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stop__c/fields/StopComplete__c.field-meta.xml
<CustomField>
    <fullName>StopComplete__c</fullName>
    <label>Stop Complete</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Stop__c/fields/StopStartedMessage__c.field-meta.xml
<CustomField>
    <fullName>StopStartedMessage__c</fullName>
    <label>Stop Started Message</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Stop__c/fields/Trip__c.field-meta.xml
<CustomField>
    <fullName>Trip__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Trip</label>
    <referenceTo>Trip__c</referenceTo>
    <relationshipLabel>Stops</relationshipLabel>
    <relationshipName>Stops</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stop__c/fields/TripStartedMessage__c.field-meta.xml
<CustomField>
    <fullName>TripStartedMessage__c</fullName>
    <label>Trip Started Message</label>
    <length>100000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Trip__c/Trip__c.object-meta.xml
<CustomObject>
    <label>Trip</label>
    <nameField>
        <label>Trips Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trips</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Trip__c/fields/CustomName__c.field-meta.xml
<CustomField>
    <fullName>CustomName__c</fullName>
    <label>Custom Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trip__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Trips</relationshipLabel>
    <relationshipName>Trips</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trip__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>Service__c</referenceTo>
    <relationshipLabel>Trips</relationshipLabel>
    <relationshipName>Trips</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trip__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Started</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TripDao.cls
public without sharing class TripDao extends GenericDao {
    @TestVisible
    private static TripDao mock;

    public TripDao() {
    }

    private TripDao(List<SObject> services, Map<Id, SObject> oldServicesById) {
        super(services, oldServicesById);
    }

    private TripDao(List<SObject> services) {
        super(services);
    }

    public static TripDao getInstance() {
        if (Test.isRunningTest() && mock != null) {
            return mock;
        } else {
            return new TripDao(new List<Stop__c>());
        }
    }

    public override void afterInsert() {
        rollup();
    }

    public override void afterUpdate() {
        sendSMSOnTripStart();
        rollup();
    }
    public override void afterDelete() {
        rollup();
    }

    public override void beforeInsert() {
        setTripName();
        setTripStatusAndDate();
    }

    public override void beforeUpdate() {
        setTripStatusAndDate();
        setStopTravelTimes();
    }

    private void rollup() {
        Database.update(dlrs.RollupService.rollup(this.records), false);
    }

    private void setStopTravelTimes(){
        Set<Id> tripIds = new Set<Id>();

        for (Trip__c trip : (List<Trip__c>) this.records) {
            tripIds.add(trip.Id);
        }

       System.enqueueJob(new GoogleMapsIntegrationQueuable(tripIds));
    }

    private void setTripStatusAndDate() {
        Map<Id, SObject> tripByService = Utils.listToMap('Service__c', this.records);

        Map<Id, SObject> servicesByIds = Utils.listToMap(
                'Id',
                (List<SObject>) new ServiceSelector().getServiceByIds(tripByService.keySet())
        );

        Map<Id, Trip__c> oldRecordsMap = new Map<Id, Trip__c>();
        oldRecordsMap = (Map<Id, Trip__c>) this.oldRecordsById;

        Map<Id, Service__c> serviceToUpdate = new Map<Id, Service__c>();

        for (Trip__c trip : (List<Trip__c>) this.records) {
            if (trip.Service__c == null || oldRecordsMap?.get(trip.Id)?.Service__c == trip.Service__c) continue;

            Service__c service = (Service__c) servicesByIds.get(trip.Service__c);

            if (service.Status__c != 'Routing' && oldRecordsMap?.get(trip.Id) == null) {
                trip.addError('Can not insert a trip if the Service Status is not "Routing"');
                continue;
            }

            if (service.RecordType.DeveloperName == 'ClientRequest' && service?.Delivery_Type__c == 'Will Call') {
                trip.addError('Can not select this status because the related Service Delivery type is a "will call"');
                continue;
            }

            service.Status__c = 'Shopping';
            serviceToUpdate.put(service.Id, service);
            trip.Date__c = service.Date__c;
        }

        TriggerManagement.disableTrigger('ServiceTrigger');
        if (!serviceToUpdate.isEmpty()) {
            Database.update(serviceToUpdate.values(), false);
        }
        TriggerManagement.enableTrigger('ServiceTrigger');

    }

    private void setTripName() {
        for (Trip__c trip : (List<Trip__c>) this.records) {
            if (trip.CustomName__c == null) continue;

            trip.Name = trip.CustomName__c + ' ' + trip.Date__c.format();
        }
    }

    private void sendSMSOnTripStart() {
        Set<Id> tripIds = new Set<Id>();

        for (Trip__c trip : (List<Trip__c>) records) {
            Trip__c oldTrip = (Trip__c) oldRecordsById.get(trip.Id);
            if (oldTrip.Status__c == 'Started' && trip.Status__c == 'Started') continue;
            if (trip.Status__c != 'Started') continue;
            tripIds.add(trip.Id);
        }

        Map<String, List<SObject>> stopsByTrip = Utils.listToMapLists(
                'Trip__c',
                new StopSelector().getStopsByTripId(tripIds)
        );


        for (Trip__c trip : (List<Trip__c>) records) {
            Trip__c oldTrip = (Trip__c) oldRecordsById.get(trip.Id);

            if (oldTrip.Status__c == 'Started' && trip.Status__c == 'Started') continue;
            if (trip.Status__c != 'Started') continue;

            List<Stop__c> stops = (List<Stop__c>) stopsByTrip.get(trip.Id);
            Stop__c firstStop = null;

            for (Stop__c stop : stops) {
                if (stop.StopComplete__c != null) continue;
                firstStop = stop;
                break;
            }

            if (firstStop == null) continue;

            System.enqueueJob(
                    new SendSMSQueueable(
                            firstStop.Service__r.Location__r.City__c,
                            firstStop.Customer__r.MobilePhone,
                            firstStop.TripStartedMessage__c
                    )
            );

            System.enqueueJob(
                    new SendSMSQueueable(
                            firstStop.Service__r.Location__r.City__c,
                            firstStop.Customer__r.MobilePhone,
                            firstStop.StopStartedMessage__c
                    )
            );
        }
    }

    public class Factory implements TriggerHandlerFactory {
        public TriggerHandler create(List<SObject> objects, Map<Id, SObject> oldObjectsById) {
            return new TripDao(objects, oldObjectsById);
        }
    }
}