force-app/main/default/objects/ServiceFeesSettings__mdt/ServiceFeesSettings__mdt.object-meta.xml
<CustomObject>
    <label>Service Fees Settings</label>
    <pluralLabel>Service Fees Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/ServiceFeesSettings__mdt/fields/DeliveryFeeAmount__c.field-meta.xml
<CustomField>
    <fullName>DeliveryFeeAmount__c</fullName>
    <label>Delivery Fee Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ServiceFeesSettings__mdt/fields/FeeAmount__c.field-meta.xml
<CustomField>
    <fullName>FeeAmount__c</fullName>
    <label>Fee Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CustomMetadataSelector.cls
public with sharing class CustomMetadataSelector {
    private static CustomMetadataSelector instance = null;

    public static CustomMetadataSelector getInstance() {
        if (instance == null) {
        instance = new CustomMetadataSelector();
        }
        return instance;
    }

    public List<ServiceFeesSettings__mdt> getMdtByStatus(){
        return [
            SELECT Id, FeeAmount__c, IsActive__c, DeveloperName, DeliveryFeeAmount__c
            FROM ServiceFeesSettings__mdt          
            WHERE IsActive__c = TRUE
        ];
    }
}