force-app/main/default/objects/Service__c/Service__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Processing</fullName>
                <default>true</default>
                <label>Processing</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Routing</fullName>
            </value>
            <value>
                <fullName>Shopping</fullName>
            </value>
            <value>
                <fullName>Delivery</fullName>
            </value>
            <value>
                <fullName>Pick Up</fullName>
            </value>
            <value>
                <fullName>Review</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
                <isActive>false</isActive>
                <label>Active</label>
            </value>
            <value>
                <fullName>Complete</fullName>
                <isActive>false</isActive>
                <label>Complete</label>
            </value>
            <value>
                <fullName>Draft</fullName>
                <isActive>false</isActive>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Expiring</fullName>
                <isActive>false</isActive>
                <label>Expiring</label>
            </value>
            <value>
                <fullName>Items Owed</fullName>
                <isActive>false</isActive>
                <label>Items Owed</label>
            </value>
            <value>
                <fullName>No Call / No Show</fullName>
                <isActive>false</isActive>
                <label>No Call / No Show</label>
            </value>
            <value>
                <fullName>Re-Delivery</fullName>
                <isActive>false</isActive>
                <label>Re-Delivery</label>
            </value>
            <value>
                <fullName>Served</fullName>
                <isActive>false</isActive>
                <label>Served</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/GenericDaoTest.cls
/**
 * Created by dudunato on 2019-08-12.
 */

@IsTest
private class GenericDaoTest {

    @IsTest
    static void testBehavior() {
    }

    @IsTest
    public static void listSObjects() {
        Contact contact = new Contact(
                FirstName = 'Test',
                LastName = 'Test'
        );
        insert contact;

        List<SObject> objects = GenericDao.getInstance().listSObjects(
                'Contact',
                new List<String>{'Name'},
                'AND Name != NULL'
        );

        System.assert(objects != null && !objects.isEmpty());
    }

    @IsTest
    public static void saveSObjects() {
        Contact contact = new Contact(
                FirstName = 'Test',
                LastName = 'Test'
        );

        List<SObject> savedObjects = GenericDao.getInstance().saveSObjects(new List<SObject>{contact});

        System.assert(savedObjects != null && !savedObjects.isEmpty());
    }

    @IsTest
    public static void getPicklist() {
        List<PicklistEnum.Entry> picklistValues = GenericDao.getInstance().getPicklist('Service__c', 'Status__c');
        System.assert(picklistValues != null && !picklistValues.isEmpty());
    }

    @IsTest
    public static void deleteSObjects() {
        Contact contact = new Contact(
                FirstName = 'Test',
                LastName = 'Test'
        );
        insert contact;
        List<SObject> deletedSObjects = GenericDao.getInstance().deleteSObjects(new List<SObject>{contact});


        System.assert(deletedSObjects != null && !deletedSObjects.isEmpty());
    }

    @IsTest
    public static void deleteSObjectsByFilter() {
        Contact contact = new Contact(
                FirstName = 'Test',
                LastName = 'Test'
        );
        insert contact;

        List<SObject> deletedSObjects = GenericDao.getInstance().deleteSObjectsByFilter(
                'Contact',
                'AND FirstName = \'Test\''
        );

        System.assert(deletedSObjects != null && !deletedSObjects.isEmpty());
    }
}