force-app/main/default/objects/Service__c/Service__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Client contact record attached to this request</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Services (Contact)</relationshipLabel>
    <relationshipName>Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/DedupActiveServicesBatchTest.cls
/**
 * Created by Eric Solari on 08/01/2024.
 */
@IsTest
public with sharing class DedupActiveServicesBatchTest {

    @IsTest
    public static void testBatch(){
        Account account = createAccount();
        insert account;
        Contact contact = createContact(account);
        insert contact;
        Service__c service = new Service__c(IsActive__c = true, Name ='test', State__c='WA', Contact__c=contact.id);
        insert service;
        DedupActiveServicesBatch sbc = new DedupActiveServicesBatch();
        Database.executeBatch(sbc, 10);
    }


    private static Contact createContact(Account account) {
        return new Contact(
                AccountId = account.Id,
                FirstName = 'Test Contact',
                LastName = 'Last name test contact',
                Email = 'testEmail@exemple.com',
                MobilePhone = '99999999'
        );

    }

    private static Account createAccount() {
        return new Account(
                Name = 'Test Account',
                Type = 'Agency',
                Active__c = true
        );
    }
}