force-app/main/default/objects/Service__c/Service__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service__c/fields/Processing_Fee__c.field-meta.xml
<CustomField>
    <fullName>Processing_Fee__c</fullName>
    <label>Processing Fee</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/SubTotal__c.field-meta.xml
<CustomField>
    <fullName>SubTotal__c</fullName>
    <label>Sub Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/TotalPaid__c.field-meta.xml
<CustomField>
    <fullName>TotalPaid__c</fullName>
    <label>Total Paid</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/TotalTaxableAmount__c.field-meta.xml
<CustomField>
    <fullName>TotalTaxableAmount__c</fullName>
    <label>Tax</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/InvoicePDFControllerTest.cls
/**
 * Created by Gustavo on 10/01/24.
 */

@IsTest
private class InvoicePDFControllerTest {
    @IsTest
    static void setItemsForPDF() {
        Service__c service = new Service__c(
                Name = 'Test',
                Processing_Fee__c = 1,
                Delivery_Fee__c = 1,
                SubTotal__c = 10,
                TotalTaxableAmount__c = 10,
                TotalPaid__c = 20
        );
        insert service;

        PageReference pageRef = Page.InvoicePDF;
        pageRef.getParameters().put('id', service.Id);
        Test.setCurrentPage(pageRef);

        new InvoicePDFController().setItemsForPDF();
    }
}