force-app/main/default/objects/Service__c/Service__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Client contact record attached to this request</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Services (Contact)</relationshipLabel>
    <relationshipName>Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <formula>CreatedDate + 60</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Pickup_type__c.field-meta.xml
<CustomField>
    <fullName>Pickup_type__c</fullName>
    <label>Pickup type (Delete)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Delivery</fullName>
            </value>
            <value>
                <fullName>Will Call</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service__c/fields/Scheduling_Contact__c.field-meta.xml
<CustomField>
    <fullName>Scheduling_Contact__c</fullName>
    <label>Scheduling Contact</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Client</fullName>
                <default>true</default>
                <label>Client</label>
            </value>
            <value>
                <fullName>Caseworker</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service__c/fields/Tag_Color__c.field-meta.xml
<CustomField>
    <fullName>Tag_Color__c</fullName>
    <label>Tag Color</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RequestRelatedListController.cls
public class RequestRelatedListController {
  
    public class RelatedListControllerWrapper {
        @AuraEnabled
        public Integer totalElements { get; set; }
        @AuraEnabled
        public List<Service__c> elements { get; set; }
    
            public RelatedListControllerWrapper(Integer totalElements, List<Service__c> elements) {
                this.totalElements = totalElements;
                this.elements = elements;
            }
        }

    @AuraEnabled
    public static RelatedListControllerWrapper getRequestCurrentPage(Id requestId,Integer pageNumber,Integer pageSize){
        Service__c currentRequest= [SELECT Id, Contact__c FROM Service__c WHERE Id=:requestId];

        if (currentRequest.Contact__c == null) {
            return new RelatedListControllerWrapper(0,new List<Service__c>() );
        }

        String queryTotal =
        'SELECT COUNT() FROM Service__c ' +
        'WHERE Contact__c = \'' +currentRequest.Contact__c + '\' AND Id != \''+requestId+'\' ';
        
        String query = 'SELECT Id, Name, Pickup_type__c, Scheduling_Contact__c, Expiration_Date__c,Tag_Color__c FROM Service__c' +
        '  WHERE contact__c =  \'' +currentRequest.Contact__c + '\' AND Id != \''+requestId+'\' ';

        Integer totalNumber = Database.countQuery(queryTotal);

        if (totalNumber ==0 ) return new RelatedListControllerWrapper(totalNumber,new List<Service__c>() );
        query += ' ORDER BY createdDate DESC  LIMIT :pageSize ';

        if (pageNumber > 0) {
            pageNumber *= pageSize;
            query += ' OFFSET : pageNumber ';
        }
        
        return new RelatedListControllerWrapper(totalNumber, Database.query(query));
    }
}