force-app/main/default/objects/Service__c/Service__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Stop__c.field-meta.xml
<CustomField>
    <fullName>Stop__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Stop</label>
    <referenceTo>Stop__c</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/SubType__c.field-meta.xml
<CustomField>
    <fullName>SubType__c</fullName>
    <label>Sub Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Will Call</fullName>
            </value>
            <value>
                <fullName>Delivery</fullName>
            </value>
            <value>
                <fullName>Hope Run</fullName>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>Hope Del.</fullName>
            </value>
            <value>
                <fullName>Donation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service__c/fields/Zip__c.field-meta.xml
<CustomField>
    <fullName>Zip__c</fullName>
    <label>Zip</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service__c/recordTypes/ClientRequest.recordType-meta.xml
<RecordType>
    <fullName>ClientRequest</fullName>
    <active>true</active>
    <label>Client Request</label>
</RecordType>

force-app/main/default/objects/Stop__c/Stop__c.object-meta.xml
<CustomObject>
    <label>Stop</label>
    <nameField>
        <label>Stop Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stops</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stop__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <formula>Service__r.Address__c + &apos; &apos; + Service__r.City__c  + &apos; &apos; + Service__r.State__c + &apos; &apos; + Service__r.Zip__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stop__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <formula>Service__r.City__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>City</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stop__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Stops</relationshipLabel>
    <relationshipName>Stops</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stop__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>Service__c</referenceTo>
    <relationshipLabel>Stops</relationshipLabel>
    <relationshipName>Stops</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stop__c/fields/StopOrder__c.field-meta.xml
<CustomField>
    <fullName>StopOrder__c</fullName>
    <label>Stop order</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/GoogleMapsAPIControllerTest.cls
/**
 * Created by Eric Solari on 04/01/2024.
 */
@IsTest
public with sharing class GoogleMapsAPIControllerTest {

    @IsTest
    public static void testBuildGetDirectionsURL(){
        Id recordTypeId = Schema.SObjectType.Service__c.getRecordTypeInfosByDeveloperName().get('ClientRequest').getRecordTypeId();
        Service__c service = new Service__c(Address__c = '3222 E D Street', City__c = 'Tacoma', State__c ='WA', Zip__c='98404', RecordTypeId = recordTypeId, SubType__c='Delivery');
        insert service;
        Stop__c stop = new Stop__c(Service__c = service.Id);
        insert stop;
        List<Stop__c> stops = [SELECT id, Address__c, Service__c, Service__r.RecordType.DeveloperName, StopOrder__c, Customer__r.Name, Service__r.SubType__c FROM Stop__c];

        Test.setMock(HttpCalloutMock.class, new MapApiCallMock());
        Test.startTest();
        GoogleMapsAPIController.buildGetDirectionsURL(stops , 'Tacoma');
        GoogleMapsAPIController.getIframeMapsUrl(null,stops, 'Tacoma', true );
        GoogleMapsAPIController.getMapDirections(stops , 'Tacoma');
        Test.stopTest();
    }

    @IsTest
    public static void testAPICall(){
        Id recordTypeId = Schema.SObjectType.Service__c.getRecordTypeInfosByDeveloperName().get('ClientRequest').getRecordTypeId();
        Service__c service = new Service__c(Address__c = '3222 E D Street', City__c = 'Tacoma', State__c ='WA', Zip__c='98404', RecordTypeId = recordTypeId, SubType__c='Delivery');
        insert service;
        Stop__c stop = new Stop__c(Service__c = service.Id);
        insert stop;
        List<Stop__c> stops = [SELECT id, Address__c, Service__c, Service__r.RecordType.DeveloperName, StopOrder__c, Customer__r.Name, Service__r.SubType__c FROM Stop__c];

        Test.setMock(HttpCalloutMock.class, new MapApiCallMock());
        Test.startTest();
        GoogleMapsIntegrationApi api = new GoogleMapsIntegrationApi();
        api.getRoute('Tacoma', stops);
        Test.stopTest();
    }
}