force-app/main/default/objects/GoogleMapsApiSetting__mdt/GoogleMapsApiSetting__mdt.object-meta.xml
<CustomObject>
    <label>Google Maps Api Setting</label>
    <pluralLabel>Google Maps Api Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/GoogleMapsApiSetting__mdt/fields/Url__c.field-meta.xml
<CustomField>
    <fullName>Url__c</fullName>
    <label>Url</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stop__c/Stop__c.object-meta.xml
<CustomObject>
    <label>Stop</label>
    <nameField>
        <label>Stop Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stops</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/GoogleMapsIntegrationApi.cls
public with sharing class GoogleMapsIntegrationApi {
    public Http http;
    public HttpRequest request;
    public HttpResponse response;

    private String apiKey;
    private String apiUrl;

    public GoogleMapsIntegrationApi() {
        this.setAPISettings();
        this.initHttp('GET');
    }

    private void setAPISettings() {
        GoogleMapsApiSetting__mdt mapsSettings = [
                SELECT Url__c, Key__c FROM GoogleMapsApiSetting__mdt LIMIT 1
        ];
        this.apiKey = mapsSettings.Key__c;
        this.apiUrl = mapsSettings.Url__c;
    }

    private void initHttp(String method) {
        this.http = new Http();
        this.request = new HttpRequest();
        this.request.setMethod(method);

    }

    public Map<String, Object> makeRequest(){
        this.response = this.http.send(this.request);

        if (this.response.getStatusCode() == 200) {
            Map<String, Object> data = (Map<String, Object>) JSON.deserializeUntyped(response.getBody());

            if(((List<Object>) data.get('routes')).size() > 0) {
                return (Map<String, Object>) ((List<Object>) data.get('routes'))[0];
            } else {
                return new Map<String, Object>();
            }
        }

        throw new GoogleMapsApiException('No successfully response from integration');
    }

    public Map<String, Object> getRoute(String origin, List<Stop__c> stops){
        String googleMapsUrl = GoogleMapsAPIController.buildGetDirectionsURL(stops, origin);
        this.request.setEndpoint(googleMapsUrl);
        return makeRequest();
    }
    
    public with sharing class GoogleMapsApiException extends Exception {
    }
}