force-app/main/default/objects/GoogleMapsApiSetting__mdt/GoogleMapsApiSetting__mdt.object-meta.xml
<CustomObject>
    <label>Google Maps Api Setting</label>
    <pluralLabel>Google Maps Api Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/GoogleMapsApiSetting__mdt/fields/Url__c.field-meta.xml
<CustomField>
    <fullName>Url__c</fullName>
    <label>Url</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service__c/Service__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Stop__c.field-meta.xml
<CustomField>
    <fullName>Stop__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Stop</label>
    <referenceTo>Stop__c</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/SubType__c.field-meta.xml
<CustomField>
    <fullName>SubType__c</fullName>
    <label>Sub Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Will Call</fullName>
            </value>
            <value>
                <fullName>Delivery</fullName>
            </value>
            <value>
                <fullName>Hope Run</fullName>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>Hope Del.</fullName>
            </value>
            <value>
                <fullName>Donation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service__c/recordTypes/ClientRequest.recordType-meta.xml
<RecordType>
    <fullName>ClientRequest</fullName>
    <active>true</active>
    <label>Client Request</label>
</RecordType>

force-app/main/default/objects/Service__c/recordTypes/DonationPickup.recordType-meta.xml
<RecordType>
    <fullName>DonationPickup</fullName>
    <active>true</active>
    <label>Donation Pickup</label>
</RecordType>

force-app/main/default/objects/Service__c/recordTypes/GeneralDelivery.recordType-meta.xml
<RecordType>
    <fullName>GeneralDelivery</fullName>
    <active>true</active>
    <label>General Delivery</label>
</RecordType>

force-app/main/default/objects/Service__c/recordTypes/GeneralPickup.recordType-meta.xml
<RecordType>
    <fullName>GeneralPickup</fullName>
    <active>true</active>
    <label>General Pickup</label>
</RecordType>

force-app/main/default/objects/Stop__c/Stop__c.object-meta.xml
<CustomObject>
    <label>Stop</label>
    <nameField>
        <label>Stop Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stops</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stop__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <formula>Service__r.Address__c + &apos; &apos; + Service__r.City__c  + &apos; &apos; + Service__r.State__c + &apos; &apos; + Service__r.Zip__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stop__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Stops</relationshipLabel>
    <relationshipName>Stops</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stop__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>Service__c</referenceTo>
    <relationshipLabel>Stops</relationshipLabel>
    <relationshipName>Stops</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stop__c/fields/StopOrder__c.field-meta.xml
<CustomField>
    <fullName>StopOrder__c</fullName>
    <label>Stop order</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/GoogleMapsAPIController.cls
/**
 * Created by Gustavo on 10/11/23.
 */

public with sharing class GoogleMapsAPIController {
    @AuraEnabled
    public static String buildGetDirectionsURL(List<Stop__c> stops, String destination) {
        GoogleMapsApiSetting__mdt mapsSettings = [
                SELECT
                        Url__c,
                        Key__c
                FROM GoogleMapsApiSetting__mdt
                LIMIT 1
        ];

        String stopsAddress = '';

        for (Stop__c stop : stops){
            stopsAddress += String.isNotBlank(stop.Address__c) ? '|' + stop.Address__c : '';
        }

        String encodedStopsAddress = EncodingUtil.urlEncode(stopsAddress, 'UTF-8');
        String googleMapsKey = mapsSettings.Key__c;
        String googleMapsBaseUrl = mapsSettings.Url__c;

        return (
                googleMapsBaseUrl +
                '/json?origin=' +
                EncodingUtil.urlEncode(destination,'UTF-8') +
                '&destination=' +
                EncodingUtil.urlEncode(destination,'UTF-8') +
                '&waypoints=optimize:true' +
                encodedStopsAddress +
                '&key=' +
                googleMapsKey
        );
    }

    @AuraEnabled
    public static String getMapDirections(List<Stop__c> stops, String destination) {
        String directionsUrl = buildGetDirectionsURL(stops, destination);
        return MapsAPICallout.callMapDirections(directionsUrl);
    }

    @AuraEnabled
    public static String getIframeMapsUrl(String originUrl, List<Stop__c> stops, String destination, Boolean optimize) {
        String stopsAddress = '';
        Long timestamp = Datetime.now().getTime();

        if (stops == null || stops.isEmpty()) {
            return null;
        }

        for (Stop__c stop : stops) {
            if (stop.Service__c == null) continue;

            String serviceRecordType = stop.Service__r.RecordType.DeveloperName;
            String serviceSubType = stop.Service__r.SubType__c;
            String stopColor = '';

            if (serviceRecordType == 'ClientRequest') {
                stopColor = 'red';
            } else if (serviceRecordType == 'DonationPickup' || serviceRecordType == 'GeneralPickup') {
                stopColor = 'blue';
            } else if (serviceRecordType == 'GeneralDelivery' && serviceSubType == 'Hope Del.') {
                stopColor = 'purple';
            } else if (serviceRecordType == 'GeneralDelivery' && serviceSubType != 'Hope Del.') {
                stopColor = 'orange';
            }

            String pointerTitle = 'Stop: ' + stop.StopOrder__c + ' Name: ' + stop.Customer__r.Name;
            stopsAddress += String.isNotBlank(stop.Address__c)
                    ? '|' + stop.Address__c + '/' + stopColor + '/' + pointerTitle
                    : '';
        }

        String encodedStopsAddress = EncodingUtil.urlEncode(stopsAddress, 'UTF-8');

        return (
                originUrl +
                '/apex/googleMapsApi?t=' +
                timestamp +
                '&startpoint=' +
                EncodingUtil.urlEncode(destination, 'UTF-8') +
                '&endpoint=' +
                EncodingUtil.urlEncode(destination, 'UTF-8') +
                '&waypoints=' +
                encodedStopsAddress +
                '&optimize=' +
                optimize
        );
    }
}