force-app/main/default/objects/AP_Contact__c/AP_Contact__c.object-meta.xml
<CustomObject>
    <label>AP Contact</label>
    <nameField>
        <label>AP Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AP Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AP_Contact__c/fields/Case_Worker__c.field-meta.xml
<CustomField>
    <fullName>Case_Worker__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case Worker</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>AP Contacts (Case Worker)</relationshipLabel>
    <relationshipName>CaseWorker</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Appointment__c/Appointment__c.object-meta.xml
<CustomObject>
    <label>Appointment</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Appointment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Appointment__c/fields/CaseworkerEmail__c.field-meta.xml
<CustomField>
    <fullName>CaseworkerEmail__c</fullName>
    <label>Caseworker Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/LocationAddress__c.field-meta.xml
<CustomField>
    <fullName>LocationAddress__c</fullName>
    <formula>Service__r.Location__r.Address__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Location Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>Service__c</referenceTo>
    <relationshipLabel>Appointments</relationshipLabel>
    <relationshipName>Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/ServiceType__c.field-meta.xml
<CustomField>
    <fullName>ServiceType__c</fullName>
    <formula>TEXT(Service__r.SubType__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
                <default>true</default>
                <label>Scheduled</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>No Show</fullName>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Time__c.field-meta.xml
<CustomField>
    <fullName>Time__c</fullName>
    <label>Time</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>AvailableTimeSlot</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location (NWFB)</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations (NWFB)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service__c/Service__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service__c/fields/Caseworker__c.field-meta.xml
<CustomField>
    <fullName>Caseworker__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Must be a contact of the agency that you selected.</inlineHelpText>
    <label>Caseworker</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Case Manager</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Client Request</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Services (Caseworker)</relationshipLabel>
    <relationshipName>Requests1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Client contact record attached to this request</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Services (Contact)</relationshipLabel>
    <relationshipName>Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/CurrentAppointment__c.field-meta.xml
<CustomField>
    <fullName>CurrentAppointment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Current Appointment</label>
    <referenceTo>Appointment__c</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/LastAppointmentDate__c.field-meta.xml
<CustomField>
    <fullName>LastAppointmentDate__c</fullName>
    <label>Last Appointment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>Request</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Processing</fullName>
                <default>true</default>
                <label>Processing</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Routing</fullName>
            </value>
            <value>
                <fullName>Shopping</fullName>
            </value>
            <value>
                <fullName>Delivery</fullName>
            </value>
            <value>
                <fullName>Pick Up</fullName>
            </value>
            <value>
                <fullName>Review</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
                <isActive>false</isActive>
                <label>Active</label>
            </value>
            <value>
                <fullName>Complete</fullName>
                <isActive>false</isActive>
                <label>Complete</label>
            </value>
            <value>
                <fullName>Draft</fullName>
                <isActive>false</isActive>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Expiring</fullName>
                <isActive>false</isActive>
                <label>Expiring</label>
            </value>
            <value>
                <fullName>Items Owed</fullName>
                <isActive>false</isActive>
                <label>Items Owed</label>
            </value>
            <value>
                <fullName>No Call / No Show</fullName>
                <isActive>false</isActive>
                <label>No Call / No Show</label>
            </value>
            <value>
                <fullName>Re-Delivery</fullName>
                <isActive>false</isActive>
                <label>Re-Delivery</label>
            </value>
            <value>
                <fullName>Served</fullName>
                <isActive>false</isActive>
                <label>Served</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service__c/recordTypes/ClientRequest.recordType-meta.xml
<RecordType>
    <fullName>ClientRequest</fullName>
    <active>true</active>
    <label>Client Request</label>
</RecordType>

force-app/main/default/classes/Appointment.cls
public without sharing class Appointment extends GenericDao {

    @TestVisible
    private static Appointment mock;
    private static final String STATUS_SCHEDULED = 'Scheduled';
    private static final String STATUS_CANCELLED = 'Cancelled';
    private static final String STATUS_DELIVERY = 'Delivery';
    private static final String STATUS_COMPLETED = 'Completed';
    private static final String STATUS_EXPIRED = 'Expired';

    public Appointment() {
    }

    private Appointment(List<SObject> requests, Map<Id, SObject> oldRequestsById) {
        super(requests, oldRequestsById);
    }

    private Appointment(List<SObject> requests) {
        super(requests);
    }

    public static Appointment getInstance() {
        if (Test.isRunningTest() && mock != null) {
            return mock;
        } else {
            return new Appointment(new List<Task>());
        }
    }

    public override void afterInsert() {
        sendSMSToServiceContact();
//        sendConfirmationBasedOnStatus();
        updateServiceStatusAndAppointment();
        rollup();
    }

    public override void afterUpdate() {
//        sendConfirmationBasedOnStatus();
        rollup(); 
    }

    public override void beforeUpdate() {
        updateCaseworkerEmailField();
    }

    public override void beforeInsert() {
        updateCaseworkerEmailField();
    }

    public override void afterDelete() {
        rollup();
    }

    private void rollup() {
        try {
            if (this.records != null && !this.records.isEmpty()) {
                Database.update(dlrs.RollupService.rollup(this.records), false);
            }
        } catch (Exception e) {
            System.debug(e.getMessage());
        }

    }

    public void updateServiceStatusAndAppointment() {
        Map<Id, Id> mapAppointmentServices = new Map<Id, Id>();
        Map<Id, Appointment__c> serviceIdToAppointmentMap = new Map<Id, Appointment__c>();

        for (Appointment__c appointment : (List<Appointment__c>) this.records) {
            mapAppointmentServices.put(appointment.Service__c, appointment.Id);
            serviceIdToAppointmentMap.put(appointment.Service__c, appointment);
        }

        Map<Id, Appointment__c> appointmentsByServiceId = AppointmentSelector.newInstance().getOldestScheduledAppointmentByServiceId(mapAppointmentServices);

        List<Service__c> servicesToUpdate = ServiceSelector.getInstance().getServiceByIds(mapAppointmentServices.keySet());
        List<Appointment__c> appointmentsToCancel = new List<Appointment__c>();

        for (Service__c service : servicesToUpdate) {

            if (service?.RecordType?.DeveloperName == null) continue;
            if (service.RecordType.DeveloperName != 'ClientRequest') continue;

            if (!appointmentsByServiceId.isEmpty()) {
                service.CurrentAppointment__c = appointmentsByServiceId?.get(service.Id).Id;

                appointmentsToCancel.add(
                        new Appointment__c(
                                Id = service.CurrentAppointment__c,
                                Status__c = 'Cancelled'
                        )
                );
            } else {
                service.CurrentAppointment__c = mapAppointmentServices?.get(service.Id);
            }

            if (service.Status__c != STATUS_DELIVERY && service.Status__c != STATUS_CANCELLED && service.Status__c != STATUS_COMPLETED && service.Status__c != STATUS_EXPIRED){
                service.Status__c = STATUS_SCHEDULED;
            }
            service.LastAppointmentDate__c = serviceIdToAppointmentMap?.get(service.Id).Date__c;
        }
        TriggerManagement.disableTrigger('AppointmentTrigger');
        TriggerManagement.disableTrigger('ServiceTrigger');
        update appointmentsToCancel;
        update servicesToUpdate;
        TriggerManagement.enableTrigger('AppointmentTrigger');
        TriggerManagement.enableTrigger('ServiceTrigger');
    }

//    public void sendConfirmationBasedOnStatus() {
//        Set<Id> serviceIds = new Set<Id>();
//
//        for (Appointment__c  appointment : (List<Appointment__c>) this.records) {
//            serviceIds.add(appointment.Service__c);
//        }
//
//        List<String> emailTemplateNames = new List<String>{
//                'RequestNotFoundEmailTemplate',
//                'ClientMissedTheirAppointmentTemplate',
//                'ClientShoppingAppointmentScheduled',
//                'CaseWorkerAppointmentScheduledEmail'
//        };
//
//        Map<String, EmailTemplate> emailTemplatesByNameMap = EmailTemplateSelector.getInstance().getEmailTemplatesByDeveloperNames(emailTemplateNames);
//        Map<String, OrgWideEmailAddress> addressToOrgWideEmail = OrgWideEmailAddressSelector.getInstance().getOrgWideEmailAddressByEmailAddress(
//                'clientservices@nwfurniturebank.org'
//        );
//
//        Map<Id, Service__c> serviceMap = new Map<Id, Service__c>(
//                ServiceSelector.getInstance().getServiceByIdsAndItemsByCategory(serviceIds)
//        );
//
//        List<Messaging.SingleEmailMessage> emailsToSend = new List<Messaging.SingleEmailMessage>();
//        List<Task> tasksToCreate = new List<Task>();
//
//        if (addressToOrgWideEmail == null) return;
//        Id orgWideEmailId = addressToOrgWideEmail.get('clientservices@nwfurniturebank.org').Id;
//
//        for (Appointment__c appointment : (List<Appointment__c>) this.records) {
//            Service__c service = serviceMap.get(appointment.Service__c);
//            String contactPreferredEmail;
//
//            if (service != null) {
//                if (service.Contact__r.npe01__Preferred_Email__c == null || service.Contact__r.npe01__Preferred_Email__c == 'Personal') {
//                    contactPreferredEmail = service.Contact__r.npe01__HomeEmail__c;
//                } else if (service.Contact__r.npe01__Preferred_Email__c == 'Work') {
//                    contactPreferredEmail = service.Contact__r.npe01__WorkEmail__c;
//                } else {
//                    contactPreferredEmail = service.Contact__r.npe01__AlternateEmail__c;
//                }
//
//                if (contactPreferredEmail == '') {
//                    appointment.addError('No preferred email on contact');
//                    continue;
//                }
//            }
//
//            try {
//                Boolean isOneDayBefore = Date.today().daysBetween(appointment.Date__c) == 1 && appointment.Date__c < Date.today();
//
//                if (isOneDayBefore) tasksToCreate.add(createEmailTask(appointment, service, null));
//
//                if (appointment.Status__c == 'Scheduled') {
//                    if (service == null) {
//                        emailsToSend.add(
//                                createEmail(
//                                        emailTemplatesByNameMap.get('RequestNotFoundEmailTemplate'),
//                                        appointment.OwnerId,
//                                        appointment.Owner.Email,
//                                        orgWideEmailId,
//                                        appointment.Id
//                                )
//                        );
//                        tasksToCreate.add(createEmailTask(appointment, service, null));
//                        continue;
//                    }
//
//                    emailsToSend.add(
//                            createEmail(
//                                    emailTemplatesByNameMap.get('ClientShoppingAppointmentScheduled'),
//                                    service.Contact__c,
//                                    contactPreferredEmail,
//                                    orgWideEmailId,
//                                    appointment.Id
//                            )
//                    );
//
//                    tasksToCreate.add(createEmailTask(appointment, service, null));
//
//                    emailsToSend.add(
//                            createEmail(
//                                    emailTemplatesByNameMap.get('CaseWorkerAppointmentScheduledEmail'),
//                                    service.Caseworker__c,
//                                    appointment.CaseworkerEmail__c,
//                                    orgWideEmailId,
//                                    appointment.Id
//                            )
//                    );
//
//                    continue;
//                }
//
//                if (appointment.Status__c == 'No Show') {
//                    tasksToCreate.add(createEmailTask(appointment, service, null));
//
//                    emailsToSend.add(
//                            createEmail(
//                                    emailTemplatesByNameMap.get('ClientMissedTheirAppointmentTemplate'),
//                                    service.Contact__c,
//                                    contactPreferredEmail,
//                                    orgWideEmailId,
//                                    appointment.Id
//                            )
//                    );
//
//                    continue;
//                }
//            } catch (Exception e) {
//                System.debug(e.getMessage());
//            }
//
//        }
//
//        sendEmails(emailsToSend, tasksToCreate);
//        Database.insert(tasksToCreate, false);
//    }

    private static Messaging.SingleEmailMessage createEmail(EmailTemplate emailTemplatesByNameMap, Id targetId, String email, Id orgWideEmailAddressId, String whatId) {
        List<String> toEmailAddressList = new List<String>{email};

        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();

        mail.setTemplateId(emailTemplatesByNameMap.Id);
        mail.setToAddresses(toEmailAddressList);
        mail.setTargetObjectId(targetId);
        mail.setWhatId(whatId);
        mail.setSaveAsActivity(false);

        if (orgWideEmailAddressId == null) mail.setOrgWideEmailAddressId(orgWideEmailAddressId);

        return mail;
    }

    private static void sendEmails(List<Messaging.SingleEmailMessage> emailsToSend, List<Task> tasksToCreate) {
        List<Messaging.SendEmailResult> results = Messaging.sendEmail(emailsToSend);
        registerMessaging(results, tasksToCreate);

    }

    private static void registerMessaging(List<Messaging.SendEmailResult> results, List<Task> tasksToCreate) {
        for (Messaging.SendEmailResult result : results) {

            if (result.getErrors().isEmpty()) continue;

            for (Messaging.SendEmailError error : result.getErrors()) {
                tasksToCreate.add(createEmailTask(null, null, error));
            }
        }
    }

    public static Task createEmailTask(Appointment__c appointment, Service__c service, Messaging.SendEmailError error) {
        String description = error != null
                ? 'The email related to the ' + service.Contact__r.Name + ' bounced. Error: ' + error.getMessage()
                : 'A Confirmation Email has been sent.';

        Task task = new Task(
                Priority = 'Normal',
                Subject = error == null ? appointment.ServiceType__c : 'Error sending email confirmation',
                ActivityDate = Date.today(),
                Status = 'Completed',
                RecordTypeId = Schema.SObjectType.Task.getRecordTypeInfosByName().get('Sent Email').getRecordTypeId(),
                TaskSubtype = 'Email',
                Type = 'Email',
                WhatId = service.Id,
                WhoId = service.Contact__c,
                OwnerId = service.OwnerId,
                Description = description
        );

        return task;
    }

    private void sendSMSToServiceContact() {
        Set<Id> serviceIds = new Set<Id>();

        for (Appointment__c app : (List<Appointment__c>) records) {
            if (app.Status__c != STATUS_SCHEDULED) continue;
            serviceIds.add(app.Service__c);
        }

        Map<Id, SObject> serviceById = Utils.listToMap('Id', new ServiceSelector().getServiceByIds(serviceIds));
        List<Task> pendingTasks = new List<Task>();

        for (Appointment__c app : (List<Appointment__c>) records) {
            if (app.Status__c != STATUS_SCHEDULED) continue;

            Service__c service = (Service__c) serviceById.get(app.Service__c);
            String appointmentDateString = app.Date__c.month() + '/' + app.Date__c.day() + '/' + app.Date__c.year();

            if (service == null) continue;

            String smsMessage = 'Your shopping appointment is scheduled for ' + appointmentDateString + ' ' + app.Time__c + ' at NW Furniture Bank.' +
            'We are located at ' + app.LocationAddress__c +
            ' ' +
            'Tacoma: Enter through the orange door for check-in \n' +
            'Vancouver: Enter through the door with the orange sign for check-in\n' +
            ' ' +
            'Please bring photo ID for check in.\n' +
            'If you are bringing your own transportation for your items, bring enough vehicle space to take everything home in 1 trip.\n' +
            'Please have your vehicle(s) present at the start of your appointment.';


//            String smsMessage = 'Your shopping appointment is scheduled for '
//                    + appointmentDateString
//                    + ' '
//                    + app.Time__c + ' at NW Furniture Bank.\n' +
//                    'We are located at ' + app.LocationAddress__c + '\n' +
//                    'When you arrive, please come around the back of building and enter through the orange door for check-in.';
//

            pendingTasks.add(
                    new Task(
                            Subject = 'Appointment ' + app.Name + ' Scheduled',
                            WhatId = app.Service__c,
                            WhoId = service.Contact__c,
                            Priority = 'Normal',
                            Status = 'Completed',
                            ActivityDate = Date.today(),
                            Description = smsMessage
                    )
            );

            System.enqueueJob(
                    new SendSMSQueueable(
                            service.Location__r.City__c,
                            service.Contact__r.MobilePhone,
                            smsMessage
                    )
            );
        }

        if (pendingTasks == null || pendingTasks.isEmpty()) return;

        TriggerManagement.disableTrigger('TaskTrigger');
        insert pendingTasks;
    }

    private void updateCaseworkerEmailField() {
        Set<Id> serviceIds = new Set<Id>();

        for (Appointment__c app : (List<Appointment__c>) records) {
            if (app.Service__c == null) continue;
            serviceIds.add(app.Service__c);
        }

        Map<Id, SObject> serviceById = Utils.listToMap(
                'Id',
                new ServiceSelector().getServiceByIds(serviceIds)
        );

        for (Appointment__c app : (List<Appointment__c>) records) {
            if (app.Service__c == null) continue;

            Service__c currentService = (Service__c) serviceById.get(app.Service__c);

            if (currentService.Caseworker__c == null) continue;

            app.CaseworkerEmail__c = currentService.Caseworker__r.Email;
        }
    }

    public class Factory implements TriggerHandlerFactory {
        public TriggerHandler create(List<SObject> objects, Map<Id, SObject> oldObjectsById) {
            return new Appointment(objects, oldObjectsById);
        }
    }
}