force-app/main/default/objects/AP_Contact__c/AP_Contact__c.object-meta.xml
<CustomObject>
    <label>AP Contact</label>
    <nameField>
        <label>AP Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AP Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AP_Contact__c/fields/Case_Worker__c.field-meta.xml
<CustomField>
    <fullName>Case_Worker__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case Worker</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>AP Contacts (Case Worker)</relationshipLabel>
    <relationshipName>CaseWorker</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/CardLast4Digits__c.field-meta.xml
<CustomField>
    <fullName>CardLast4Digits__c</fullName>
    <label>Card Last 4 Digits</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Payee_Type__c.field-meta.xml
<CustomField>
    <fullName>Payee_Type__c</fullName>
    <label>Payee Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Agency</fullName>
            </value>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment__c/fields/PaymentAmount__c.field-meta.xml
<CustomField>
    <fullName>PaymentAmount__c</fullName>
    <label>Payment Amount</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/PaymentMethod__c.field-meta.xml
<CustomField>
    <fullName>PaymentMethod__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cash</fullName>
                <color>#006600</color>
                <label>Cash</label>
            </value>
            <value>
                <fullName>CreditCard</fullName>
                <color>#996633</color>
                <label>Credit Card</label>
            </value>
            <value>
                <fullName>DebitCard</fullName>
                <color>#EFAE73</color>
                <label>Debit Card</label>
            </value>
            <value>
                <fullName>Wire</fullName>
                <color>#663366</color>
                <label>Wire</label>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
            <value>
                <fullName>Card</fullName>
            </value>
            <value>
                <fullName>Check</fullName>
                <color>#AFCADF</color>
                <label>Check</label>
            </value>
            <value>
                <fullName>Bulletin de Versement</fullName>
                <isActive>false</isActive>
                <label>Bulletin de Versement</label>
            </value>
            <value>
                <fullName>Credit Card Old</fullName>
                <isActive>false</isActive>
                <label>Credit Card Old</label>
            </value>
            <value>
                <fullName>ECheck</fullName>
                <isActive>false</isActive>
                <label>E-Check</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>Service__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service__c/Service__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service__c/fields/Agency__c.field-meta.xml
<CustomField>
    <fullName>Agency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agency</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Agency</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/BalanceDue__c.field-meta.xml
<CustomField>
    <fullName>BalanceDue__c</fullName>
    <formula>TotalAmount__c-TotalPaid__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Balance Due</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Caseworker__c.field-meta.xml
<CustomField>
    <fullName>Caseworker__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Must be a contact of the agency that you selected.</inlineHelpText>
    <label>Caseworker</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Case Manager</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Client Request</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Services (Caseworker)</relationshipLabel>
    <relationshipName>Requests1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/CaseworkerName__c.field-meta.xml
<CustomField>
    <fullName>CaseworkerName__c</fullName>
    <formula>Caseworker__r.Full_Contact_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Caseworker Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Client contact record attached to this request</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Services (Contact)</relationshipLabel>
    <relationshipName>Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Due_Date_Invoice_1__c.field-meta.xml
<CustomField>
    <fullName>Due_Date_Invoice_1__c</fullName>
    <formula>CreatedDate  + 30</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Due_Date_Invoice_-1</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Invoice_Number__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Number__c</fullName>
    <displayFormat>INV-{0000}</displayFormat>
    <label>Invoice Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/InvoiceDue__c.field-meta.xml
<CustomField>
    <fullName>InvoiceDue__c</fullName>
    <formula>IF( RecordTypeName__c = &apos;ClientRequest&apos;, LastAppointmentDate__c + 30, DATEVALUE(CreatedDate))</formula>
    <inlineHelpText>30 days from last appointment date</inlineHelpText>
    <label>Invoice Due</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/InvoiceNumberVersion__c.field-meta.xml
<CustomField>
    <fullName>InvoiceNumberVersion__c</fullName>
    <formula>Invoice_Number__c + &apos;-&apos; + TEXT(InvoiceVersion__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Invoice Number Version</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/InvoiceVersion__c.field-meta.xml
<CustomField>
    <fullName>InvoiceVersion__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Invoice Version</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/LastAppointmentDate__c.field-meta.xml
<CustomField>
    <fullName>LastAppointmentDate__c</fullName>
    <label>Last Appointment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Processing_Fee__c.field-meta.xml
<CustomField>
    <fullName>Processing_Fee__c</fullName>
    <label>Processing Fee</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/ProcessingFeeBalanceDue__c.field-meta.xml
<CustomField>
    <fullName>ProcessingFeeBalanceDue__c</fullName>
    <formula>(TotalTaxableAmount__c + Processing_Fee__c) - TotalPaid__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Processing Fee Balance Due</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/SubTotal__c.field-meta.xml
<CustomField>
    <fullName>SubTotal__c</fullName>
    <label>Sub Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/TotalAmount__c.field-meta.xml
<CustomField>
    <fullName>TotalAmount__c</fullName>
    <formula>SubTotal__c +  Delivery_Fee__c +  Processing_Fee__c +  Pickup_Fee__c + TotalTaxableAmount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/TotalPaid__c.field-meta.xml
<CustomField>
    <fullName>TotalPaid__c</fullName>
    <label>Total Paid</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/TotalTaxableAmount__c.field-meta.xml
<CustomField>
    <fullName>TotalTaxableAmount__c</fullName>
    <label>Tax</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ServiceItem__c/ServiceItem__c.object-meta.xml
<CustomObject>
    <label>Service Item</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Service Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ServiceItem__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <label>Service</label>
    <referenceTo>Service__c</referenceTo>
    <relationshipLabel>Service Items</relationshipLabel>
    <relationshipName>ServiceItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ServiceItem__c/fields/TotalItemPrice__c.field-meta.xml
<CustomField>
    <fullName>TotalItemPrice__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Item Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/InvoicePDFController.cls
public without sharing class InvoicePDFController {

    public List<ServiceItem__c> items { get; set; }
    public List<ServiceFee> feeItems { get; set; }
    public List<Payment__c> payments { get; set; }
    public Date today {get; set;}
    public Service__c service { get; set; }
    public Decimal serviceBalanceDue { get; set; }
    //public Map<String, Decimal> totals { get; set; }

    public class ServiceFee {
        public String name { get; set; }
        public Integer quantity { get; set; }
        public Decimal totalItemPrice { get; set; }
        public Decimal totalFee { get; set; }
    }

    public InvoicePDFController() {
        setItemsForPDF();
    }

    public void setItemsForPDF() {
        String serviceId = ApexPages.currentPage().getParameters().get('id');
        today = Date.today();

        // get service details and format
        service = [
                SELECT
                        Id,
                        Name,
                        CreatedDate,
                        InvoiceDue__c,
                        Invoice_Number__c,
                        Processing_Fee__c,
                        Delivery_Fee__c,
                        SubTotal__c,
                        TotalTaxableAmount__c,
                        TotalPaid__c,
                        BalanceDue__c,
                        TotalAmount__c,
                        Contact__r.Name,
                        Contact__r.MobilePhone,
                        CaseworkerName__c,
                        LastAppointmentDate__c,
                        Caseworker__r.Email,
                        InvoiceVersion__c,
                        InvoiceNumberVersion__c,
                        Agency__r.Name,
                        Agency__r.BillingStreet,
                        Agency__r.BillingCity, Agency__r.BillingState,
                        Agency__r.BillingPostalCode,
                        ProcessingFeeBalanceDue__c,
                        Due_Date_Invoice_1__c
                FROM Service__c
                WHERE Id = :serviceId
        ];

        if (service.TotalTaxableAmount__c == null) service.TotalTaxableAmount__c = 0;
        if (service.TotalPaid__c == null) service.TotalPaid__c = 0;

        // set fees
        feeItems = new List<ServiceFee>();
        if (service.Delivery_Fee__c > 0 && service.InvoiceVersion__c != 1) {
            ServiceFee si = new ServiceFee();
            si.name = 'Delivery Fee';
            si.quantity = 1; 
            si.totalItemPrice = service.Delivery_Fee__c;
            si.totalFee = service.Delivery_Fee__c;
            feeItems.add(si);
        }

        if (service.Processing_Fee__c > 0) {
            ServiceFee si = new ServiceFee();
            si.name = 'Processing Fee';
            si.quantity = 1;
            si.totalItemPrice = service.Processing_Fee__c;
            si.totalFee = service.Processing_Fee__c;
            feeItems.add(si);
            serviceBalanceDue = service.Processing_Fee__c - service.TotalPaid__c;
        }

        // get items and format
        List<ServiceItem__c> serviceItems = new ServiceItemSelector().getServiceItemsByServiceId(serviceId);
        items = new List<ServiceItem__c>();
        if (service.InvoiceVersion__c != 1) {
            for (ServiceItem__c item : serviceItems) {
                if (item.Quantity__c > 0 && item.TotalItemPrice__c != null && item.TotalItemPrice__c > 0){
                    items.add(item);
                }
            }
        }


        // get payments
        payments = new List<Payment__c>();
        payments = [
                SELECT
                        Id,
                        Name,
                        PaymentMethod__c,
                        PaymentAmount__c,
                        Payee_Type__c,
                        CardLast4Digits__c,
                        CreatedDate
                FROM Payment__c
                WHERE Service__c = :serviceId
        ];

    }
}