force-app/main/default/objects/AP_Contact__c/AP_Contact__c.object-meta.xml
<CustomObject>
    <label>AP Contact</label>
    <nameField>
        <label>AP Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AP Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AP_Contact__c/fields/Case_Worker__c.field-meta.xml
<CustomField>
    <fullName>Case_Worker__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case Worker</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>AP Contacts (Case Worker)</relationshipLabel>
    <relationshipName>CaseWorker</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/Payee_Type__c.field-meta.xml
<CustomField>
    <fullName>Payee_Type__c</fullName>
    <label>Payee Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Agency</fullName>
            </value>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment__c/fields/PaymentType__c.field-meta.xml
<CustomField>
    <fullName>PaymentType__c</fullName>
    <label>Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Payment</fullName>
                <default>true</default>
                <label>Payment</label>
            </value>
            <value>
                <fullName>Refund</fullName>
            </value>
            <value>
                <fullName>ActivationFee</fullName>
                <isActive>false</isActive>
                <label>Activation Fee</label>
            </value>
            <value>
                <fullName>Application Fee</fullName>
                <isActive>false</isActive>
                <label>Application Fee</label>
            </value>
            <value>
                <fullName>Application Fee Refund</fullName>
                <isActive>false</isActive>
                <label>Application Fee Refund</label>
            </value>
            <value>
                <fullName>EventFees</fullName>
                <isActive>false</isActive>
                <label>Event Fees</label>
            </value>
            <value>
                <fullName>KokuaCrewAppFee</fullName>
                <isActive>false</isActive>
                <label>Kokua Crew App Fee</label>
            </value>
            <value>
                <fullName>Kokua Crew Fees</fullName>
                <isActive>false</isActive>
                <label>Kokua Crew Fees</label>
            </value>
            <value>
                <fullName>MealCredit</fullName>
                <isActive>false</isActive>
                <label>Meal Credit</label>
            </value>
            <value>
                <fullName>Overpayment</fullName>
                <isActive>false</isActive>
                <label>Overpayment</label>
            </value>
            <value>
                <fullName>School Fees</fullName>
                <isActive>false</isActive>
                <label>School Fees</label>
            </value>
            <value>
                <fullName>StaffAppFee</fullName>
                <isActive>false</isActive>
                <label>Staff App Fee</label>
            </value>
            <value>
                <fullName>StaffFees</fullName>
                <isActive>false</isActive>
                <label>Staff Fees</label>
            </value>
            <value>
                <fullName>StaffPayment</fullName>
                <isActive>false</isActive>
                <label>Staff Payment</label>
            </value>
            <value>
                <fullName>StudentAppFee</fullName>
                <isActive>false</isActive>
                <label>Student App Fee</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>Service__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service__c/Service__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service__c/fields/Caseworker__c.field-meta.xml
<CustomField>
    <fullName>Caseworker__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Must be a contact of the agency that you selected.</inlineHelpText>
    <label>Caseworker</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Case Manager</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Client Request</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Services (Caseworker)</relationshipLabel>
    <relationshipName>Requests1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Client contact record attached to this request</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Services (Contact)</relationshipLabel>
    <relationshipName>Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/InvoiceNumberVersion__c.field-meta.xml
<CustomField>
    <fullName>InvoiceNumberVersion__c</fullName>
    <formula>Invoice_Number__c + &apos;-&apos; + TEXT(InvoiceVersion__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Invoice Number Version</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/InvoiceVersion__c.field-meta.xml
<CustomField>
    <fullName>InvoiceVersion__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Invoice Version</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/PaymentReceiptEmailSender.cls
/**
 * Created by Gustavo on 03/06/24.
 */

public with sharing class PaymentReceiptEmailSender {

    @Future(Callout=true)
    public static void send(Set<Id> paymentIds) {
        List<Payment__c> payments = new PaymentSelector().byIds(paymentIds);

        Set<Id> serviceIds = new Set<Id>();

        for (Payment__c payment : (List<Payment__c>) payments) {
            if (payment.Service__c == null) continue;
            serviceIds.add(payment.Service__c);
        }

        if (serviceIds == null || serviceIds.isEmpty()) return;

        Map<Id, SObject> serviceById = Utils.listToMap(
                'Id',
                new ServiceSelector().getServiceByIds(serviceIds)
        );

        EmailTemplate paymentReceivedEmailTemplate = new EmailTemplateSelector().getEmailTemplateByDeveloperName(
                'PaymentCompleted'
        );

        OrgWideEmailAddress infoOrgWideAddress = new OrgWideEmailAddressSelector().getOrgWideEmailAddress(
                'info@nwfurniturebank.org'
        );

        List<Service__c> services = new List<Service__c>();

        EmailCooker emailCooker = new EmailCooker();

        for (Payment__c payment : (List<Payment__c>) payments) {
            Service__c currentService = (Service__c) serviceById.get(payment.Service__c);
            if (currentService == null) continue;
            if (payment.PaymentType__c == 'Refund') continue;
            Messaging.EmailFileAttachment mailAttachment = null;

            if (!Test.isRunningTest())  {
                PageReference PDF = Page.InvoicePDF;
                PDF.getParameters().put('Id', currentService.Id);
                PDF.setRedirect(true);
                Blob b = PDF.getContent();

                Utils.createContentVersion(
                        'Invoice:' + currentService.InvoiceNumberVersion__c + '.pdf',
                        b,
                        currentService.Id
                );
                mailAttachment = new Messaging.EmailFileAttachment();
                mailAttachment.setBody(b);
                mailAttachment.setContentType('application/pdf');
                mailAttachment.setFileName('Invoice: ' + currentService.InvoiceNumberVersion__c + '.pdf');
                mailAttachment.setInline(false);
            }

            Contact contact = payment.Payee_Type__c == 'Client' ? currentService.Contact__r : currentService.Caseworker__r;
            if (contact == null || contact.Email == null) continue;

            emailCooker.addEmail(
                    infoOrgWideAddress.Id,
                    contact.Email,
                    paymentReceivedEmailTemplate.Id,
                    contact.Id,
                    payment.Id,
                    mailAttachment != null
                            ? new List<Messaging.EmailFileAttachment>{mailAttachment}
                            : null
            );
            currentService.InvoiceVersion__c = currentService.InvoiceVersion__c + 1;
            services.add(currentService);
        }

        if (emailCooker.getEmails().size() == 0) return;

        emailCooker.send();

        if (services == null || services.isEmpty()) return;
        Database.update(services);
    }

}