force-app/main/default/objects/AP_Contact__c/AP_Contact__c.object-meta.xml
<CustomObject>
    <label>AP Contact</label>
    <nameField>
        <label>AP Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AP Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AP_Contact__c/fields/APContact__c.field-meta.xml
<CustomField>
    <fullName>APContact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AP Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>AP Contacts</relationshipLabel>
    <relationshipName>AP_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AP_Contact__c/fields/Case_Worker__c.field-meta.xml
<CustomField>
    <fullName>Case_Worker__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case Worker</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>AP Contacts (Case Worker)</relationshipLabel>
    <relationshipName>CaseWorker</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Appointment__c/Appointment__c.object-meta.xml
<CustomObject>
    <label>Appointment</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Appointment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Appointment__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>Service__c</referenceTo>
    <relationshipLabel>Appointments</relationshipLabel>
    <relationshipName>Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
                <default>true</default>
                <label>Scheduled</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>No Show</fullName>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Area__c/Area__c.object-meta.xml
<CustomObject>
    <label>Area</label>
    <nameField>
        <label>Area Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Area__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Areas</relationshipLabel>
    <relationshipName>Areas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Area__c/fields/ZipCode__c.field-meta.xml
<CustomField>
    <fullName>ZipCode__c</fullName>
    <label>Zip Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location (NWFB)</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations (NWFB)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service__c/Service__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Area</label>
    <referenceTo>Area__c</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Caseworker__c.field-meta.xml
<CustomField>
    <fullName>Caseworker__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Must be a contact of the agency that you selected.</inlineHelpText>
    <label>Caseworker</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Case Manager</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Client Request</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Services (Caseworker)</relationshipLabel>
    <relationshipName>Requests1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Client contact record attached to this request</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Services (Contact)</relationshipLabel>
    <relationshipName>Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/DeletionDate__c.field-meta.xml
<CustomField>
    <fullName>DeletionDate__c</fullName>
    <label>Deletion Date (old)</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>Request</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Processing</fullName>
                <default>true</default>
                <label>Processing</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Routing</fullName>
            </value>
            <value>
                <fullName>Shopping</fullName>
            </value>
            <value>
                <fullName>Delivery</fullName>
            </value>
            <value>
                <fullName>Pick Up</fullName>
            </value>
            <value>
                <fullName>Review</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
                <isActive>false</isActive>
                <label>Active</label>
            </value>
            <value>
                <fullName>Complete</fullName>
                <isActive>false</isActive>
                <label>Complete</label>
            </value>
            <value>
                <fullName>Draft</fullName>
                <isActive>false</isActive>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Expiring</fullName>
                <isActive>false</isActive>
                <label>Expiring</label>
            </value>
            <value>
                <fullName>Items Owed</fullName>
                <isActive>false</isActive>
                <label>Items Owed</label>
            </value>
            <value>
                <fullName>No Call / No Show</fullName>
                <isActive>false</isActive>
                <label>No Call / No Show</label>
            </value>
            <value>
                <fullName>Re-Delivery</fullName>
                <isActive>false</isActive>
                <label>Re-Delivery</label>
            </value>
            <value>
                <fullName>Served</fullName>
                <isActive>false</isActive>
                <label>Served</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service__c/fields/SubType__c.field-meta.xml
<CustomField>
    <fullName>SubType__c</fullName>
    <label>Sub Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Will Call</fullName>
            </value>
            <value>
                <fullName>Delivery</fullName>
            </value>
            <value>
                <fullName>Hope Run</fullName>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>Hope Del.</fullName>
            </value>
            <value>
                <fullName>Donation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service__c/fields/Trip__c.field-meta.xml
<CustomField>
    <fullName>Trip__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Trip</label>
    <referenceTo>Trip__c</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/TruckNotes__c.field-meta.xml
<CustomField>
    <fullName>TruckNotes__c</fullName>
    <label>Truck Notes</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Zip__c.field-meta.xml
<CustomField>
    <fullName>Zip__c</fullName>
    <label>Zip</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trip__c/Trip__c.object-meta.xml
<CustomObject>
    <label>Trip</label>
    <nameField>
        <label>Trips Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trips</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Trip__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Trips</relationshipLabel>
    <relationshipName>Trips</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trip__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Trips</relationshipLabel>
    <relationshipName>Trips</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trip__c/fields/PrimaryTimeframe__c.field-meta.xml
<CustomField>
    <fullName>PrimaryTimeframe__c</fullName>
    <label>Primary Timeframe</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Morning</fullName>
            </value>
            <value>
                <fullName>Afternoon</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trip__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>Service__c</referenceTo>
    <relationshipLabel>Trips</relationshipLabel>
    <relationshipName>Trips</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trip__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Started</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trip__c/fields/Truck__c.field-meta.xml
<CustomField>
    <fullName>Truck__c</fullName>
    <label>Truck</label>
    <referenceTo>Truck__c</referenceTo>
    <relationshipLabel>Trips</relationshipLabel>
    <relationshipName>Trips</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Truck__c/Truck__c.object-meta.xml
<CustomObject>
    <label>Truck</label>
    <nameField>
        <label>Truck Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trucks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Truck__c/fields/LicensePlate__c.field-meta.xml
<CustomField>
    <fullName>LicensePlate__c</fullName>
    <label>License Plate</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Truck__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Trucks</relationshipLabel>
    <relationshipName>Trucks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ServiceDaoTest.cls
/**
 * Created by Gustavo on 05/01/24.
 */

@IsTest
private class ServiceDaoTest {
    @IsTest
    public static void setServiceName() {
        Contact contact = new Contact(
                FirstName = 'Test',
                LastName = 'Test'
        );
        insert contact;

        Service__c service = new Service__c(
                Contact__c = contact.Id
        );

        insert service;
        ServiceDao.getInstance().setServiceName();

        Service__c updatedService = [SELECT Id, Name FROM Service__c WHERE Id = :service.Id LIMIT 1];
        System.assert(updatedService.Name != null);
    }

    @IsTest
    public static void sendTripScheduledNotification() {
        Contact contact = new Contact(
                FirstName = 'Test',
                LastName = 'Test',
                Email = 'test@gmail.com'
        );
        insert contact;

        Location__c location = new Location__c(
                Name = 'Tacoma',
                City__c = 'Tacoma'
        );
        insert location;

        Truck__c truck = new Truck__c(
                LicensePlate__c = '00001',
                Active__c = true
        );
        insert truck;

        Trip__c trip = new Trip__c(
                Name = 'Test',
                Location__c = location.Id,
                Truck__c = truck.Id,
                PrimaryTimeframe__c = 'Morning',
                Date__c = Date.today()
        );
        insert trip;

        Service__c service = new Service__c(
                Contact__c = contact.Id,
                Trip__c = trip.Id,
                Location__c = location.Id,
                Status__c = 'Routing',
                SubType__c = 'Delivery',
                RecordTypeId = Utils.getRecordTypeId(Service__c.SObjectType, 'Client Request')
        );
        insert service;

        service.Status__c = 'Shopping';
        update service;

        System.assert(Limits.getEmailInvocations() > 0);
    }

    @IsTest
    public static void setAreaByZipCode() {
        Contact contact = new Contact(
                FirstName = 'Test',
                LastName = 'Test'
        );
        insert contact;

        Area__c area = new Area__c(
                ZipCode__c = '123'
        );
        insert area;

        Service__c service = new Service__c(
                Zip__c = '123',
                Contact__c = contact.Id
        );
        insert service;

        ServiceDao.getInstance().setAreaByZipCode();
        Service__c updatedService = [SELECT Id, Area__c FROM Service__c WHERE Id = :service.Id LIMIT 1];
        System.assert(updatedService.Area__c != null);
    }

    @IsTest
    public static void setPossibleDeleteDate() {
        Contact contact = new Contact(
                FirstName = 'Test',
                LastName = 'Test'
        );
        insert contact;

        Service__c service = new Service__c(
                Contact__c = contact.Id
        );
        insert service;

        Appointment__c appointment = new Appointment__c(
                Status__c = 'Scheduled',
                Service__c = service.Id
        );
        TriggerManagement.disableTrigger('AppointmentTrigger');
        insert appointment;
        TriggerManagement.enableTrigger('AppointmentTrigger');
        update service;


        ServiceDao.getInstance().setPossibleDeleteDate();
        Service__c updatedService = [SELECT Id, DeletionDate__c FROM Service__c WHERE Id = :service.Id LIMIT 1];

        System.assert(updatedService.DeletionDate__c != null);
    }

    @IsTest(SeeAllData=true)
    public static void sendEmailBasedOnStatus() {
        Contact contact = new Contact(
                FirstName = 'Test',
                LastName = 'Test'
        );

        insert contact;

        Service__c service = new Service__c(
                Contact__c = contact.Id,
                Status__c = 'Scheduled',
                RecordTypeId = Utils.getRecordTypeId(Service__c.SObjectType, 'Client Request'),
                SubType__c = 'Will Call'
        );

        insert service;
    }

    @IsTest
    static void generateInvoiceAndSendPDF() {
        Account account = new Account(
                Name = 'Test Account',
                Type = 'Agency',
                Active__c = true
        );
        insert account;

        Contact serviceContact = new Contact(
                FirstName = 'Test',
                LastName = 'Test',
                Email = 'test@example.com'
        );

        insert serviceContact;


        Contact caseworker = new Contact(
                FirstName = 'caseworker',
                LastName = 'test',
                Email = 'caseworkertest@example.com',
                AccountId = account.Id,
                AP_Contact_Email__c = 'caseworkertest@example.com'
        );
        insert caseworker;
        caseworker.RecordTypeId = Utils.getRecordTypeId(Contact.SObjectType, 'Case Manager');
        update caseworker;

        AP_Contact__c apContact = new AP_Contact__c(
                Name = 'Test',
                Case_Worker__c = caseworker.Id,
                APContact__c = serviceContact.Id
        );
        insert apContact;

        Service__c service = new Service__c(
                Contact__c = serviceContact.Id,
                Status__c = 'Scheduled',
                Caseworker__c = caseworker.Id,
                RecordTypeId = Utils.getRecordTypeId(Service__c.SObjectType, 'Client Request'),
                SubType__c = 'Will Call'
        );
        insert service;

        System.assert(ServiceDao.callGenerateInvoiceAndSendPDF(service.Id, true, true, true) == 'SentEmails');
    }

    @IsTest
    public static void testSendScheduledPickupMessage() {
        Contact serviceContact = new Contact(
                FirstName = 'Test',
                LastName = 'Test',
                Email = 'test@example.com',
                MobilePhone = '1123123123'
        );
        insert serviceContact;

        Location__c location = new Location__c(
                Name = 'Tacoma',
                City__c = 'Tacoma'
        );
        insert location;

        Truck__c truck = new Truck__c(
                LicensePlate__c = '00001',
                Active__c = true
        );
        insert truck;

        Trip__c trip = new Trip__c(
                Name = 'Test',
                Location__c = location.Id,
                Truck__c = truck.Id,
                PrimaryTimeframe__c = 'Morning',
                Date__c = Date.today()
        );
        insert trip;

        Service__c service = new Service__c(
                Contact__c = serviceContact.Id,
                Status__c = 'Processing',
                Trip__c = trip.Id,
                RecordTypeId = Utils.getRecordTypeId(Service__c.SObjectType, 'Donation Pickup'),
                SubType__c = 'Donation'
        );
        TriggerManagement.disableTrigger('ServiceTrigger');
        insert service;
        TriggerManagement.enableTrigger('ServiceTrigger');

        service.Status__c = 'Pick Up';
        update service;

        Service__c updatedService = [SELECT Id, Name FROM Service__c WHERE Id = :service.Id];

        String taskSubject = 'Donation Pickup ' + updatedService.Name + ' Confirmed';

        Task donationPickupConfirmedTask = [SELECT Id FROM Task WHERE WhatId =: service.Id AND Subject = :taskSubject];
        System.assert(donationPickupConfirmedTask != null);
    }

    @isTest
    public static void testLitTodelete() {
        Contact contact = new Contact(
                FirstName = 'Test',
                LastName = 'Test'
        );

        insert contact;

        Service__c service = new Service__c(
                Contact__c = contact.Id,
                Status__c = 'Scheduled',
                RecordTypeId = Utils.getRecordTypeId(Service__c.SObjectType, 'Client Request'),
                SubType__c = 'Will Call'
        );

        insert service;

        List<Service__c> toDelete = new List<Service__c>{
                service
        };
        List<List<SObject>> listfromListToDelete = new List<List<SObject>>{
                toDelete
        };
        ServiceDao serviceClass = new ServiceDao();
        serviceClass.deleteDuplicateRecords(listfromListToDelete);
    }

    @IsTest
    public static void testAdjustTruckNotes() {
        Contact contact = new Contact(
                FirstName = 'Test',
                LastName = 'Test'
        );

        insert contact;

        Service__c service = new Service__c(
                Contact__c = contact.Id,
                Status__c = 'Scheduled',
                TruckNotes__c = 'Test',
                RecordTypeId = Utils.getRecordTypeId(Service__c.SObjectType, 'Client Request'),
                SubType__c = 'Will Call'
        );
        insert service;

        service.TruckNotes__c = 'Testing';
        update service;
    }


}