force-app/main/default/objects/AP_Contact__c/AP_Contact__c.object-meta.xml
<CustomObject>
    <label>AP Contact</label>
    <nameField>
        <label>AP Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AP Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AP_Contact__c/fields/Case_Worker__c.field-meta.xml
<CustomField>
    <fullName>Case_Worker__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case Worker</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>AP Contacts (Case Worker)</relationshipLabel>
    <relationshipName>CaseWorker</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location (NWFB)</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations (NWFB)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service__c/Service__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service__c/fields/Caseworker__c.field-meta.xml
<CustomField>
    <fullName>Caseworker__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Must be a contact of the agency that you selected.</inlineHelpText>
    <label>Caseworker</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Case Manager</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Client Request</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Services (Caseworker)</relationshipLabel>
    <relationshipName>Requests1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/DeletionDate__c.field-meta.xml
<CustomField>
    <fullName>DeletionDate__c</fullName>
    <label>Deletion Date (old)</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <formula>CreatedDate + 60</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>Request</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/NumberOfScheduledAppointments__c.field-meta.xml
<CustomField>
    <fullName>NumberOfScheduledAppointments__c</fullName>
    <label>Number Of Scheduled Appointments</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Processing</fullName>
                <default>true</default>
                <label>Processing</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Routing</fullName>
            </value>
            <value>
                <fullName>Shopping</fullName>
            </value>
            <value>
                <fullName>Delivery</fullName>
            </value>
            <value>
                <fullName>Pick Up</fullName>
            </value>
            <value>
                <fullName>Review</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
                <isActive>false</isActive>
                <label>Active</label>
            </value>
            <value>
                <fullName>Complete</fullName>
                <isActive>false</isActive>
                <label>Complete</label>
            </value>
            <value>
                <fullName>Draft</fullName>
                <isActive>false</isActive>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Expiring</fullName>
                <isActive>false</isActive>
                <label>Expiring</label>
            </value>
            <value>
                <fullName>Items Owed</fullName>
                <isActive>false</isActive>
                <label>Items Owed</label>
            </value>
            <value>
                <fullName>No Call / No Show</fullName>
                <isActive>false</isActive>
                <label>No Call / No Show</label>
            </value>
            <value>
                <fullName>Re-Delivery</fullName>
                <isActive>false</isActive>
                <label>Re-Delivery</label>
            </value>
            <value>
                <fullName>Served</fullName>
                <isActive>false</isActive>
                <label>Served</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service__c/recordTypes/ClientRequest.recordType-meta.xml
<RecordType>
    <fullName>ClientRequest</fullName>
    <active>true</active>
    <label>Client Request</label>
</RecordType>

force-app/main/default/classes/ClientRequestExpirationBatch.cls
global class ClientRequestExpirationBatch implements Database.Batchable<SObject>, Database.AllowsCallouts {

    global Database.QueryLocator start(Database.BatchableContext BC) {

        return Database.getQueryLocator([
            SELECT  Id,
                    Caseworker__c,
                    Caseworker__r.Email,
                    NumberOfScheduledAppointments__c,
                    Expiration_Date__c,
                    DeletionDate__c,
                    Status__c,
                    Location__r.City__c
            FROM Service__c
            WHERE RecordType.DeveloperName = 'ClientRequest'
        ]);
    }

    global void execute(Database.BatchableContext BC, List<Service__c> scope) {
        List<Service__c> expiredServices = new List<Service__c>();
        List<Service__c> serviceToDelete = new List<Service__c>();
        List<Messaging.SingleEmailMessage> emailMessages = new List<Messaging.SingleEmailMessage>();

        OrgWideEmailAddress tacomaEmailAddress = new OrgWideEmailAddressSelector().getOrgWideEmailAddress(
                'clientservices@nwfurniturebank.org'
        );

        OrgWideEmailAddress vancouverEmailAddress = new OrgWideEmailAddressSelector().getOrgWideEmailAddress(
                'vaninfo@nwfurniturebank.org'
        );

        EmailTemplate clientRequestExpiredEmailTemplate = EmailTemplateSelector.getInstance()
                .getEmailTemplateByDeveloperName('ClientRequestExpired');

        for (Service__c clientRequest : scope) {
            if (clientRequest.NumberOfScheduledAppointments__c > 0) continue;
            OrgWideEmailAddress currentlyEmailLocation = clientRequest.Location__r.City__c == 'Tacoma'
                    ? tacomaEmailAddress
                    : vancouverEmailAddress;

            if (Date.today() == clientRequest.Expiration_Date__c) {
                clientRequest.Status__c = 'Expired';
                expiredServices.add(clientRequest);
                Messaging.SingleEmailMessage mail = createEmail(
                        clientRequest,
                        clientRequestExpiredEmailTemplate.Id,
                        currentlyEmailLocation
                );
                if (mail != null) emailMessages.add(mail);
            }

            if (Date.today() == clientRequest.DeletionDate__c && clientRequest.Status__c == 'Expired') {
                serviceToDelete.add(clientRequest);
            }
        }

        if (!expiredServices.isEmpty()) {
            update expiredServices;
        }

        if (!emailMessages.isEmpty()) {
           Messaging.sendEmail(emailMessages);
        }

        if (!serviceToDelete.isEmpty()) {
            delete serviceToDelete;
        }
    }

    global void finish(Database.BatchableContext BC) {}

    private static Messaging.SingleEmailMessage createEmail(Service__c clientRequest, String templateId, OrgWideEmailAddress orgWideEmailAddress) {
        Messaging.SingleEmailMessage emailMessage = null;

        if (clientRequest.Caseworker__c != null) {
            emailMessage = new Messaging.SingleEmailMessage();
            emailMessage.setTemplateId(templateId);
            emailMessage.setTargetObjectId(clientRequest.Caseworker__c);
            emailMessage.setSaveAsActivity(false);
            emailMessage.setWhatId(clientRequest.Id);
            emailMessage.setOrgWideEmailAddressId(orgWideEmailAddress.Id);
            emailMessage.setToAddresses(new List<String>{clientRequest.Caseworker__r.Email});
        }
        return emailMessage;
    }
}