force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>Service__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Void</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/TotalPaid__c.field-meta.xml
<CustomField>
    <fullName>TotalPaid__c</fullName>
    <label>Total Paid</label>
    <summarizedField>InvoicePayment__c.Amount__c</summarizedField>
    <summaryForeignKey>InvoicePayment__c.Invoice__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/PaymentAmount__c.field-meta.xml
<CustomField>
    <fullName>PaymentAmount__c</fullName>
    <label>Payment Amount</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/PaymentMethod__c.field-meta.xml
<CustomField>
    <fullName>PaymentMethod__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cash</fullName>
                <color>#006600</color>
                <label>Cash</label>
            </value>
            <value>
                <fullName>CreditCard</fullName>
                <color>#996633</color>
                <label>Credit Card</label>
            </value>
            <value>
                <fullName>DebitCard</fullName>
                <color>#EFAE73</color>
                <label>Debit Card</label>
            </value>
            <value>
                <fullName>Wire</fullName>
                <color>#663366</color>
                <label>Wire</label>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
            <value>
                <fullName>Card</fullName>
            </value>
            <value>
                <fullName>Check</fullName>
                <color>#AFCADF</color>
                <label>Check</label>
            </value>
            <value>
                <fullName>Bulletin de Versement</fullName>
                <isActive>false</isActive>
                <label>Bulletin de Versement</label>
            </value>
            <value>
                <fullName>Credit Card Old</fullName>
                <isActive>false</isActive>
                <label>Credit Card Old</label>
            </value>
            <value>
                <fullName>ECheck</fullName>
                <isActive>false</isActive>
                <label>E-Check</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment__c/fields/PaymentType__c.field-meta.xml
<CustomField>
    <fullName>PaymentType__c</fullName>
    <label>Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Payment</fullName>
                <default>true</default>
                <label>Payment</label>
            </value>
            <value>
                <fullName>Refund</fullName>
            </value>
            <value>
                <fullName>ActivationFee</fullName>
                <isActive>false</isActive>
                <label>Activation Fee</label>
            </value>
            <value>
                <fullName>Application Fee</fullName>
                <isActive>false</isActive>
                <label>Application Fee</label>
            </value>
            <value>
                <fullName>Application Fee Refund</fullName>
                <isActive>false</isActive>
                <label>Application Fee Refund</label>
            </value>
            <value>
                <fullName>EventFees</fullName>
                <isActive>false</isActive>
                <label>Event Fees</label>
            </value>
            <value>
                <fullName>KokuaCrewAppFee</fullName>
                <isActive>false</isActive>
                <label>Kokua Crew App Fee</label>
            </value>
            <value>
                <fullName>Kokua Crew Fees</fullName>
                <isActive>false</isActive>
                <label>Kokua Crew Fees</label>
            </value>
            <value>
                <fullName>MealCredit</fullName>
                <isActive>false</isActive>
                <label>Meal Credit</label>
            </value>
            <value>
                <fullName>Overpayment</fullName>
                <isActive>false</isActive>
                <label>Overpayment</label>
            </value>
            <value>
                <fullName>School Fees</fullName>
                <isActive>false</isActive>
                <label>School Fees</label>
            </value>
            <value>
                <fullName>StaffAppFee</fullName>
                <isActive>false</isActive>
                <label>Staff App Fee</label>
            </value>
            <value>
                <fullName>StaffFees</fullName>
                <isActive>false</isActive>
                <label>Staff Fees</label>
            </value>
            <value>
                <fullName>StaffPayment</fullName>
                <isActive>false</isActive>
                <label>Staff Payment</label>
            </value>
            <value>
                <fullName>StudentAppFee</fullName>
                <isActive>false</isActive>
                <label>Student App Fee</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>Service__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>(&quot;Processing&quot;)</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Voided</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service__c/Service__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Client contact record attached to this request</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Services (Contact)</relationshipLabel>
    <relationshipName>Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Processing</fullName>
                <default>true</default>
                <label>Processing</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Routing</fullName>
            </value>
            <value>
                <fullName>Shopping</fullName>
            </value>
            <value>
                <fullName>Delivery</fullName>
            </value>
            <value>
                <fullName>Pick Up</fullName>
            </value>
            <value>
                <fullName>Review</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
                <isActive>false</isActive>
                <label>Active</label>
            </value>
            <value>
                <fullName>Complete</fullName>
                <isActive>false</isActive>
                <label>Complete</label>
            </value>
            <value>
                <fullName>Draft</fullName>
                <isActive>false</isActive>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Expiring</fullName>
                <isActive>false</isActive>
                <label>Expiring</label>
            </value>
            <value>
                <fullName>Items Owed</fullName>
                <isActive>false</isActive>
                <label>Items Owed</label>
            </value>
            <value>
                <fullName>No Call / No Show</fullName>
                <isActive>false</isActive>
                <label>No Call / No Show</label>
            </value>
            <value>
                <fullName>Re-Delivery</fullName>
                <isActive>false</isActive>
                <label>Re-Delivery</label>
            </value>
            <value>
                <fullName>Served</fullName>
                <isActive>false</isActive>
                <label>Served</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service__c/fields/TotalPaid__c.field-meta.xml
<CustomField>
    <fullName>TotalPaid__c</fullName>
    <label>Total Paid</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/PaymentDao.cls
public without sharing class PaymentDao extends GenericDao {
    @TestVisible
    private static PaymentDao mock;

    public PaymentDao() {
    }

    private PaymentDao(List<SObject> payments, Map<Id, SObject> oldPaymentsById) {
        super(payments, oldPaymentsById);
    }
    private PaymentDao(List<SObject> payments) {
        super(payments);
    }

    public static PaymentDao getInstance() {
        if (Test.isRunningTest() && mock != null) {
            return mock;
        } else {
            return new PaymentDao(new List<Payment__c>());
        }
    }

    public override void afterInsert() {
        sendRefundEmail();
//        sendEmailByStatus();
//        rollUpInvoiceAmountDue();
        rollup();
    }
    public override void afterUpdate() {
//        sendEmailByStatus();
//        rollUpInvoiceAmountDue();
        rollup();
    }

    public override void afterDelete() {
//        rollUpInvoiceAmountDue();
        rollup();
    }

    private void rollup() {
        if (this.records != null && !this.records.isEmpty()) {
            Database.update(dlrs.RollupService.rollup(this.records));
        }
    }

//    private void sendEmailByStatus() {
//        Map<Id, SObject> newRecordsMap = new Map<Id, SObject>(this.records);
//        Map<Id, SObject> oldPayments = (Map<Id, SObject>) this.oldRecordsById;
//        Set<Id> invoiceIds = new Set<Id>();
//
//        for (Payment__c payment : (List<Payment__c>) newRecordsMap.values()) {
//            if (payment.Invoice__c == null) continue;
//
//            invoiceIds.add(payment.Invoice__c);
//        }
//
//        List<String> emailTemplateNames = new List<String>{
//            'PaymentCompleted'
//        };
//
//        Map<String, EmailTemplate> emailTemplatesByNameMap = EmailTemplateSelector.getInstance().getEmailTemplatesByDeveloperNames(emailTemplateNames);
//        Map<Id, Invoice__c> invoiceMap = new Map<Id, Invoice__c>(InvoiceSelector.getInstance().getInvoicesByIds(invoiceIds));
//        Map<String, OrgWideEmailAddress> addressToOrgWideEmail = OrgWideEmailAddressSelector.getInstance().getOrgWideEmailAddressByEmailAddress('clientservices@nwfurniturebank.org');
//
//        for(Payment__c payment : (List<Payment__c>) newRecordsMap.values()){
//            Payment__c oldPayment = (Payment__c)oldPayments?.get(payment.Id);
//
//            if (payment.Status__c != 'Approved' || (payment.Status__c == oldPayment.Status__c)) continue;
//
////            sendEmail(emailTemplatesByNameMap.get('PaymentCompleted'), invoiceMap.get(payment.Invoice__c), addressToOrgWideEmail.get('clientservices@nwfurniturebank.org').Id);
//        }
//    }

//    private void sendEmail(EmailTemplate emailTemplatesByNameMap, Invoice__c invoice, Id orgWideEmailAddressId) {
//        List<String> toEmailAddressList = new List<String>{
//                invoice.Service__r.Contact__r.Email
//        };
//
//        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
//        mail.setTemplateId(emailTemplatesByNameMap.Id);
//        mail.setToAddresses(toEmailAddressList);
//        mail.setTargetObjectId(invoice.Service__c);
//        mail.setSaveAsActivity(false);
//        mail.setOrgWideEmailAddressId(orgWideEmailAddressId);
//
//        List<Messaging.SingleEmailMessage> emailMessageList = new List<Messaging.SingleEmailMessage>{
//                mail
//        };
//
//        try {
//            List<Messaging.SendEmailResult> results = Messaging.sendEmail(emailMessageList);
//            System.debug('results ' + results);
//
//        } catch (Exception e) {
//            System.debug(e.getMessage());
//        }
//    }
    @TestVisible
    private void sendRefundEmail() {
        List<Messaging.SingleEmailMessage> emails = new List<Messaging.SingleEmailMessage>();
        EmailTemplate paymentRefundEmailTemplate = new EmailTemplateSelector().getEmailTemplateByName('Payment Refund');

        Map<String, OrgWideEmailAddress> orgWideEmailAddressByEmail = OrgWideEmailAddressSelector.getInstance()
                .getOrgWideEmailAddressByEmailAddress('clientservices@nwfurniturebank.org');

        Set<Id> paymentIds = new Set<Id>();

        for (Payment__c payment : (List<Payment__c>) records) {
            paymentIds.add(payment.Id);
        }

        Map<Id, SObject> paymentsByIds = Utils.listToMap(
                'Id',
                PaymentSelector.getInstance().byIds(paymentIds)
        );

        for (Payment__c pm : (List<Payment__c>) records) {
            Payment__c payment = (Payment__c) paymentsByIds.get(pm.Id);

            if (payment.PaymentMethod__c == 'CreditCard') continue;
            if (payment.PaymentType__c != 'Refund') continue;

            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            mail.setTemplateId(paymentRefundEmailTemplate.Id);
            mail.setToAddresses(new List<String>{
                    'ap@nwfurniturebank.org'
            });
            mail.setTargetObjectId(payment.Service__r.Contact__c);
            mail.setTreatTargetObjectAsRecipient(false);
            mail.setWhatId(payment.Id);
            mail.setSaveAsActivity(false);
//            mail.setOrgWideEmailAddressId(orgWideEmailAddressByEmail.get('clientservices@nwfurniturebank.org').Id);
            emails.add(mail);
            System.debug('Added Email');
        }

        try {
            List<Messaging.SendEmailResult> results = Messaging.sendEmail(emails);
        } catch (Exception e) {
            System.debug(e.getMessage());
        }
    }


//    @TestVisible
//    private void rollUpInvoiceAmountDue(){
    // Map<Id, SObject> newRecordsMap = new Map<Id, SObject>(this.records);
    // Set<Id> invoiceIdSet = new Set<Id>();
    // for(Payment__c payment : (List<Payment__c>) newRecordsMap.values()){
    //     invoiceIdSet.add(payment.Invoice__c);
    // }
    // invoiceIdSet.remove(null);
    // Map<Id, Invoice__c> invoicesMap = new Map<Id, Invoice__c>(InvoiceSelector.getInstance().getInvoicesByIds(invoiceIdSet));
    // for(Payment__c payment : (List<Payment__c>) newRecordsMap.values()){
    //     if(String.isNotBlank(payment.Invoice__c)){
    //         Invoice__c invoice = invoicesMap.get(payment.Invoice__c);
    //         if(invoice.TotalPaid__c == null){
    //             invoice.TotalPaid__c = 0;
    //         }
    //         invoice.TotalPaid__c += payment.PaymentAmount__c;
    //         invoicesMap.put(payment.Invoice__c, invoice);
    //     }
    // }
    // update invoicesMap.values();
//    }


    public class Factory implements TriggerHandlerFactory {
        public TriggerHandler create(List<SObject> objects, Map<Id, SObject> oldObjectsById) {
            return new PaymentDao(objects, oldObjectsById);
        }
    }
}