force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>Service__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InvoiceItem__c/InvoiceItem__c.object-meta.xml
<CustomObject>
    <label>Invoice Item</label>
    <nameField>
        <label>Invoice Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/InvoiceItem__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Invoice Items</relationshipLabel>
    <relationshipName>InvoiceItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/InvoiceItem__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/InvoiceItem__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Processing Fee</fullName>
            </value>
            <value>
                <fullName>Delivery charge</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service__c/Service__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service__c/fields/Processing_Fee__c.field-meta.xml
<CustomField>
    <fullName>Processing_Fee__c</fullName>
    <label>Processing Fee</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/InvoiceItemDao.cls
public with sharing class InvoiceItemDao extends GenericDao{

    @TestVisible
    private static InvoiceItemDao mock;

    public InvoiceItemDao() {}

    private InvoiceItemDao(List<SObject> tasks, Map<Id, SObject> oldTasksById) {
        super(tasks, oldTasksById);
    }

    private InvoiceItemDao(List<SObject> invoiceItems) {
        super(invoiceItems);
    }

//    public static InvoiceItemDao getInstance() {
//        if (Test.isRunningTest() && mock != null) {
//            return mock;
//        } else {
//            return new InvoiceItemDao(new List<InvoiceItem__c>());
//        }
//    }
//
    public class Factory implements TriggerHandlerFactory {
        public TriggerHandler create(List<SObject> objects, Map<Id, SObject> oldObjectsById) {
            return new InvoiceItemDao(objects, oldObjectsById);
        }
    }

//    public override void afterInsert() {
//    }
//
//    public override void beforeInsert() {
//        //setFees();
//    }
//
//    public override void beforeUpdate() {
//        //setFees();
//    }

//    private void setFees(){
//        Map<Id, InvoiceItem__c> invoiceIdToInvoiceItem = new Map<Id, InvoiceItem__c>();
//
//        for(InvoiceItem__c invoiceItem : (List<InvoiceItem__c>)this.records) {
//            invoiceIdToInvoiceItem.put(invoiceItem.Invoice__c, invoiceItem);
//        }
//
//        Map<Id, Invoice__c> relatedInvoice = (Map<Id, Invoice__c>)InvoiceSelector.getInstance().getInvoicesByIds(invoiceIdToInvoiceItem.keySet());
//
//        for(InvoiceItem__c invoiceItem : (List<InvoiceItem__c>)this.records){
//
//            if(relatedInvoice.get(invoiceItem.Invoice__c) == null || relatedInvoice.isEmpty()){continue;}
//
//            invoiceItem.Name = invoiceItem.Type__c;
//
//            if(invoiceItem.Type__c == 'Processing Fee'){
//                invoiceItem.Price__c = relatedInvoice.get(invoiceItem.Invoice__c)?.Service__r.Processing_Fee__c;
//
//            }else{
//                invoiceItem.Price__c =  relatedInvoice.get(invoiceItem.Invoice__c)?.Service__r.Delivery_Fee__c;
//
//            }
//        }
//    }
}