force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Caseworker__c.field-meta.xml
<CustomField>
    <fullName>Caseworker__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Caseworker</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Invoices (Caseworker)</relationshipLabel>
    <relationshipName>Invoices1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/CreateDate__c.field-meta.xml
<CustomField>
    <fullName>CreateDate__c</fullName>
    <label>Create Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>Service__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Void</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/InvoiceItem__c/InvoiceItem__c.object-meta.xml
<CustomObject>
    <label>Invoice Item</label>
    <nameField>
        <label>Invoice Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/InvoiceItem__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Invoice Items</relationshipLabel>
    <relationshipName>InvoiceItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/InvoiceItem__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/InvoiceItem__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Processing Fee</fullName>
            </value>
            <value>
                <fullName>Delivery charge</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service__c/Service__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service__c/fields/Caseworker__c.field-meta.xml
<CustomField>
    <fullName>Caseworker__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Must be a contact of the agency that you selected.</inlineHelpText>
    <label>Caseworker</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Case Manager</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Client Request</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Services (Caseworker)</relationshipLabel>
    <relationshipName>Requests1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/InvoiceCreated__c.field-meta.xml
<CustomField>
    <fullName>InvoiceCreated__c</fullName>
    <label>Invoice Created</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Processing</fullName>
                <default>true</default>
                <label>Processing</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Routing</fullName>
            </value>
            <value>
                <fullName>Shopping</fullName>
            </value>
            <value>
                <fullName>Delivery</fullName>
            </value>
            <value>
                <fullName>Pick Up</fullName>
            </value>
            <value>
                <fullName>Review</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
                <isActive>false</isActive>
                <label>Active</label>
            </value>
            <value>
                <fullName>Complete</fullName>
                <isActive>false</isActive>
                <label>Complete</label>
            </value>
            <value>
                <fullName>Draft</fullName>
                <isActive>false</isActive>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Expiring</fullName>
                <isActive>false</isActive>
                <label>Expiring</label>
            </value>
            <value>
                <fullName>Items Owed</fullName>
                <isActive>false</isActive>
                <label>Items Owed</label>
            </value>
            <value>
                <fullName>No Call / No Show</fullName>
                <isActive>false</isActive>
                <label>No Call / No Show</label>
            </value>
            <value>
                <fullName>Re-Delivery</fullName>
                <isActive>false</isActive>
                <label>Re-Delivery</label>
            </value>
            <value>
                <fullName>Served</fullName>
                <isActive>false</isActive>
                <label>Served</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServiceCharge__mdt/ServiceCharge__mdt.object-meta.xml
<CustomObject>
    <label>Service Charge</label>
    <pluralLabel>Service Charges</pluralLabel>
</CustomObject>

force-app/main/default/objects/ServiceCharge__mdt/fields/DeliveryCost__c.field-meta.xml
<CustomField>
    <fullName>DeliveryCost__c</fullName>
    <label>DeliveryCost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ServiceCharge__mdt/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ServiceCharge__mdt/fields/WillCallCost__c.field-meta.xml
<CustomField>
    <fullName>WillCallCost__c</fullName>
    <label>Will Call Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ServiceItem__c/ServiceItem__c.object-meta.xml
<CustomObject>
    <label>Service Item</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Service Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ServiceItem__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <label>Service</label>
    <referenceTo>Service__c</referenceTo>
    <relationshipLabel>Service Items</relationshipLabel>
    <relationshipName>ServiceItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ServiceItem__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
                <default>true</default>
                <label>Requested</label>
            </value>
            <value>
                <fullName>Not Available</fullName>
            </value>
            <value>
                <fullName>Staged</fullName>
            </value>
            <value>
                <fullName>Not Loaded</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Loaded</fullName>
            </value>
            <value>
                <fullName>Shopping Declined</fullName>
            </value>
            <value>
                <fullName>Not Delivered</fullName>
            </value>
            <value>
                <fullName>Item Rejected</fullName>
            </value>
            <value>
                <fullName>Backlog</fullName>
                <isActive>false</isActive>
                <label>Backlog</label>
            </value>
            <value>
                <fullName>Declined</fullName>
                <isActive>false</isActive>
                <label>Declined</label>
            </value>
            <value>
                <fullName>Delivered</fullName>
                <isActive>false</isActive>
                <label>Delivered</label>
            </value>
            <value>
                <fullName>Received</fullName>
                <isActive>false</isActive>
                <label>Received</label>
            </value>
            <value>
                <fullName>Referred</fullName>
                <isActive>false</isActive>
                <label>Referred</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/InvoiceDao.cls
public with sharing class InvoiceDao extends GenericDao {
    @TestVisible
    private static InvoiceDao mock;

    public InvoiceDao() {
    }

    private InvoiceDao(List<SObject> invoices, Map<Id, SObject> oldInvoicesById) {
        super(invoices, oldInvoicesById);
    }
    private InvoiceDao(List<SObject> invoices) {
        super(invoices);
    }

    public static InvoiceDao getInstance() {
        if (Test.isRunningTest() && mock != null) {
            return mock;
        } else {
            return new InvoiceDao(new List<Invoice__c>());
        }
    }

    public override void afterInsert() {
        createInvoiceItems();
        setCreateInvoiceDate(false);
    }
    public override void beforeInsert() {
        setDueDate();
    }
    public override void beforeUpdate() {
        setDueDate();
    }
    public override void afterUpdate() {
        sendEmailWhenSubmitted();
    }

    public override void afterDelete(){
        setCreateInvoiceDate(true);
    }

    public void setCreateInvoiceDate(Boolean clearField){
        List<Service__c> servicesToUpdate = new List<Service__c>();
        Set<Id> servicesIds = new Set<Id>();

        for (Invoice__c invoice : (List<Invoice__c>) this.records) {
            servicesIds.add(invoice.Service__c);
        }

        for (Id serviceId : servicesIds) {
            if (clearField) {
                servicesToUpdate.add(
                        new Service__c(
                                Id = serviceId,
                                InvoiceCreated__c = null
                        )
                );
                continue;
            }

            servicesToUpdate.add(
                    new Service__c(
                            Id = serviceId,
                            InvoiceCreated__c = System.now()
                    )
            );
        }

        update servicesToUpdate;
    }
    
    @TestVisible
    private void setDueDate(){
        Map<Id, Invoice__c> oldRecordsMap = (Map<Id, Invoice__c>) this.oldRecordsById;

        for (Invoice__c inv : (List<Invoice__c>) this.records) {
            if (oldRecordsMap == null) continue;
            if (inv.CreateDate__c == oldRecordsMap.get(inv.Id).CreateDate__c || inv.CreateDate__c == null) continue;

            inv.DueDate__c = inv.CreateDate__c.addDays(30);
        }
    }

    @TestVisible
    private void createInvoiceItems(){
        List<ServiceCharge__mdt> mapsSettings = [
                SELECT
                        DeliveryCost__c,
                        Quantity__c,
                        WillCallCost__c
                FROM ServiceCharge__mdt
        ];
        Map<Decimal,ServiceCharge__mdt> priceMap = new Map<Decimal,ServiceCharge__mdt>();

        for (ServiceCharge__mdt scm : mapsSettings) {
            priceMap.put(scm.Quantity__c,scm);
        }
        
        Map<Id, Invoice__c> newRecordsMap = new Map<Id, Invoice__c>((List<Invoice__c>) this.records);
        Set<Id> requestIdSet = new Set<Id>();

        for (Invoice__c inv : newRecordsMap.values()) {
            requestIdSet.add(inv.Service__c);
        }

        requestIdSet.remove(null);

        Map<Id,Service__c> requestMap = new Map<Id,Service__c>(
                ServiceSelector.getInstance().getServiceByIdsAndItemsByCategory(requestIdSet)
        );
        List<InvoiceItem__c> invItemInsertList = new List<InvoiceItem__c>();

        for (Invoice__c inv : newRecordsMap.values()) {
            InvoiceItem__c invItem = new InvoiceItem__c(
                    Name = 'Delivery charge Item',
                    Invoice__c = inv.Id,
                    Type__c = 'Delivery charge',
                    Price__c = 125
            );
            invItemInsertList.add(invItem);

            invItem = new InvoiceItem__c(
                    Name = 'Processing Fee Item',
                    Invoice__c = inv.Id,
                    Type__c = 'Processing Fee'
            );
            Decimal price = 0;

            Service__c service = requestMap.get(inv.Service__c);

            if (service != null && service.ServiceItems__r != null && service.ServiceItems__r.size() > 0) {
                price = priceMap.get(service.ServiceItems__r.size()).DeliveryCost__c;
            }

            invItem.Price__c = price;
            invItemInsertList.add(invItem);
        }

        insert invItemInsertList;
    }
    @TestVisible
    private void sendEmailWhenSubmitted(){
        Map<Id, Invoice__c> newRecordsMap = new Map<Id, Invoice__c>((List<Invoice__c>) this.records);
        Map<Id, Invoice__c> oldRecordsMap = (Map<Id, Invoice__c>) this.oldRecordsById;

        Set<Id> contactIdSet = new Set<Id>();

        for (Invoice__c inv : newRecordsMap.values()) {
            if (oldRecordsMap == null) continue;
            Invoice__c oldInvoice = oldRecordsMap.get(inv.Id);

            if (inv.Status__c == 'Submitted' && oldInvoice.Status__c == 'Submitted') continue;

            contactIdSet.add(inv.Caseworker__c);
        }
        contactIdSet.remove(null);
        sendEmailToCaseworkerAndRelatedApContacts(contactIdSet);        
    }

    @TestVisible
    private static void sendEmailToCaseworkerAndRelatedApContacts(Set<Id> contactIdSet){
        EmailTemplate emailTemplate = EmailTemplateSelector.getInstance().getEmailTemplateByName('InvoiceTemplate');
        List<Contact> contactsToNotify = ContactSelector.getInstance().getCaseWorkersAndRelatedApContacts(contactIdSet);
        Map<Id,Id> contactInvoiceIdMap = new Map<Id,Id>();
        Messaging.SingleEmailMessage mail;
        List<Messaging.SingleEmailMessage> mailsList = new List<Messaging.SingleEmailMessage>();

        for(Contact con : contactsToNotify){
            mail = new Messaging.SingleEmailMessage();
            mail.setTargetObjectId(con.Id);
            mail.setWhatId(contactInvoiceIdMap.get(con.Id));
            mail.setTemplateId(emailTemplate.Id);
            mailsList.add(mail);
        }
        //send the email
        Messaging.sendEmail(mailsList);
        
    }

    public class Factory implements TriggerHandlerFactory {
        public TriggerHandler create(List<SObject> objects, Map<Id, SObject> oldObjectsById) {
            return new InvoiceDao(objects, oldObjectsById);
        }
    }
}