force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/CreateDate__c.field-meta.xml
<CustomField>
    <fullName>CreateDate__c</fullName>
    <label>Create Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>Service__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Void</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/InvoicePayment__c/InvoicePayment__c.object-meta.xml
<CustomObject>
    <label>Invoice Payment</label>
    <nameField>
        <displayFormat>IP-{000000}</displayFormat>
        <label>Invoice Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/InvoicePayment__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Invoice Payments</relationshipLabel>
    <relationshipName>Invoice_Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/InvoicePayment__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <label>Payment</label>
    <referenceTo>Payment__c</referenceTo>
    <relationshipLabel>Invoice Payments</relationshipLabel>
    <relationshipName>Invoice_Payments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/InvoicePayment__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>Service__c</referenceTo>
    <relationshipLabel>Invoice Payments</relationshipLabel>
    <relationshipName>Invoice_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/PaymentAmount__c.field-meta.xml
<CustomField>
    <fullName>PaymentAmount__c</fullName>
    <label>Payment Amount</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/PaymentMethod__c.field-meta.xml
<CustomField>
    <fullName>PaymentMethod__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cash</fullName>
                <color>#006600</color>
                <label>Cash</label>
            </value>
            <value>
                <fullName>CreditCard</fullName>
                <color>#996633</color>
                <label>Credit Card</label>
            </value>
            <value>
                <fullName>DebitCard</fullName>
                <color>#EFAE73</color>
                <label>Debit Card</label>
            </value>
            <value>
                <fullName>Wire</fullName>
                <color>#663366</color>
                <label>Wire</label>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
            <value>
                <fullName>Card</fullName>
            </value>
            <value>
                <fullName>Check</fullName>
                <color>#AFCADF</color>
                <label>Check</label>
            </value>
            <value>
                <fullName>Bulletin de Versement</fullName>
                <isActive>false</isActive>
                <label>Bulletin de Versement</label>
            </value>
            <value>
                <fullName>Credit Card Old</fullName>
                <isActive>false</isActive>
                <label>Credit Card Old</label>
            </value>
            <value>
                <fullName>ECheck</fullName>
                <isActive>false</isActive>
                <label>E-Check</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment__c/fields/PaymentType__c.field-meta.xml
<CustomField>
    <fullName>PaymentType__c</fullName>
    <label>Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Payment</fullName>
                <default>true</default>
                <label>Payment</label>
            </value>
            <value>
                <fullName>Refund</fullName>
            </value>
            <value>
                <fullName>ActivationFee</fullName>
                <isActive>false</isActive>
                <label>Activation Fee</label>
            </value>
            <value>
                <fullName>Application Fee</fullName>
                <isActive>false</isActive>
                <label>Application Fee</label>
            </value>
            <value>
                <fullName>Application Fee Refund</fullName>
                <isActive>false</isActive>
                <label>Application Fee Refund</label>
            </value>
            <value>
                <fullName>EventFees</fullName>
                <isActive>false</isActive>
                <label>Event Fees</label>
            </value>
            <value>
                <fullName>KokuaCrewAppFee</fullName>
                <isActive>false</isActive>
                <label>Kokua Crew App Fee</label>
            </value>
            <value>
                <fullName>Kokua Crew Fees</fullName>
                <isActive>false</isActive>
                <label>Kokua Crew Fees</label>
            </value>
            <value>
                <fullName>MealCredit</fullName>
                <isActive>false</isActive>
                <label>Meal Credit</label>
            </value>
            <value>
                <fullName>Overpayment</fullName>
                <isActive>false</isActive>
                <label>Overpayment</label>
            </value>
            <value>
                <fullName>School Fees</fullName>
                <isActive>false</isActive>
                <label>School Fees</label>
            </value>
            <value>
                <fullName>StaffAppFee</fullName>
                <isActive>false</isActive>
                <label>Staff App Fee</label>
            </value>
            <value>
                <fullName>StaffFees</fullName>
                <isActive>false</isActive>
                <label>Staff Fees</label>
            </value>
            <value>
                <fullName>StaffPayment</fullName>
                <isActive>false</isActive>
                <label>Staff Payment</label>
            </value>
            <value>
                <fullName>StudentAppFee</fullName>
                <isActive>false</isActive>
                <label>Student App Fee</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>Service__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>(&quot;Processing&quot;)</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Voided</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service__c/Service__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Client contact record attached to this request</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Services (Contact)</relationshipLabel>
    <relationshipName>Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/InvoiceCreated__c.field-meta.xml
<CustomField>
    <fullName>InvoiceCreated__c</fullName>
    <label>Invoice Created</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Processing</fullName>
                <default>true</default>
                <label>Processing</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Routing</fullName>
            </value>
            <value>
                <fullName>Shopping</fullName>
            </value>
            <value>
                <fullName>Delivery</fullName>
            </value>
            <value>
                <fullName>Pick Up</fullName>
            </value>
            <value>
                <fullName>Review</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
                <isActive>false</isActive>
                <label>Active</label>
            </value>
            <value>
                <fullName>Complete</fullName>
                <isActive>false</isActive>
                <label>Complete</label>
            </value>
            <value>
                <fullName>Draft</fullName>
                <isActive>false</isActive>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Expiring</fullName>
                <isActive>false</isActive>
                <label>Expiring</label>
            </value>
            <value>
                <fullName>Items Owed</fullName>
                <isActive>false</isActive>
                <label>Items Owed</label>
            </value>
            <value>
                <fullName>No Call / No Show</fullName>
                <isActive>false</isActive>
                <label>No Call / No Show</label>
            </value>
            <value>
                <fullName>Re-Delivery</fullName>
                <isActive>false</isActive>
                <label>Re-Delivery</label>
            </value>
            <value>
                <fullName>Served</fullName>
                <isActive>false</isActive>
                <label>Served</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/InvoiceDaoTest.cls
/**
 * Created by Gustavo on 03/01/24.
 */

@IsTest
public with sharing class InvoiceDaoTest {

    @TestSetup
    public static void setup() {
        Contact contact = new Contact(
                FirstName = 'Test',
                LastName = 'Test'
        );
        insert contact;

        Service__c service = new Service__c(
                Contact__c = contact.Id,
                Status__c = 'Processing'
        );
        insert service;
    }


    @IsTest
    public static void setCreateInvoiceDate() {

        Service__c service = [SELECT Id FROM Service__c WHERE Contact__r.FirstName = 'Test'];

        Invoice__c invoice = new Invoice__c(
                DueDate__c = Date.newInstance(2024, 01, 01),
                Status__c = 'Submitted',
                Service__c = service.Id
        );
        insert invoice;

        Payment__c payment = new Payment__c(
                PaymentAmount__c = 10,
                PaymentMethod__c = 'DebitCard',
                PaymentType__c = 'Refund',
                Service__c = service.Id
        );
        insert payment;
        insert new InvoicePayment__c(Amount__c = 1, Invoice__c = invoice.Id, Payment__c = payment.Id);


        Service__c clearedServiceField = [SELECT Id, InvoiceCreated__c FROM Service__c WHERE Contact__r.FirstName = 'Test'];
        System.assert(clearedServiceField.InvoiceCreated__c != null);
        delete invoice;
        Service__c populatedServiceField = [SELECT Id, InvoiceCreated__c FROM Service__c WHERE Contact__r.FirstName = 'Test'];
        System.assert(populatedServiceField.InvoiceCreated__c == null);
    }

    @IsTest
    public static void setDueDate() {
        Service__c service = [SELECT Id FROM Service__c WHERE Contact__r.FirstName = 'Test'];

        Invoice__c invoice = new Invoice__c(
                DueDate__c = Date.newInstance(2024, 01, 01),
                Status__c = 'Draft',
                Service__c = service.Id
        );
        insert invoice;

        invoice.CreateDate__c = Date.today();
        update invoice;

        Invoice__c updatedInvoice = [
                SELECT
                        DueDate__c,
                        CreateDate__c
                FROM Invoice__c
                WHERE Id = :invoice.Id
        ];

        System.assert(updatedInvoice.DueDate__c == updatedInvoice.CreateDate__c.addDays(30));
    }

}