force-app/main/default/objects/DispatcherException__c/DispatcherException__c.object-meta.xml
<CustomObject>
    <label>Dispatcher Exception</label>
    <nameField>
        <label>Dispatcher Exception Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dispatcher Exceptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DispatcherException__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipName>Blockout_Days</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DispatcherException__c/fields/UniqueField__c.field-meta.xml
<CustomField>
    <fullName>UniqueField__c</fullName>
    <label>Unique Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location (NWFB)</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations (NWFB)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/TripExceptionDao.cls
/**
 * Created by Eric Solari on 02/05/2023.
 */

public with sharing class TripExceptionDao extends GenericDao{

    @TestVisible
    private static TripExceptionDao mock;

    public TripExceptionDao() {
    }

    private TripExceptionDao(List<SObject> services, Map<Id, SObject> oldServicesById) {
        super(services, oldServicesById);
    }

    private TripExceptionDao(List<SObject> services) {
        super(services);
    }

    public static TripExceptionDao getInstance() {
        if (Test.isRunningTest() && mock != null) {
            return mock;
        } else {
            return new TripExceptionDao(new List<DispatcherException__c>());
        }
    }

    public override void afterInsert() {

    }

    public override void beforeInsert() {
        validateUniqueCreation();
    }

    public void validateUniqueCreation(){
        Set<String> uniquesStrings = new Set<String>();

        for(DispatcherException__c dispatcherException: (List<DispatcherException__c>) this.records){
            String uniqueString = '' + dispatcherException.RecordTypeId + dispatcherException.Location__c + dispatcherException.Date__c;
            dispatcherException.UniqueField__c = uniqueString;
            uniquesStrings.add(uniqueString);
        }

        //TODO put this in a selector
        Map<String, SObject> createdExceptions = Utils.listToStringMap(
                DispatcherException__c.UniqueField__c,
                [SELECT Id, UniqueField__c FROM DispatcherException__c WHERE UniqueField__c IN: uniquesStrings]
        );

        for(DispatcherException__c dispatcherException: (List<DispatcherException__c>) this.records){
           if (!createdExceptions.containsKey(dispatcherException.UniqueField__c)) continue;
           dispatcherException.addError('There is already an exception created for the informed date and location. Edit the existing exception or create a new one with another date or location.');
        }
    }

    public class Factory implements TriggerHandlerFactory {
        public TriggerHandler create(List<SObject> objects, Map<Id, SObject> oldObjectsById) {
            return new TripExceptionDao(objects, oldObjectsById);
        }
    }
}