force-app/main/default/objects/DispatcherException__c/DispatcherException__c.object-meta.xml
<CustomObject>
    <label>Dispatcher Exception</label>
    <nameField>
        <label>Dispatcher Exception Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dispatcher Exceptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DispatcherException__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipName>Blockout_Days</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DispatcherException__c/fields/TimeFrame__c.field-meta.xml
<CustomField>
    <fullName>TimeFrame__c</fullName>
    <label>TimeFrame</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Morning</fullName>
                <label>Morning (9am - 2pm)</label>
            </value>
            <value>
                <fullName>Afternoon</fullName>
                <label>Afternoon (2pm - 6pm)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DispatcherException__c/fields/UniqueField__c.field-meta.xml
<CustomField>
    <fullName>UniqueField__c</fullName>
    <label>Unique Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location (NWFB)</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations (NWFB)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/TripExceptionDaoTest.cls
/**
 * Created by Gustavo on 08/01/24.
 */

@IsTest
private class TripExceptionDaoTest {
    @TestSetup
    static void setup() {
        Location__c location = new Location__c(
                Name = 'Test'
        );
        insert location;
        DispatcherException__c dispatcherException = new DispatcherException__c(
                Name = 'Test',
                UniqueField__c = '22123',
                TimeFrame__c = 'Morning',
                Location__c = location.Id
        );
        insert dispatcherException;
    }

    @IsTest
    static void validateUniqueCreation() {
        try {
            Location__c location = [SELECT Id FROM Location__c LIMIT 1];

            DispatcherException__c duplicateDispatcherException = new DispatcherException__c(
                    Name = 'Test',
                    UniqueField__c = '22123',
                    TimeFrame__c = 'Morning',
                    Location__c = location.Id
            );
            insert duplicateDispatcherException;
            System.assert(duplicateDispatcherException.Id == null);
        } catch (Exception e) {
            System.assert(e != null);
        }
    }
}