force-app/main/default/objects/CloverConnectPaymentHandler__mdt/CloverConnectPaymentHandler__mdt.object-meta.xml
<CustomObject>
    <label>Clover Connect Payment Handler</label>
    <pluralLabel>Clover Connect Payment Handlers</pluralLabel>
</CustomObject>

force-app/main/default/objects/CloverConnectPaymentHandler__mdt/fields/ClassName__c.field-meta.xml
<CustomField>
    <fullName>ClassName__c</fullName>
    <label>Class Name</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/CloverConnectPaymentManager.cls
/**
 * Created by dudunato on 18/06/22.
 */

public with sharing class CloverConnectPaymentManager {

    private static CloverConnectPaymentManager mock;
    private CloverConnectSettingsSelector settingsSelector;

    private CloverConnectPaymentManager(CloverConnectSettingsSelector settingsSelector) {
        this.settingsSelector = settingsSelector;
    }

    public static CloverConnectPaymentManager getInstance(CloverConnectSettingsSelector settingsSelector) {
        if (Test.isRunningTest() && mock != null) {
            return mock;
        } else {
            return new CloverConnectPaymentManager(settingsSelector);
        }
    }

    public void callHandlers(Map<String, Object> authorizationResponse, String handlerType) {
        callHandlers(null, authorizationResponse, handlerType);
    }

    public void callHandlers(Map<String, Object> requestParams, Map<String, Object> authorizationResponse, String handlerType) {
        if (authorizationResponse == null || authorizationResponse.containsKey('errors')) return;

        List<CloverConnectPaymentHandler__mdt> paymentHandlers = this.settingsSelector.getHandlersByType(
                handlerType
        );

        if (paymentHandlers.isEmpty()) return;

        for (CloverConnectPaymentHandler__mdt paymentHandler : paymentHandlers) {
            Type handlerTypeClass = Type.forName(paymentHandler.ClassName__c);
            CloverConnectPaymentHandler iHandler = (CloverConnectPaymentHandler) handlerTypeClass.newInstance();
            iHandler.process(requestParams, authorizationResponse);
        }

    }

}