force-app/main/default/objects/CloverConnectMerchantSetting__mdt/CloverConnectMerchantSetting__mdt.object-meta.xml
<CustomObject>
    <label>Clover Connect Merchant Setting</label>
    <pluralLabel>Clover Connect Merchant Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/CloverConnectMerchantSetting__mdt/fields/MerchantId__c.field-meta.xml
<CustomField>
    <fullName>MerchantId__c</fullName>
    <label>Merchant Id</label>
    <length>13</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CloverConnectPaymentHandler__mdt/CloverConnectPaymentHandler__mdt.object-meta.xml
<CustomObject>
    <label>Clover Connect Payment Handler</label>
    <pluralLabel>Clover Connect Payment Handlers</pluralLabel>
</CustomObject>

force-app/main/default/objects/CloverConnectPaymentHandler__mdt/fields/ClassName__c.field-meta.xml
<CustomField>
    <fullName>ClassName__c</fullName>
    <label>Class Name</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CloverConnectPaymentHandler__mdt/fields/HandlerType__c.field-meta.xml
<CustomField>
    <fullName>HandlerType__c</fullName>
    <label>Handler Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Authorize</fullName>
                <default>true</default>
                <label>Authorize</label>
            </value>
            <value>
                <fullName>Refund</fullName>
            </value>
            <value>
                <fullName>Funding</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CloverConnectSettingsSelector.cls
/**
 * Created by dudunato on 03/06/22.
 */

public with sharing class CloverConnectSettingsSelector {

    @TestVisible
    private static CloverConnectSettingsSelector mock;
    public static final String HANDLER_TYPE_AUTHORIZE = 'Authorize';

    public static CloverConnectSettingsSelector getInstance() {
        if (Test.isRunningTest() && mock != null) {
            return mock;
        } else {
            return new CloverConnectSettingsSelector();
        }
    }

    public String getMerchantId(String settingDeveloperName) {
        CloverConnectMerchantSetting__mdt currentMerchantSetting = CloverConnectMerchantSetting__mdt.getInstance(
                settingDeveloperName
        );

        if (currentMerchantSetting == null || !currentMerchantSetting.Active__c) {
            throw new CloverConnectException('No merchant setting found!');
        }

        return currentMerchantSetting.MerchantId__c;
    }

    public List<CloverConnectPaymentHandler__mdt> getHandlersByType(String type) {

        return [
                SELECT ClassName__c
                FROM CloverConnectPaymentHandler__mdt
                WHERE HandlerType__c = :type
                  AND Active__c = TRUE
        ];
    }



}