force-app/main/default/objects/Area__c/Area__c.object-meta.xml
<CustomObject>
    <label>Area</label>
    <nameField>
        <label>Area Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Area__c/fields/PhysicalAddress__c.field-meta.xml
<CustomField>
    <fullName>PhysicalAddress__c</fullName>
    <label>Physical Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Area__c/fields/Pickup__c.field-meta.xml
<CustomField>
    <fullName>Pickup__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pickup</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Area__c/fields/Timeframe__c.field-meta.xml
<CustomField>
    <fullName>Timeframe__c</fullName>
    <label>Timeframe(s)</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Morning</fullName>
            </value>
            <value>
                <fullName>Afternoon</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Area__c/fields/ZipCode__c.field-meta.xml
<CustomField>
    <fullName>ZipCode__c</fullName>
    <label>Zip Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pickup__c/Pickup__c.object-meta.xml
<CustomObject>
    <label>Pickup</label>
    <nameField>
        <label>Pickup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pickups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pickup__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Area</label>
    <referenceTo>Area__c</referenceTo>
    <relationshipLabel>Pickups</relationshipLabel>
    <relationshipName>Pickups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pickup__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Pickups</relationshipLabel>
    <relationshipName>Pickups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pickup__c/fields/Stop__c.field-meta.xml
<CustomField>
    <fullName>Stop__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Stop</label>
    <referenceTo>Stop__c</referenceTo>
    <relationshipLabel>Pickups</relationshipLabel>
    <relationshipName>Pickups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProductItem__c/ProductItem__c.object-meta.xml
<CustomObject>
    <label>Product Item</label>
    <nameField>
        <label>Product Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProductItem__c/fields/Pickup__c.field-meta.xml
<CustomField>
    <fullName>Pickup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pickup</label>
    <referenceTo>Pickup__c</referenceTo>
    <relationshipLabel>Product Items</relationshipLabel>
    <relationshipName>ProductItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service__c/Service__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Area</label>
    <referenceTo>Area__c</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Client contact record attached to this request</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Services (Contact)</relationshipLabel>
    <relationshipName>Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Stop__c.field-meta.xml
<CustomField>
    <fullName>Stop__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Stop</label>
    <referenceTo>Stop__c</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Trip__c.field-meta.xml
<CustomField>
    <fullName>Trip__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Trip</label>
    <referenceTo>Trip__c</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stop__c/Stop__c.object-meta.xml
<CustomObject>
    <label>Stop</label>
    <nameField>
        <label>Stop Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stops</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stop__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>Service__c</referenceTo>
    <relationshipLabel>Stops</relationshipLabel>
    <relationshipName>Stops</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stop__c/fields/Trip__c.field-meta.xml
<CustomField>
    <fullName>Trip__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Trip</label>
    <referenceTo>Trip__c</referenceTo>
    <relationshipLabel>Stops</relationshipLabel>
    <relationshipName>Stops</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trip__c/Trip__c.object-meta.xml
<CustomObject>
    <label>Trip</label>
    <nameField>
        <label>Trips Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trips</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Trip__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Trips</relationshipLabel>
    <relationshipName>Trips</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trip__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>Service__c</referenceTo>
    <relationshipLabel>Trips</relationshipLabel>
    <relationshipName>Trips</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TruckSchedulerController.cls
public without sharing class TruckSchedulerController {
    public TruckSchedulerController() {

    }
    @AuraEnabled
    public static Boolean calculateTrip(Id tripId){
        try {
            return TripService.buildStopsTrip(tripId);
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    @AuraEnabled
    public static Boolean createStop(Marker stop, Id tripId){
        try {
            List<Stop__c> tripStops = StopSelector.getInstance().getStopsByTripId(new Set<Id>{tripId});
            Stop__c newStop = new Stop__c();
            newStop.Name = (String) stop.description;
            newStop.Trip__c = tripId;
            insert newStop;
            if(stop.title == 'Pickup'){
                Pickup__c pick = new Pickup__c();
                pick.Id = (Id) stop.id;
                pick.Stop__c = newStop.Id;
                update pick;
            } else {
                Service__c req = new Service__c();
                req.Id = (Id) stop.id;
                req.Stop__c = newStop.Id;
                update req;
            }
            return true;
        } catch (Exception e) {
            System.debug(e.getMessage());
            throw new AuraHandledException(e.getMessage() + e.getStackTraceString());
        }
    }
    @AuraEnabled(cacheable = true)
    public static List<Marker> getPickupsAndRequests(Date tripDate){
        try {
            List<Marker> stops = new List<Marker>();
            List<Marker> deliveries = setMarkers(ServiceSelector.getInstance().getServicesByDate(tripDate), 'Delivery');
            List<Marker> pickups = setMarkers(PickupSelector.getInstance().getPickupsByDate(tripDate), 'Pickup');
            stops.addAll(deliveries);
            stops.addAll(pickups);
            return stops;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage() + e.getStackTraceString());
        }
    }
    private static List<Marker> setMarkers(List<SObject> stops, String type){
        List<Marker> markers = new List<Marker>();
        for(SObject stop : stops){
            Marker marker = new Marker();
            marker.id = stop.Id;
            marker.isChecked = true;
            marker.location = new Location();
            marker.label = stop.getSObject('Area__r')?.get('ZipCode__c');
            marker.value = stop.getSObject('Area__r')?.get('ZipCode__c');
            marker.timeFrame = stop.getSObject('Area__r')?.get('Timeframe__c');
            marker.title = type;
            marker.contact = stop.get('Contact__c') != null ? '/' + stop.get('Contact__c') : '';
            marker.contactName = stop.getSObject('Contact__r')?.get('Name');
            marker.eta = '30 minutes';
            marker.isAddable = stop.get('Stop__c') != null ? true : false;
            marker.items = getItems(stop);
            marker.numberOfItems = getNumberOfItems(stop);
            marker.description = stop.getSObject('Area__r')?.get('PhysicalAddress__c');
            marker.location.PostalCode = stop.getSObject('Area__r')?.get('ZipCode__c');
            marker.location.Street = stop.getSObject('Area__r')?.get('Street__c');
            marker.location.Country = 'USA';
            marker.location.State = 'WA';
            marker.mapIcon = type == 'Pickup' ? 'https://webportal.site/images/blue-dot.png' : 'https://webportal.site/images/red-dot.png';
            marker.icon = type == 'Pickup' ? 'custom:custom93' : 'custom:custom33';
            markers.add(marker);
        }
        return markers;
    }
    private static String getItems(SObject stop){
        Map<String, Object> stopMap = (Map<String, Object>) JSON.deserializeUntyped(JSON.serialize(stop));
        stopMap = (Map<String, Object>) stopMap?.get('ProductItems__r');
        if(stopMap == null){
            return '';
        }
        List<Object> itemsList = (List<Object>) stopMap?.get('records');
        if(itemsList == null){
            return '';
        } 
        String itemsText = '';
        for(Object item : itemsList){
            Map<String, Object> convertedItem = (Map<String, Object>) item;
            itemsText += convertedItem.get('Name') + '\n';
        }
        return itemsText;
    }
    private static Integer getNumberOfItems(SObject stop){
        Map<String, Object> stopMap = (Map<String, Object>) JSON.deserializeUntyped(JSON.serialize(stop));
        stopMap = (Map<String, Object>) stopMap?.get('ProductItems__r');
        if(stopMap == null){
            return 0;
        }
        List<Object> itemsList = (List<Object>) stopMap?.get('records');
        if(itemsList == null){
            return 0;
        } 
        return itemsList.size();
    }
    public class Marker {
        @AuraEnabled
        public Object isChecked {get;set;}
        @AuraEnabled
        public Object id {get;set;}
        @AuraEnabled
        public Object contact {get;set;}
        @AuraEnabled
        public Object contactName {get;set;}
        @AuraEnabled
        public Object eta {get;set;}
        @AuraEnabled
        public Object items {get;set;}
        @AuraEnabled
        public Object label {get;set;}
        @AuraEnabled
        public Object value {get;set;}
        @AuraEnabled
        public Object timeFrame {get;set;}
        @AuraEnabled
        public Object title {get;set;}
        @AuraEnabled
        public Object description {get;set;}
        @AuraEnabled
        public Location location {get;set;}
        @AuraEnabled
        public Object mapIcon {get;set;}
        @AuraEnabled
        public Object icon {get;set;}
        @AuraEnabled
        public Object numberOfItems {get;set;}    
        @AuraEnabled
        public Object isAddable {get;set;}    
        
    }
    public class Location {
        @AuraEnabled
        public Object PostalCode {get;set;}
        @AuraEnabled
        public Object Street {get;set;}
        @AuraEnabled
        public Object Country {get;set;}
        @AuraEnabled
        public Object State {get;set;}
    }
}