force-app/main/default/objects/Area__c/Area__c.object-meta.xml
<CustomObject>
    <label>Area</label>
    <nameField>
        <label>Area Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Area__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Areas</relationshipLabel>
    <relationshipName>Areas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Area__c/fields/PhysicalAddress__c.field-meta.xml
<CustomField>
    <fullName>PhysicalAddress__c</fullName>
    <label>Physical Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location (NWFB)</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations (NWFB)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Location__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <formula>Street__c + &apos;, &apos; 
+ City__c + &apos;, &apos; + State__c + &apos;, &apos; + PostalCode__c + &apos;.&apos;</formula>
    <label>Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stop__c/Stop__c.object-meta.xml
<CustomObject>
    <label>Stop</label>
    <nameField>
        <label>Stop Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stops</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stop__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <formula>Service__r.Address__c + &apos; &apos; + Service__r.City__c  + &apos; &apos; + Service__r.State__c + &apos; &apos; + Service__r.Zip__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stop__c/fields/StopOrder__c.field-meta.xml
<CustomField>
    <fullName>StopOrder__c</fullName>
    <label>Stop order</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stop__c/fields/TravelTime__c.field-meta.xml
<CustomField>
    <fullName>TravelTime__c</fullName>
    <label>Travel Time</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stop__c/fields/Trip__c.field-meta.xml
<CustomField>
    <fullName>Trip__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Trip</label>
    <referenceTo>Trip__c</referenceTo>
    <relationshipLabel>Stops</relationshipLabel>
    <relationshipName>Stops</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trip__c/Trip__c.object-meta.xml
<CustomObject>
    <label>Trip</label>
    <nameField>
        <label>Trips Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trips</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Trip__c/fields/CalculatedTotalTimeText__c.field-meta.xml
<CustomField>
    <fullName>CalculatedTotalTimeText__c</fullName>
    <label>Calculated Total Time Text</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trip__c/fields/Destination__c.field-meta.xml
<CustomField>
    <fullName>Destination__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Destination</label>
    <referenceTo>Area__c</referenceTo>
    <relationshipLabel>Trips (Destination)</relationshipLabel>
    <relationshipName>Trips1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trip__c/fields/GoogleRouteTime__c.field-meta.xml
<CustomField>
    <fullName>GoogleRouteTime__c</fullName>
    <label>Google Route Time</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trip__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Trips</relationshipLabel>
    <relationshipName>Trips</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trip__c/fields/Origin__c.field-meta.xml
<CustomField>
    <fullName>Origin__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Area</label>
    <referenceTo>Area__c</referenceTo>
    <relationshipLabel>Trips</relationshipLabel>
    <relationshipName>Trips</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TripService.cls
public without sharing class TripService {
    public TripService() {

    }

    public static Boolean buildStopsTrip(Id tripId){
        Trip__c trip = TripSelector.getInstance().getTripById(tripId)[0];
        GoogleMapsIntegrationApi gmia = new GoogleMapsIntegrationApi();
        //verify the origin, destinatio, stops. if one of them doesnt exist, then don't calculate.
        if(trip.Stops__r == null || trip.Stops__r.size() == 0) return false;
        //Map<String, Object> routes = gmia.getRoute(trip.Origin__r.PhysicalAddress__c, trip.Destination__r.PhysicalAddress__c, trip.Stops__r);
        Map<String, Object> routes = gmia.getRoute(trip.Location__r.Address__c, trip.Stops__r);
        List<Object> indexOrderList = (List<Object>) routes.get('waypoint_order');
        List<Object> stopsList = (List<Object>) routes.get('legs');

        for (Integer i = 0; i < indexOrderList.size(); i++){
            //set Stop Order
//            trip.Stops__r.get(i).StopOrder__c = Integer.valueOf(indexOrderList.indexOf(i)) + 1;
            //set travel time
            trip.Stops__r.get(i).TravelTime__c = Math.ceil(Double.valueOf(((Map<String, Object>) ((Map<String, Object>) stopsList.get(indexOrderList.indexOf(i))).get('duration')).get('value'))/60);
        }
        Database.update(trip.Stops__r,true);
        return true;
    }


    public Boolean buildStopsTripsSet(Set<Id> tripsIdSet){
        List<Trip__c> trips = TripSelector.getInstance().getTripByIdSet(tripsIdSet);
        List<Stop__c> stopsToUpdate = new List<Stop__c>();
        GoogleMapsIntegrationApi googleMapsIntegrationApi = new GoogleMapsIntegrationApi();

        for (Trip__c trip : trips) {
            if(trip.Stops__r == null || trip.Stops__r.size() == 0) continue;
            List<Stop__c> stopByTrip = trip.Stops__r;

            Map<String, Object> routes = googleMapsIntegrationApi.getRoute(
                    trip.Location__r.Address__c,
                    trip.Stops__r
            );

            List<Object> indexOrderList = (List<Object>) routes.get('waypoint_order');
            List<Object> stopsList = (List<Object>) routes.get('legs');

            Decimal durationTimeMinutes = calculateTotalTime((List<Object>) routes.get('legs'));
            String durationTimeMinutesString = parseTripDurationToString(durationTimeMinutes);

            trip.GoogleRouteTime__c = durationTimeMinutes;
            trip.CalculatedTotalTimeText__c = durationTimeMinutesString;

            for (Integer i = 0; i < (indexOrderList != null ? indexOrderList.size() : 0); i++) {
//                stopByTrip[i].StopOrder__c = Integer.valueOf(indexOrderList.indexOf(i)) + 1;
                stopByTrip[i].TravelTime__c = Math.floor(Double.valueOf(((Map<String, Object>)
                        ((Map<String, Object>) stopsList.get(indexOrderList.indexOf(i))).get('duration')).get('value')) / 60
                );
            }

            stopsToUpdate.addAll(stopByTrip);
        }

        TriggerManagement.disableTrigger('StopTrigger');
        TriggerManagement.disableTrigger('TripTrigger');

        Database.update(stopsToUpdate,false);
        Database.update(trips,false);

        TriggerManagement.enableTrigger('TripTrigger');
        TriggerManagement.enableTrigger('StopTrigger');

        return true;
    }

    private static Decimal calculateTotalTime(List<Object> googleSteps) {
        Decimal totalTimeMinutes = 0;

        if (googleSteps == null || googleSteps.isEmpty()) return 0;

        for (Integer i = 0; i < (googleSteps != null ? googleSteps.size() : 0); i++) {
            Map<String, Object> currentStep = (Map<String, Object>) googleSteps[i];
            Map<String, Object> currentStepDuration = (Map<String, Object>) currentStep.get('duration');
            totalTimeMinutes += Math.floor(Double.valueOf(currentStepDuration.get('value')) / 60);
        }

       return totalTimeMinutes;
    }

    private static String parseTripDurationToString(Decimal durationTimeMinutes) {
        Decimal hours = Math.floor(durationTimeMinutes / 60);
        Decimal minutes = (Decimal) Math.mod((Long) durationTimeMinutes, (Long) 60);
        return hours != 0 ? hours + 'h,  min' + minutes : minutes + 'min';
    }
}