force-app/main/default/objects/Area__c/Area__c.object-meta.xml
<CustomObject>
    <label>Area</label>
    <nameField>
        <label>Area Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Area__c/fields/DaysOfWeek__c.field-meta.xml
<CustomField>
    <fullName>DaysOfWeek__c</fullName>
    <inlineHelpText>Not checking any means the user will be called to schedule.</inlineHelpText>
    <label>Days of Week</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>DaysOfWeek</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Area__c/fields/Delivery__c.field-meta.xml
<CustomField>
    <fullName>Delivery__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Delivery</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Area__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Areas</relationshipLabel>
    <relationshipName>Areas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Area__c/fields/MinimumItems__c.field-meta.xml
<CustomField>
    <fullName>MinimumItems__c</fullName>
    <defaultValue>(&quot;0&quot;)</defaultValue>
    <inlineHelpText>(Pickup only)</inlineHelpText>
    <label>Minimum Items</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
                <label>(none)</label>
            </value>
            <value>
                <fullName>5+ items</fullName>
            </value>
            <value>
                <fullName>10+ items</fullName>
            </value>
            <value>
                <fullName>15+ items</fullName>
            </value>
            <value>
                <fullName>20+ items</fullName>
            </value>
            <value>
                <fullName>25+ items</fullName>
            </value>
            <value>
                <fullName>30+ items</fullName>
            </value>
            <value>
                <fullName>35+ items</fullName>
            </value>
            <value>
                <fullName>40+ items</fullName>
            </value>
            <value>
                <fullName>45+ items</fullName>
            </value>
            <value>
                <fullName>50+ items</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Area__c/fields/PhysicalAddress__c.field-meta.xml
<CustomField>
    <fullName>PhysicalAddress__c</fullName>
    <label>Physical Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Area__c/fields/Pickup__c.field-meta.xml
<CustomField>
    <fullName>Pickup__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pickup</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Area__c/fields/Timeframe__c.field-meta.xml
<CustomField>
    <fullName>Timeframe__c</fullName>
    <label>Timeframe(s)</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Morning</fullName>
            </value>
            <value>
                <fullName>Afternoon</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Area__c/fields/ZipCode__c.field-meta.xml
<CustomField>
    <fullName>ZipCode__c</fullName>
    <label>Zip Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location (NWFB)</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations (NWFB)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pickup__c/Pickup__c.object-meta.xml
<CustomObject>
    <label>Pickup</label>
    <nameField>
        <label>Pickup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pickups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pickup__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Area</label>
    <referenceTo>Area__c</referenceTo>
    <relationshipLabel>Pickups</relationshipLabel>
    <relationshipName>Pickups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pickup__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Pickups</relationshipLabel>
    <relationshipName>Pickups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AreaSelector.cls
/**
 * Created by Gustavo on 28/02/23.
 */

public without sharing class AreaSelector {

    private static AreaSelector instance = null;

    public static AreaSelector getInstance() {
        if (instance == null) {
            instance = new AreaSelector();
        }
        return instance;
    }

    public List<Area__c> getAreaByIds(Set<Id> areaIds) {
        return [
                SELECT
                        Id,
                        Name,
                        DaysOfWeek__c,
                        Delivery__c,
                        Location__c,
                        MinimumItems__c,
                        PhysicalAddress__c,
                        Pickup__c,
                        Street__c,
                        Timeframe__c,
                        ZipCode__c
                FROM Area__c
                WHERE Id IN :areaIds
        ];
    }


    public List<Area__c> getAreaByZipCode(Set<String> zipCodes) {
        return [
                SELECT
                        Id,
                        Name,
                        DaysOfWeek__c,
                        Delivery__c,
                        Location__c,
                        MinimumItems__c,
                        PhysicalAddress__c,
                        Pickup__c,
                        Street__c,
                        Timeframe__c,
                        ZipCode__c
                FROM Area__c
                WHERE ZipCode__c IN :zipCodes
        ];
    }

}