force-app/main/default/objects/AgreementSetting__mdt/AgreementSetting__mdt.object-meta.xml
<CustomObject>
    <label>Agreement Setting</label>
    <pluralLabel>Agreement Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/AgreementSetting__mdt/fields/AgreementText__c.field-meta.xml
<CustomField>
    <fullName>AgreementText__c</fullName>
    <label>Agreement Text</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/MetadataSelector.cls
public with sharing class MetadataSelector {

    private static MetadataSelector instance = null;

    public static MetadataSelector getInstance() {
        if (instance == null) {
        instance = new MetadataSelector();
        }
        return instance;
    }

    @AuraEnabled(cacheable=true)
    public static String getAgreementText(){
        return [SELECT Id, AgreementText__c FROM AgreementSetting__mdt LIMIT 1][0].AgreementText__c;
    }
}