force-app/main/default/objects/CloverConnectLog__c/CloverConnectLog__c.object-meta.xml
<CustomObject>
    <label>Clover Connect Log</label>
    <nameField>
        <displayFormat>CCLOG-{00000}</displayFormat>
        <label>Clover Connect Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clover Connect Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CloverConnectLog__c/fields/ErrorMessage__c.field-meta.xml
<CustomField>
    <fullName>ErrorMessage__c</fullName>
    <label>Error Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CloverConnectLog__c/fields/Payload__c.field-meta.xml
<CustomField>
    <fullName>Payload__c</fullName>
    <label>Payload</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CloverConnectLog__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <label>Service</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Authorize</fullName>
            </value>
            <value>
                <fullName>Profile</fullName>
            </value>
            <value>
                <fullName>Refund</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CloverConnectLog__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Attempt</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failure</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service__c/Service__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Processing</fullName>
                <default>true</default>
                <label>Processing</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Routing</fullName>
            </value>
            <value>
                <fullName>Shopping</fullName>
            </value>
            <value>
                <fullName>Delivery</fullName>
            </value>
            <value>
                <fullName>Pick Up</fullName>
            </value>
            <value>
                <fullName>Review</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
                <isActive>false</isActive>
                <label>Active</label>
            </value>
            <value>
                <fullName>Complete</fullName>
                <isActive>false</isActive>
                <label>Complete</label>
            </value>
            <value>
                <fullName>Draft</fullName>
                <isActive>false</isActive>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Expiring</fullName>
                <isActive>false</isActive>
                <label>Expiring</label>
            </value>
            <value>
                <fullName>Items Owed</fullName>
                <isActive>false</isActive>
                <label>Items Owed</label>
            </value>
            <value>
                <fullName>No Call / No Show</fullName>
                <isActive>false</isActive>
                <label>No Call / No Show</label>
            </value>
            <value>
                <fullName>Re-Delivery</fullName>
                <isActive>false</isActive>
                <label>Re-Delivery</label>
            </value>
            <value>
                <fullName>Served</fullName>
                <isActive>false</isActive>
                <label>Served</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CloverConnectLogManager.cls
/**
 * Created by dudunato on 19/06/22.
 */

public with sharing class CloverConnectLogManager implements Queueable {

    @TestVisible
    private static CloverConnectLogManager mock;
    public static final String STATUS_ATTEMPT = 'Attempt';
    public static final String STATUS_SUCCESS = 'Success';
    public static final String STATUS_FAILURE = 'Failure';

    private List<LogParam> payloads;
    private String currentService;

    public CloverConnectLogManager() {
        this.payloads = new List<LogParam>();
    }

    public static CloverConnectLogManager getInstance() {
        if (Test.isRunningTest() && mock != null) {
            return mock;
        } else {
            return new CloverConnectLogManager();
        }
    }

    public void execute(QueueableContext context) {
        saveLogs();
    }

    private void saveLogs() {

        for (LogParam param : payloads) {
            insert new CloverConnectLog__c(
                    Service__c = currentService,
                    Payload__c = param.payload,
                    Status__c = param.status,
                    ErrorMessage__c = param.errorMessage
            );
        }

    }

    public void setCurrentService(String service) {
        this.currentService = service;
    }

    public void add(Map<String, Object> payload) {
        if (payload == null) {
            this.add('null response', STATUS_FAILURE);
            return;
        }

        if (payload.containsKey('errors') || payload.get('respstat') != 'A') {
            this.add(
                    JSON.serialize(payload),
                    STATUS_FAILURE,
                    payload.containsKey('errors')
                        ? JSON.serialize(payload.get('errors'))
                        : (String) payload.get('resptext')
            );
        } else {
            this.add(
                    JSON.serialize(payload),
                    STATUS_SUCCESS
            );
        }
    }

    public void add(String payload, String status) {
        this.payloads.add(new LogParam(payload, status));
    }

    public void add(String payload, String status, String errorMessage) {
        this.payloads.add(new LogParam(payload, status, errorMessage));
    }

    public void queueUp() {
        System.enqueueJob(this);
    }

    private class LogParam {

        private String payload;
        private String status;
        private String errorMessage;

        LogParam(String payload, String status) {
            this.payload = payload;
            this.status = status;
            this.errorMessage = null;
        }

        LogParam(String payload, String status, String errorMessage) {
            this.payload = payload;
            this.status = status;
            this.errorMessage = errorMessage;
        }


    }

}