force-app/main/default/objects/NWFBSettings__c/NWFBSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>NWFB Settings</label>
</CustomObject>

force-app/main/default/objects/NWFBSettings__c/fields/DisableSMS__c.field-meta.xml
<CustomField>
    <fullName>DisableSMS__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Disable SMS</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/SendSMSQueueable.cls
public class SendSMSQueueable implements Queueable, Database.AllowsCallouts  {
    public String phNumber;
    public String body;
    public String locationName;

    public SendSMSQueueable(String locationName, String phNumber, String body) {
        this.locationName = locationName;
        this.phNumber = phNumber;
        this.body = body;
    }

    public void execute(QueueableContext context) {
        NWFBSettings__c settings = NWFBSettings__c.getOrgDefaults();
        if (!settings.DisableSMS__c) {
            TwillioIntegrationApi tw = new TwillioIntegrationApi(this.locationName, this.phNumber, this.body);
            tw.sendSMS();
        }
    }
}