force-app/main/default/objects/NWFBSettings__c/NWFBSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>NWFB Settings</label>
</CustomObject>

force-app/main/default/objects/Service__c/Service__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Processing</fullName>
                <default>true</default>
                <label>Processing</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Routing</fullName>
            </value>
            <value>
                <fullName>Shopping</fullName>
            </value>
            <value>
                <fullName>Delivery</fullName>
            </value>
            <value>
                <fullName>Pick Up</fullName>
            </value>
            <value>
                <fullName>Review</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
                <isActive>false</isActive>
                <label>Active</label>
            </value>
            <value>
                <fullName>Complete</fullName>
                <isActive>false</isActive>
                <label>Complete</label>
            </value>
            <value>
                <fullName>Draft</fullName>
                <isActive>false</isActive>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Expiring</fullName>
                <isActive>false</isActive>
                <label>Expiring</label>
            </value>
            <value>
                <fullName>Items Owed</fullName>
                <isActive>false</isActive>
                <label>Items Owed</label>
            </value>
            <value>
                <fullName>No Call / No Show</fullName>
                <isActive>false</isActive>
                <label>No Call / No Show</label>
            </value>
            <value>
                <fullName>Re-Delivery</fullName>
                <isActive>false</isActive>
                <label>Re-Delivery</label>
            </value>
            <value>
                <fullName>Served</fullName>
                <isActive>false</isActive>
                <label>Served</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SObjectCRUDControllerTest.cls
/**
 * Created by calebeaires on 18/03/22.
 */

@IsTest
private class SObjectCRUDControllerTest {
    @IsTest
    static void testItAll() {
        List<Account> accounts = (List<Account>) SObjectCRUDController.saveSObjects(
                new List<Account>{
                        new Account(
                                Name = 'Test',
                                ShippingCountry = 'Germany'
                        )
                }
        );

        System.assert(accounts.size() == 1);

        List<Account> accountsFetched = (List<Account>) SObjectCRUDController.listSObjects(
                'Account',
                new List<String>{
                        'Name'
                },
                'AND Id = \'' + accounts[0].Id + '\''
        );

        System.assertEquals(accounts[0].Name, accountsFetched[0].Name);

        SObjectCRUDController.deleteSObjects(accounts);


        System.assert([SELECT Id FROM Account].size() == 0);

    }

    @IsTest
    static void deleteSObjectByFilter() {
        Account account = new Account(
                Name = 'Test',
                ShippingCountry = 'Germany'
        );
        insert account;

        SObjectCRUDController.deleteSObjectsByFilter('Account', 'AND Name = \'Test\'');
        System.assert([SELECT Id FROM Account WHERE Name = 'Test'].isEmpty());
    }

    @IsTest
    static void getPicklist() {
        List<PicklistEnum.Entry> picklistValues = SObjectCRUDController.getPicklist('Service__c', 'Status__c');
        System.assert(picklistValues != null && !picklistValues.isEmpty());
    }

    @IsTest
    static void getCustomSettings() {
        NWFBSettings__c nwfbSettings = SObjectCRUDController.getCustomSettings();
        System.assert(nwfbSettings != null);
    }
}