force-app/main/default/objects/Pickup__c/Pickup__c.object-meta.xml
<CustomObject>
    <label>Pickup</label>
    <nameField>
        <label>Pickup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pickups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pickup__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pickup__c/fields/Stop__c.field-meta.xml
<CustomField>
    <fullName>Stop__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Stop</label>
    <referenceTo>Stop__c</referenceTo>
    <relationshipLabel>Pickups</relationshipLabel>
    <relationshipName>Pickups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Estimated_Value__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Value__c</fullName>
    <label>Estimated Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Pick_up_Fee__c.field-meta.xml
<CustomField>
    <fullName>Pick_up_Fee__c</fullName>
    <inlineHelpText>Fee being charged to pickup an item</inlineHelpText>
    <label>Pick-up Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product_Fee__c.field-meta.xml
<CustomField>
    <fullName>Product_Fee__c</fullName>
    <inlineHelpText>This is fee of a product being sold (outgoing)</inlineHelpText>
    <label>Product Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Service__c/Service__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Processing</fullName>
                <default>true</default>
                <label>Processing</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Routing</fullName>
            </value>
            <value>
                <fullName>Shopping</fullName>
            </value>
            <value>
                <fullName>Delivery</fullName>
            </value>
            <value>
                <fullName>Pick Up</fullName>
            </value>
            <value>
                <fullName>Review</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
                <isActive>false</isActive>
                <label>Active</label>
            </value>
            <value>
                <fullName>Complete</fullName>
                <isActive>false</isActive>
                <label>Complete</label>
            </value>
            <value>
                <fullName>Draft</fullName>
                <isActive>false</isActive>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Expiring</fullName>
                <isActive>false</isActive>
                <label>Expiring</label>
            </value>
            <value>
                <fullName>Items Owed</fullName>
                <isActive>false</isActive>
                <label>Items Owed</label>
            </value>
            <value>
                <fullName>No Call / No Show</fullName>
                <isActive>false</isActive>
                <label>No Call / No Show</label>
            </value>
            <value>
                <fullName>Re-Delivery</fullName>
                <isActive>false</isActive>
                <label>Re-Delivery</label>
            </value>
            <value>
                <fullName>Served</fullName>
                <isActive>false</isActive>
                <label>Served</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service__c/fields/Stop__c.field-meta.xml
<CustomField>
    <fullName>Stop__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Stop</label>
    <referenceTo>Stop__c</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Total_Estimated_Value__c.field-meta.xml
<CustomField>
    <fullName>Total_Estimated_Value__c</fullName>
    <label>Total Estimated Value</label>
    <summarizedField>ServiceItem__c.Total_Estimated_Value__c</summarizedField>
    <summaryForeignKey>ServiceItem__c.Service__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/ServiceItem__c/ServiceItem__c.object-meta.xml
<CustomObject>
    <label>Service Item</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Service Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ServiceItem__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ServiceItem__c/fields/Estimated_Value__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Value__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Estimated Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ServiceItem__c/fields/Override_Product_Fee__c.field-meta.xml
<CustomField>
    <fullName>Override_Product_Fee__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Override Product Fee</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ServiceItem__c/fields/Pickup__c.field-meta.xml
<CustomField>
    <fullName>Pickup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pickup</label>
    <referenceTo>Pickup__c</referenceTo>
    <relationshipLabel>Service Items</relationshipLabel>
    <relationshipName>ServiceItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceItem__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product__c.Archived__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Service Items</relationshipLabel>
    <relationshipName>ServiceItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceItem__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <label>Service</label>
    <referenceTo>Service__c</referenceTo>
    <relationshipLabel>Service Items</relationshipLabel>
    <relationshipName>ServiceItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ServiceItem__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
                <default>true</default>
                <label>Requested</label>
            </value>
            <value>
                <fullName>Not Available</fullName>
            </value>
            <value>
                <fullName>Staged</fullName>
            </value>
            <value>
                <fullName>Not Loaded</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Loaded</fullName>
            </value>
            <value>
                <fullName>Shopping Declined</fullName>
            </value>
            <value>
                <fullName>Not Delivered</fullName>
            </value>
            <value>
                <fullName>Item Rejected</fullName>
            </value>
            <value>
                <fullName>Backlog</fullName>
                <isActive>false</isActive>
                <label>Backlog</label>
            </value>
            <value>
                <fullName>Declined</fullName>
                <isActive>false</isActive>
                <label>Declined</label>
            </value>
            <value>
                <fullName>Delivered</fullName>
                <isActive>false</isActive>
                <label>Delivered</label>
            </value>
            <value>
                <fullName>Received</fullName>
                <isActive>false</isActive>
                <label>Received</label>
            </value>
            <value>
                <fullName>Referred</fullName>
                <isActive>false</isActive>
                <label>Referred</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServiceItem__c/fields/Stop__c.field-meta.xml
<CustomField>
    <fullName>Stop__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Stop</label>
    <referenceTo>Stop__c</referenceTo>
    <relationshipLabel>Service Items</relationshipLabel>
    <relationshipName>ServiceItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceItem__c/fields/TaxableItem__c.field-meta.xml
<CustomField>
    <fullName>TaxableItem__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Taxable Item</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ServiceItem__c/fields/Total_Estimated_Value__c.field-meta.xml
<CustomField>
    <fullName>Total_Estimated_Value__c</fullName>
    <formula>Quantity__c * Estimated_Value__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Estimated Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ServiceItem__c/fields/Total_Fee__c.field-meta.xml
<CustomField>
    <fullName>Total_Fee__c</fullName>
    <formula>TotalItemPrice__c * Quantity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ServiceItem__c/fields/TotalItemPrice__c.field-meta.xml
<CustomField>
    <fullName>TotalItemPrice__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Item Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Stop__c/Stop__c.object-meta.xml
<CustomObject>
    <label>Stop</label>
    <nameField>
        <label>Stop Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stops</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stop__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>Service__c</referenceTo>
    <relationshipLabel>Stops</relationshipLabel>
    <relationshipName>Stops</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ServiceItemSelector.cls
public without sharing class ServiceItemSelector {
//    public List<ServiceItem__c> getRequestItemByIds(Set<Id> requestItemIdSet) {
//        return [
//                SELECT
//                        Id,
//                        Name,
//                        Description__c,
//                        TotalItemPrice__c,
//                        Pickup__c,
//                        Product__c,
//                        Quantity__c,
//                        Service__c,
//                        Status__c,
//                        Stop__c,
//                        TaxableItem__c,
//                        Total_Estimated_Value__c,
//                        Total_Fee__c,
//                        Service__r.RecordTypeId,
//                        Service__r.RecordType.DeveloperName,
//                        Product__r.Pick_up_Fee__c,
//                        Product__r.Product_Fee__c,
//                        Product__r.Estimated_Value__c
//                FROM ServiceItem__c
//                WHERE Id IN :requestItemIdSet
//
//        ];
//
//    }

    public List<ServiceItem__c> getServiceItemsByServiceId(Id serviceId){
        return [
                SELECT
                        Id,
                        Name,
                        Description__c,
                        TotalItemPrice__c,
                        Pickup__c,
                        Product__r.Name,
                        Product__c,
                        Quantity__c,
                        Service__c,
                        Status__c,
                        Stop__c,
                        TaxableItem__c,
                        Total_Estimated_Value__c,
                        Override_Product_Fee__c,
                        Total_Fee__c
                FROM ServiceItem__c
                WHERE Service__c = :serviceId
        ];
    }

    public List<ServiceItem__c> getServiceItemsByServiceIds(Set<Id> serviceIds){
        return [
                SELECT
                        Id,
                        Name,
                        Description__c,
                        TotalItemPrice__c,
                        Pickup__c,
                        Product__r.Name,
                        Product__c,
                        Quantity__c,
                        Service__c,
                        Status__c,
                        Stop__c,
                        TaxableItem__c,
                        Total_Estimated_Value__c,
                        Override_Product_Fee__c,
                        Total_Fee__c
                FROM ServiceItem__c
                WHERE Service__c IN :serviceIds
        ];
    }


    public List<ServiceItem__c> getTaxableServiceItemsById(Set<Id> serviceId){
        return [
                SELECT
                        Id,
                        Name,
                        Description__c,
                        TotalItemPrice__c,
                        Pickup__c,
                        Product__c,
                        Quantity__c,
                        Service__c,
                        Status__c,
                        Stop__c,
                        TaxableItem__c,
                        Total_Estimated_Value__c,
                        Total_Fee__c
                FROM ServiceItem__c
                WHERE Service__c IN :serviceId AND TaxableItem__c = TRUE
        ];
    }
}