force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Estimated_Value__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Value__c</fullName>
    <label>Estimated Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Pick_up_Fee__c.field-meta.xml
<CustomField>
    <fullName>Pick_up_Fee__c</fullName>
    <inlineHelpText>Fee being charged to pickup an item</inlineHelpText>
    <label>Pick-up Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product_Fee__c.field-meta.xml
<CustomField>
    <fullName>Product_Fee__c</fullName>
    <inlineHelpText>This is fee of a product being sold (outgoing)</inlineHelpText>
    <label>Product Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Taxable__c.field-meta.xml
<CustomField>
    <fullName>Taxable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Taxable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Service__c/Service__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service__c/recordTypes/ClientRequest.recordType-meta.xml
<RecordType>
    <fullName>ClientRequest</fullName>
    <active>true</active>
    <label>Client Request</label>
</RecordType>

force-app/main/default/objects/Service__c/recordTypes/DonationPickup.recordType-meta.xml
<RecordType>
    <fullName>DonationPickup</fullName>
    <active>true</active>
    <label>Donation Pickup</label>
</RecordType>

force-app/main/default/objects/Service__c/recordTypes/GeneralDelivery.recordType-meta.xml
<RecordType>
    <fullName>GeneralDelivery</fullName>
    <active>true</active>
    <label>General Delivery</label>
</RecordType>

force-app/main/default/objects/Service__c/recordTypes/GeneralPickup.recordType-meta.xml
<RecordType>
    <fullName>GeneralPickup</fullName>
    <active>true</active>
    <label>General Pickup</label>
</RecordType>

force-app/main/default/objects/ServiceFeesSettings__mdt/ServiceFeesSettings__mdt.object-meta.xml
<CustomObject>
    <label>Service Fees Settings</label>
    <pluralLabel>Service Fees Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/ServiceFeesSettings__mdt/fields/FeeAmount__c.field-meta.xml
<CustomField>
    <fullName>FeeAmount__c</fullName>
    <label>Fee Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ServiceItem__c/ServiceItem__c.object-meta.xml
<CustomObject>
    <label>Service Item</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Service Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ServiceItem__c/fields/Estimated_Value__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Value__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Estimated Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ServiceItem__c/fields/ItemCost__c.field-meta.xml
<CustomField>
    <fullName>ItemCost__c</fullName>
    <label>Item Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ServiceItem__c/fields/Override_Product_Fee__c.field-meta.xml
<CustomField>
    <fullName>Override_Product_Fee__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Override Product Fee</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ServiceItem__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product__c.Archived__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Service Items</relationshipLabel>
    <relationshipName>ServiceItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceItem__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <label>Service</label>
    <referenceTo>Service__c</referenceTo>
    <relationshipLabel>Service Items</relationshipLabel>
    <relationshipName>ServiceItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ServiceItem__c/fields/TaxableItem__c.field-meta.xml
<CustomField>
    <fullName>TaxableItem__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Taxable Item</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ServiceItem__c/fields/TotalItemPrice__c.field-meta.xml
<CustomField>
    <fullName>TotalItemPrice__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Item Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/ServiceItemDao.cls
public without sharing class ServiceItemDao extends GenericDao {

    @TestVisible
    private static ServiceItemDao mock;

    public ServiceItemDao() {
    }

    private ServiceItemDao(List<SObject> requests, Map<Id, SObject> oldRequestsById) {
        super(requests, oldRequestsById);
    }
    private ServiceItemDao(List<SObject> requests) {
        super(requests);
    }

    public static ServiceItemDao getInstance() {
        if (Test.isRunningTest() && mock != null) {
            return mock;
        } else {
            return new ServiceItemDao(new List<ServiceItem__c>());
        }
    }

    public override void beforeInsert() {
        setFees();
        //setItemCost();
    }

    public override void beforeUpdate() {
        //setItemCost();
    }

    public override void afterInsert() {
        rollup();
    }

    public override void afterUpdate() {
        rollup();
    }

    private void rollup() {
        if (this.records != null && !this.records.isEmpty()) {
            Database.update(dlrs.RollupService.rollup(this.records));
        }
    }
    @TestVisible
    private void setFees() {
        Set<Id> serviceItemIds = new Set<Id>();
        Set<Id> servicesIds = new Set<Id>();

        for (ServiceItem__c serviceItem : (List<ServiceItem__c>) this.records) {
            serviceItemIds.add(serviceItem.Product__c);
            servicesIds.add(serviceItem.Service__c);
        }

        Map<Id, Product__c> productMap = ProductSelector.getInstance().getMapProductById(serviceItemIds);
        Map<Id, Service__c> servicesMap = ServiceSelector.getInstance().getServicesRecordTypesById(servicesIds);

        if (productMap.isEmpty()) return;

        for (ServiceItem__c serviceItem : (List<ServiceItem__c>) this.records) {
            Product__c productServiceItem = productMap.get(serviceItem.Product__c);
            Service__c service = servicesMap.get(serviceItem.Service__c);
            System.debug('service.RecordType.DeveloperName => ' + service.RecordType.DeveloperName);
            System.debug('serviceItem.TotalItemPrice__c => ' + serviceItem.TotalItemPrice__c);
            serviceItem.Estimated_Value__c = productServiceItem.Estimated_Value__c;

            if(!serviceItem.Override_Product_Fee__c){
                if ((service.RecordType.DeveloperName == 'ClientRequest' || service.RecordType.DeveloperName == 'GeneralDelivery')
                        && serviceItem.TotalItemPrice__c == 0.00) {
                    serviceItem.TotalItemPrice__c = productServiceItem.Product_Fee__c;
                } else if ((service.RecordType.DeveloperName == 'DonationPickup' || service.RecordType.DeveloperName == 'GeneralPickup')
                        &&  serviceItem.TotalItemPrice__c == 0.00) {
                    serviceItem.TotalItemPrice__c = productServiceItem.Pick_up_Fee__c;
                }
            }

            serviceItem.TaxableItem__c = productServiceItem.Taxable__c;
        }
    }

//    private void setItemCost() {
//        Set<Id> serviceItemIds = new Set<Id>();
//        for (ServiceItem__c serviceItem : (List<ServiceItem__c>) this.records) {
//            serviceItemIds.add(serviceItem.Id);
//        }
//
//        Map<String, ServiceFeesSettings__mdt> serviceFeesSettingsByDevName = new Map<String, ServiceFeesSettings__mdt>();
//        List<ServiceFeesSettings__mdt> serviceFeesSettings = CustomMetadataSelector.getInstance().getMdtByStatus();
//        for (ServiceFeesSettings__mdt serviceFeeSetting : serviceFeesSettings) {
//            serviceFeesSettingsByDevName.put(serviceFeeSetting.DeveloperName, serviceFeeSetting);
//        }
//
//        List<ServiceItem__c> servicesItems = ServiceItemSelector.getInstance().getRequestItemByIds(serviceItemIds);
//
//        for (ServiceItem__c serviceItem : servicesItems) {
//            if (serviceItem.Service__c == null ) continue;
//            if (serviceItem.Service__r.RecordType.DeveloperName != 'GeneralDelivery') continue;
//            //serviceItem.ItemCost__c = serviceFeesSettingsByDevName.get('GeneralDeliveryServiceItemFee').FeeAmount__c;
//        }
//    }

    public class Factory implements TriggerHandlerFactory {
        public TriggerHandler create(List<SObject> objects, Map<Id, SObject> oldObjectsById) {
            return new ServiceItemDao(objects, oldObjectsById);
        }
    }
}