force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Estimated_Value__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Value__c</fullName>
    <label>Estimated Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Limit__c.field-meta.xml
<CustomField>
    <fullName>Limit__c</fullName>
    <label>Limit</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Single</fullName>
            </value>
            <value>
                <fullName>Household Size</fullName>
            </value>
            <value>
                <fullName>Adult</fullName>
            </value>
            <value>
                <fullName>Children</fullName>
            </value>
            <value>
                <fullName>No Limit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Pick_up_Fee__c.field-meta.xml
<CustomField>
    <fullName>Pick_up_Fee__c</fullName>
    <inlineHelpText>Fee being charged to pickup an item</inlineHelpText>
    <label>Pick-up Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product_Code__c.field-meta.xml
<CustomField>
    <fullName>Product_Code__c</fullName>
    <description>Used to map standard Products to Service Products</description>
    <externalId>true</externalId>
    <label>Product Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product_Fee__c.field-meta.xml
<CustomField>
    <fullName>Product_Fee__c</fullName>
    <inlineHelpText>This is fee of a product being sold (outgoing)</inlineHelpText>
    <label>Product Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Taxable__c.field-meta.xml
<CustomField>
    <fullName>Taxable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Taxable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Service__c/Service__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Client contact record attached to this request</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Services (Contact)</relationshipLabel>
    <relationshipName>Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/SubType__c.field-meta.xml
<CustomField>
    <fullName>SubType__c</fullName>
    <label>Sub Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Will Call</fullName>
            </value>
            <value>
                <fullName>Delivery</fullName>
            </value>
            <value>
                <fullName>Hope Run</fullName>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>Hope Del.</fullName>
            </value>
            <value>
                <fullName>Donation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServiceItem__c/ServiceItem__c.object-meta.xml
<CustomObject>
    <label>Service Item</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Service Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ServiceItem__c/fields/Estimated_Value__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Value__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Estimated Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ServiceItem__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product__c.Archived__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Service Items</relationshipLabel>
    <relationshipName>ServiceItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceItem__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <label>Service</label>
    <referenceTo>Service__c</referenceTo>
    <relationshipLabel>Service Items</relationshipLabel>
    <relationshipName>ServiceItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ServiceItem__c/fields/TaxableItem__c.field-meta.xml
<CustomField>
    <fullName>TaxableItem__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Taxable Item</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ServiceItem__c/fields/TotalItemPrice__c.field-meta.xml
<CustomField>
    <fullName>TotalItemPrice__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Item Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/ServiceItemDaoTest.cls
/**
 * Created by Gustavo on 05/01/24.
 */

@IsTest
private class ServiceItemDaoTest {
    @TestSetup
    private static void setup() {
        Contact contact = new Contact(
                FirstName = 'Test',
                LastName = 'Test'
        );
        insert contact;

        Product__c product = new Product__c(
            Name = 'Test',
            Product_Code__c = 'Test1',
            Estimated_Value__c = 10,
            Taxable__c = true,
            Limit__c = 'Single',
            Product_Fee__c = 10,
            Pick_up_Fee__c = 10
        );
        insert product;

        Service__c service = new Service__c(
                Contact__c = contact.Id
        );
        insert service;


    }

    @IsTest
    private static void setFees() {
        TriggerManagement.disableTrigger('ServiceTrigger');

        Product__c product = [SELECT Id FROM Product__c LIMIT 1];
        Service__c service = [SELECT Id FROM Service__c LIMIT 1];

        service.RecordTypeId = Utils.getRecordTypeId(Service__c.SObjectType, 'Client Request');
        service.SubType__c = 'Delivery';
        update service;

        ServiceItem__c serviceItem = new ServiceItem__c(
                Product__c = product.Id,
                Service__c = service.Id,
                TotalItemPrice__c = 0
        );
        insert serviceItem;
        ServiceItemDao.getInstance().setFees();

        ServiceItem__c updatedServiceItem = [SELECT Id, TaxableItem__c, TotalItemPrice__c FROM ServiceItem__c LIMIT 1];

        System.assert(updatedServiceItem.TotalItemPrice__c > 0);
        System.assert(updatedServiceItem.TaxableItem__c == true);

        TriggerManagement.enableTrigger('ServiceTrigger');
    }
}