force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Estimated_Value__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Value__c</fullName>
    <label>Estimated Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Pick_up_Fee__c.field-meta.xml
<CustomField>
    <fullName>Pick_up_Fee__c</fullName>
    <inlineHelpText>Fee being charged to pickup an item</inlineHelpText>
    <label>Pick-up Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product_Fee__c.field-meta.xml
<CustomField>
    <fullName>Product_Fee__c</fullName>
    <inlineHelpText>This is fee of a product being sold (outgoing)</inlineHelpText>
    <label>Product Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Taxable__c.field-meta.xml
<CustomField>
    <fullName>Taxable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Taxable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ProductSelector.cls
/**
 * Created by Eric Solari on 05/04/2023.
 */

public with sharing class ProductSelector {
    private static ProductSelector instance = null;

    public static ProductSelector getInstance() {
        if (instance == null) {
            instance = new ProductSelector();
        }
        return instance;
    }

    public Map<Id, Product__c> getMapProductById(Set<Id> productsIds){
        return new Map<Id, Product__c>([SELECT Id, Pick_up_Fee__c, Estimated_Value__c, Product_Fee__c, Taxable__c FROM Product__c WHERE id IN: productsIds]);
    }
}