force-app/main/default/objects/Appointment__c/Appointment__c.object-meta.xml
<CustomObject>
    <label>Appointment</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Appointment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Appointment__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>Service__c</referenceTo>
    <relationshipLabel>Appointments</relationshipLabel>
    <relationshipName>Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
                <default>true</default>
                <label>Scheduled</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>No Show</fullName>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Time__c.field-meta.xml
<CustomField>
    <fullName>Time__c</fullName>
    <label>Time</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>AvailableTimeSlot</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service__c/Service__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Client contact record attached to this request</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Services (Contact)</relationshipLabel>
    <relationshipName>Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Pickup_type__c.field-meta.xml
<CustomField>
    <fullName>Pickup_type__c</fullName>
    <label>Pickup type (Delete)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Delivery</fullName>
            </value>
            <value>
                <fullName>Will Call</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Processing</fullName>
                <default>true</default>
                <label>Processing</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Routing</fullName>
            </value>
            <value>
                <fullName>Shopping</fullName>
            </value>
            <value>
                <fullName>Delivery</fullName>
            </value>
            <value>
                <fullName>Pick Up</fullName>
            </value>
            <value>
                <fullName>Review</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
                <isActive>false</isActive>
                <label>Active</label>
            </value>
            <value>
                <fullName>Complete</fullName>
                <isActive>false</isActive>
                <label>Complete</label>
            </value>
            <value>
                <fullName>Draft</fullName>
                <isActive>false</isActive>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Expiring</fullName>
                <isActive>false</isActive>
                <label>Expiring</label>
            </value>
            <value>
                <fullName>Items Owed</fullName>
                <isActive>false</isActive>
                <label>Items Owed</label>
            </value>
            <value>
                <fullName>No Call / No Show</fullName>
                <isActive>false</isActive>
                <label>No Call / No Show</label>
            </value>
            <value>
                <fullName>Re-Delivery</fullName>
                <isActive>false</isActive>
                <label>Re-Delivery</label>
            </value>
            <value>
                <fullName>Served</fullName>
                <isActive>false</isActive>
                <label>Served</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service__c/fields/SubType__c.field-meta.xml
<CustomField>
    <fullName>SubType__c</fullName>
    <label>Sub Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Will Call</fullName>
            </value>
            <value>
                <fullName>Delivery</fullName>
            </value>
            <value>
                <fullName>Hope Run</fullName>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>Hope Del.</fullName>
            </value>
            <value>
                <fullName>Donation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AppointmentTest.cls
@IsTest
public with sharing class AppointmentTest {

    @IsTest
    public static void sendEmailConfirmationBasedOnStatusTest() {

        Account account = createAccount();
        insert account;

        Contact contact = createContact(account);
        insert contact;

        Service__c service = createService(contact);
        insert service;

        Appointment__c appointment = createScheduledAppointment(service);

        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new AppointmentMock());
        insert appointment;
        Test.stopTest();

        Task task = [SELECT Id FROM Task LIMIT 1];

        System.assertEquals(true, task != null);
    }

    @IsTest
    public static void serviceStatusChangeTest() {

        Account account = createAccount();
        insert account;

        Contact contact = createContact(account);
        insert contact;

        Service__c service = createService(contact);
        service.RecordTypeId = Utils.getRecordTypeId(Service__c.SObjectType, 'General Delivery');
        service.SubType__c = 'Event';
        insert service;

        Appointment__c appointment = createScheduledAppointment(service);


        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new AppointmentMock());
        insert appointment;
        Test.stopTest();

        Service__c updatedService = [SELECT Id, Status__c FROM Service__c LIMIT 1];

        System.assertEquals('Processing', updatedService.Status__c);
    }

    private static Account createAccount() {
        return new Account(
                Name = 'Test Account',
                Type = 'Agency',
                Active__c = true
        );
    }

    private static Contact createContact(Account account) {
        return new Contact(
                AccountId = account.Id,
                FirstName = 'Test Contact',
                LastName = 'Last name test contact',
                Email = 'testEmail@exemple.com',
                MobilePhone = '9999999999'
        );
    }

    private static Service__c createService(Contact contact) {
        return new Service__c(
                Contact__c = contact.Id,
                Status__c = 'Processing',
                Pickup_type__c = 'Delivery',
                RecordTypeId = Utils.getRecordTypeId(Service__c.SObjectType, 'Client Request'),
                SubType__c = 'Delivery'
        );
    }

    private static Appointment__c createScheduledAppointment(Service__c service) {
        return new Appointment__c(
                Service__c = service.Id,
                Status__c = 'Scheduled',
                Time__c = '9:15am',
                Date__c = System.today()
        );
    }

    @IsTest
    public static void updateServiceStatusAndAppointment() {
        Account account = createAccount();
        insert account;

        Contact contact = createContact(account);
        insert contact;

        Service__c service = createService(contact);
//
//        service.RecordTypeId = Utils.getRecordTypeId(Service__c.SObjectType, 'Client Request');
//        service.SubType__c = 'Delivery';

        insert service;

        Appointment__c appointment = createScheduledAppointment(service);
        Appointment__c noShowAppointment = createScheduledAppointment(service);
        noShowAppointment.Status__c = 'No Show';
        
        TriggerManagement.disableTrigger('ServiceTrigger');
        Test.setMock(HttpCalloutMock.class, new AppointmentMock());
        
        Test.startTest();
        insert appointment;
        insert noShowAppointment;
        Test.stopTest();
        
        TriggerManagement.disableTrigger('TaskTrigger');

        Service__c updatedService = [SELECT Id, Status__c FROM Service__c WHERE Id = :service.Id];
        System.assertEquals('Scheduled', updatedService.Status__c);
    }

    @IsTest
    public static void testCreateEmailTask() {
        TriggerManagement.disableTrigger('ServiceTrigger');
        TriggerManagement.disableTrigger('AppointmentTrigger');

        Account account = createAccount();
        insert account;

        Contact contact = createContact(account);
        insert contact;

        Service__c service = createService(contact);
        insert service;

        Appointment__c scheduledAppointment = createScheduledAppointment(service);
        insert scheduledAppointment;

        Task createdTask = Appointment.createEmailTask(
                scheduledAppointment,
                service,
               null
        );

        System.assert(createdTask != null);
    }
}