force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/CardLast4Digits__c.field-meta.xml
<CustomField>
    <fullName>CardLast4Digits__c</fullName>
    <label>Card Last 4 Digits</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/ParentPayment__c.field-meta.xml
<CustomField>
    <fullName>ParentPayment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Payment</label>
    <referenceTo>Payment__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Payee_Type__c.field-meta.xml
<CustomField>
    <fullName>Payee_Type__c</fullName>
    <label>Payee Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Agency</fullName>
            </value>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment__c/fields/PaymentAmount__c.field-meta.xml
<CustomField>
    <fullName>PaymentAmount__c</fullName>
    <label>Payment Amount</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/PaymentMethod__c.field-meta.xml
<CustomField>
    <fullName>PaymentMethod__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cash</fullName>
                <color>#006600</color>
                <label>Cash</label>
            </value>
            <value>
                <fullName>CreditCard</fullName>
                <color>#996633</color>
                <label>Credit Card</label>
            </value>
            <value>
                <fullName>DebitCard</fullName>
                <color>#EFAE73</color>
                <label>Debit Card</label>
            </value>
            <value>
                <fullName>Wire</fullName>
                <color>#663366</color>
                <label>Wire</label>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
            <value>
                <fullName>Card</fullName>
            </value>
            <value>
                <fullName>Check</fullName>
                <color>#AFCADF</color>
                <label>Check</label>
            </value>
            <value>
                <fullName>Bulletin de Versement</fullName>
                <isActive>false</isActive>
                <label>Bulletin de Versement</label>
            </value>
            <value>
                <fullName>Credit Card Old</fullName>
                <isActive>false</isActive>
                <label>Credit Card Old</label>
            </value>
            <value>
                <fullName>ECheck</fullName>
                <isActive>false</isActive>
                <label>E-Check</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment__c/fields/PaymentType__c.field-meta.xml
<CustomField>
    <fullName>PaymentType__c</fullName>
    <label>Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Payment</fullName>
                <default>true</default>
                <label>Payment</label>
            </value>
            <value>
                <fullName>Refund</fullName>
            </value>
            <value>
                <fullName>ActivationFee</fullName>
                <isActive>false</isActive>
                <label>Activation Fee</label>
            </value>
            <value>
                <fullName>Application Fee</fullName>
                <isActive>false</isActive>
                <label>Application Fee</label>
            </value>
            <value>
                <fullName>Application Fee Refund</fullName>
                <isActive>false</isActive>
                <label>Application Fee Refund</label>
            </value>
            <value>
                <fullName>EventFees</fullName>
                <isActive>false</isActive>
                <label>Event Fees</label>
            </value>
            <value>
                <fullName>KokuaCrewAppFee</fullName>
                <isActive>false</isActive>
                <label>Kokua Crew App Fee</label>
            </value>
            <value>
                <fullName>Kokua Crew Fees</fullName>
                <isActive>false</isActive>
                <label>Kokua Crew Fees</label>
            </value>
            <value>
                <fullName>MealCredit</fullName>
                <isActive>false</isActive>
                <label>Meal Credit</label>
            </value>
            <value>
                <fullName>Overpayment</fullName>
                <isActive>false</isActive>
                <label>Overpayment</label>
            </value>
            <value>
                <fullName>School Fees</fullName>
                <isActive>false</isActive>
                <label>School Fees</label>
            </value>
            <value>
                <fullName>StaffAppFee</fullName>
                <isActive>false</isActive>
                <label>Staff App Fee</label>
            </value>
            <value>
                <fullName>StaffFees</fullName>
                <isActive>false</isActive>
                <label>Staff Fees</label>
            </value>
            <value>
                <fullName>StaffPayment</fullName>
                <isActive>false</isActive>
                <label>Staff Payment</label>
            </value>
            <value>
                <fullName>StudentAppFee</fullName>
                <isActive>false</isActive>
                <label>Student App Fee</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>Service__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>(&quot;Processing&quot;)</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Voided</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment__c/fields/TransactionId__c.field-meta.xml
<CustomField>
    <fullName>TransactionId__c</fullName>
    <label>Transaction ID</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service__c/Service__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Processing</fullName>
                <default>true</default>
                <label>Processing</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Routing</fullName>
            </value>
            <value>
                <fullName>Shopping</fullName>
            </value>
            <value>
                <fullName>Delivery</fullName>
            </value>
            <value>
                <fullName>Pick Up</fullName>
            </value>
            <value>
                <fullName>Review</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
                <isActive>false</isActive>
                <label>Active</label>
            </value>
            <value>
                <fullName>Complete</fullName>
                <isActive>false</isActive>
                <label>Complete</label>
            </value>
            <value>
                <fullName>Draft</fullName>
                <isActive>false</isActive>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Expiring</fullName>
                <isActive>false</isActive>
                <label>Expiring</label>
            </value>
            <value>
                <fullName>Items Owed</fullName>
                <isActive>false</isActive>
                <label>Items Owed</label>
            </value>
            <value>
                <fullName>No Call / No Show</fullName>
                <isActive>false</isActive>
                <label>No Call / No Show</label>
            </value>
            <value>
                <fullName>Re-Delivery</fullName>
                <isActive>false</isActive>
                <label>Re-Delivery</label>
            </value>
            <value>
                <fullName>Served</fullName>
                <isActive>false</isActive>
                <label>Served</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServicePayment__c/ServicePayment__c.object-meta.xml
<CustomObject>
    <description>OLD PAYMENT OBJECT, NOT USED</description>
    <label>Service Payment</label>
    <nameField>
        <displayFormat>SP-{000000}</displayFormat>
        <label>Service Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ServicePayment__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <label>Payment</label>
    <referenceTo>Payment__c</referenceTo>
    <relationshipLabel>Service Payments</relationshipLabel>
    <relationshipName>Service_Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ServicePayment__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <label>Service</label>
    <referenceTo>Service__c</referenceTo>
    <relationshipLabel>Service Payments</relationshipLabel>
    <relationshipName>Service_Payments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/InvoicePaymentProcess.cls
public with sharing class InvoicePaymentProcess implements CloverConnectPaymentHandler {


    public void process(Map<String, Object> requestParams, Map<String, Object> authorizeResponse) {
        if (!new CloverConnectClient.TransactionStatus(authorizeResponse).approved()) {
            createRejectedPayment(requestParams, authorizeResponse);
            return;
        }

        Map<String, Object> userFields = (Map<String, Object>) requestParams.get('userFields');
        String token = (String) authorizeResponse.get('account');

        Payment__c newPayment = new Payment__c(
                PaymentDate__c = Date.today(),
                PaymentAmount__c = Double.valueOf(authorizeResponse.get('amount')),
                PaymentMethod__c = 'CreditCard',
                TransactionId__c = (String) authorizeResponse.get('retref'),
                PaymentType__c = 'Payment',
                Status__c = 'Approved',
                CardLast4Digits__c = token.substring(token.length() - 4) 
        );

        if (userFields.get('serviceId') != null) {
            newPayment.Service__c = (Id) userFields.get('serviceId');
        }

        if (userFields.get('opportunityId') != null) {
            System.debug('created payment here');
            newPayment.Opportunity__c = (Id) userFields.get('opportunityId');
        }

        /*here I validate the past payer data*/
        if (userFields.get('payee') != null) {
            newPayment.Payee_Type__c = (String) userFields.get('payee');
        }

        insert newPayment;

        List<Object> invoicePayments = (List<Object>) userFields.get('invoicePayments');
        if (invoicePayments != null && !invoicePayments.isEmpty()) {
            List<ServicePayment__c> newInvoicePayments = new List<ServicePayment__c>();
            List<Payment__c> childPayments = new List<Payment__c>();

            for (Object invoicePaymentObj : invoicePayments) {
                Map<String, Object> invoicePaymentMap = (Map<String, Object>) invoicePaymentObj;

                newInvoicePayments.add(
                        new ServicePayment__c(
                                Service__c = String.valueOf(invoicePaymentMap.get('Service__c')),
                                Payment__c = newPayment.Id,
                                Amount__c = Double.valueOf(invoicePaymentMap.get('Amount__c'))
                        )
                );

                childPayments.add(new Payment__c(
                        Service__c = (Id) String.valueOf(invoicePaymentMap.get('Service__c')),
                        ParentPayment__c = newPayment.Id,
                        PaymentAmount__c = Double.valueOf(invoicePaymentMap.get('Amount__c')),
                        PaymentDate__c = newPayment.PaymentDate__c,
                        PaymentMethod__c = newPayment.PaymentMethod__c,
                        TransactionId__c = newPayment.TransactionId__c,
                        PaymentType__c = 'Payment',
                        Status__c = 'Approved',
                        CardLast4Digits__c = newPayment.CardLast4Digits__c
                ));
            }

            insert newInvoicePayments;
            insert childPayments;
        }
    }

    public void createRejectedPayment(Map<String, Object> requestParams, Map<String, Object> authorizeResponse) {
        Map<String, Object> userFields = (Map<String, Object>) requestParams.get('userFields');
        String token = (String) authorizeResponse.get('account');

        Id opportunityId = (Id) userFields.get('opportunityId');
        if (opportunityId == null) return;

        Payment__c rejectedPayment = new Payment__c(
                Opportunity__c = opportunityId,
                PaymentDate__c = Date.today(),
                PaymentAmount__c = Double.valueOf(authorizeResponse.get('amount')),
                PaymentMethod__c = 'CreditCard',
                TransactionId__c = (String) authorizeResponse.get('retref'),
                PaymentType__c = 'Payment',
                Status__c = 'Rejected',
                CardLast4Digits__c = token.substring(token.length() - 4)
        );

        insert rejectedPayment;
    }
}