force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/Payee_Type__c.field-meta.xml
<CustomField>
    <fullName>Payee_Type__c</fullName>
    <label>Payee Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Agency</fullName>
            </value>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment__c/fields/PaymentMethod__c.field-meta.xml
<CustomField>
    <fullName>PaymentMethod__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cash</fullName>
                <color>#006600</color>
                <label>Cash</label>
            </value>
            <value>
                <fullName>CreditCard</fullName>
                <color>#996633</color>
                <label>Credit Card</label>
            </value>
            <value>
                <fullName>DebitCard</fullName>
                <color>#EFAE73</color>
                <label>Debit Card</label>
            </value>
            <value>
                <fullName>Wire</fullName>
                <color>#663366</color>
                <label>Wire</label>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
            <value>
                <fullName>Card</fullName>
            </value>
            <value>
                <fullName>Check</fullName>
                <color>#AFCADF</color>
                <label>Check</label>
            </value>
            <value>
                <fullName>Bulletin de Versement</fullName>
                <isActive>false</isActive>
                <label>Bulletin de Versement</label>
            </value>
            <value>
                <fullName>Credit Card Old</fullName>
                <isActive>false</isActive>
                <label>Credit Card Old</label>
            </value>
            <value>
                <fullName>ECheck</fullName>
                <isActive>false</isActive>
                <label>E-Check</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment__c/fields/PaymentType__c.field-meta.xml
<CustomField>
    <fullName>PaymentType__c</fullName>
    <label>Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Payment</fullName>
                <default>true</default>
                <label>Payment</label>
            </value>
            <value>
                <fullName>Refund</fullName>
            </value>
            <value>
                <fullName>ActivationFee</fullName>
                <isActive>false</isActive>
                <label>Activation Fee</label>
            </value>
            <value>
                <fullName>Application Fee</fullName>
                <isActive>false</isActive>
                <label>Application Fee</label>
            </value>
            <value>
                <fullName>Application Fee Refund</fullName>
                <isActive>false</isActive>
                <label>Application Fee Refund</label>
            </value>
            <value>
                <fullName>EventFees</fullName>
                <isActive>false</isActive>
                <label>Event Fees</label>
            </value>
            <value>
                <fullName>KokuaCrewAppFee</fullName>
                <isActive>false</isActive>
                <label>Kokua Crew App Fee</label>
            </value>
            <value>
                <fullName>Kokua Crew Fees</fullName>
                <isActive>false</isActive>
                <label>Kokua Crew Fees</label>
            </value>
            <value>
                <fullName>MealCredit</fullName>
                <isActive>false</isActive>
                <label>Meal Credit</label>
            </value>
            <value>
                <fullName>Overpayment</fullName>
                <isActive>false</isActive>
                <label>Overpayment</label>
            </value>
            <value>
                <fullName>School Fees</fullName>
                <isActive>false</isActive>
                <label>School Fees</label>
            </value>
            <value>
                <fullName>StaffAppFee</fullName>
                <isActive>false</isActive>
                <label>Staff App Fee</label>
            </value>
            <value>
                <fullName>StaffFees</fullName>
                <isActive>false</isActive>
                <label>Staff Fees</label>
            </value>
            <value>
                <fullName>StaffPayment</fullName>
                <isActive>false</isActive>
                <label>Staff Payment</label>
            </value>
            <value>
                <fullName>StudentAppFee</fullName>
                <isActive>false</isActive>
                <label>Student App Fee</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>Service__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service__c/Service__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Client contact record attached to this request</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Services (Contact)</relationshipLabel>
    <relationshipName>Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PaymentSelector.cls
/**
 * Created by Gustavo on 29/06/23.
 */

public without sharing class PaymentSelector {

    private static PaymentSelector instance = null;

    public static PaymentSelector getInstance() {
        if (instance == null) {
            instance = new PaymentSelector();
        }
        return instance;
    }

    public List<Payment__c> byIds(Set<Id> ids){
        return [
            SELECT
                Id,
                Name,
                Service__c,
                PaymentMethod__c,
                Payee_Type__c,
                PaymentType__c,
                Service__r.Contact__c,
                Service__r.Name
            FROM Payment__c
            WHERE Id IN :ids
        ];
    }
}