force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/Payee_Type__c.field-meta.xml
<CustomField>
    <fullName>Payee_Type__c</fullName>
    <label>Payee Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Agency</fullName>
            </value>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment__c/fields/PaymentAmount__c.field-meta.xml
<CustomField>
    <fullName>PaymentAmount__c</fullName>
    <label>Payment Amount</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/PaymentMethod__c.field-meta.xml
<CustomField>
    <fullName>PaymentMethod__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cash</fullName>
                <color>#006600</color>
                <label>Cash</label>
            </value>
            <value>
                <fullName>CreditCard</fullName>
                <color>#996633</color>
                <label>Credit Card</label>
            </value>
            <value>
                <fullName>DebitCard</fullName>
                <color>#EFAE73</color>
                <label>Debit Card</label>
            </value>
            <value>
                <fullName>Wire</fullName>
                <color>#663366</color>
                <label>Wire</label>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
            <value>
                <fullName>Card</fullName>
            </value>
            <value>
                <fullName>Check</fullName>
                <color>#AFCADF</color>
                <label>Check</label>
            </value>
            <value>
                <fullName>Bulletin de Versement</fullName>
                <isActive>false</isActive>
                <label>Bulletin de Versement</label>
            </value>
            <value>
                <fullName>Credit Card Old</fullName>
                <isActive>false</isActive>
                <label>Credit Card Old</label>
            </value>
            <value>
                <fullName>ECheck</fullName>
                <isActive>false</isActive>
                <label>E-Check</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>Service__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>(&quot;Processing&quot;)</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Voided</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service__c/Service__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Client contact record attached to this request</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Services (Contact)</relationshipLabel>
    <relationshipName>Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Processing</fullName>
                <default>true</default>
                <label>Processing</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Routing</fullName>
            </value>
            <value>
                <fullName>Shopping</fullName>
            </value>
            <value>
                <fullName>Delivery</fullName>
            </value>
            <value>
                <fullName>Pick Up</fullName>
            </value>
            <value>
                <fullName>Review</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
                <isActive>false</isActive>
                <label>Active</label>
            </value>
            <value>
                <fullName>Complete</fullName>
                <isActive>false</isActive>
                <label>Complete</label>
            </value>
            <value>
                <fullName>Draft</fullName>
                <isActive>false</isActive>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Expiring</fullName>
                <isActive>false</isActive>
                <label>Expiring</label>
            </value>
            <value>
                <fullName>Items Owed</fullName>
                <isActive>false</isActive>
                <label>Items Owed</label>
            </value>
            <value>
                <fullName>No Call / No Show</fullName>
                <isActive>false</isActive>
                <label>No Call / No Show</label>
            </value>
            <value>
                <fullName>Re-Delivery</fullName>
                <isActive>false</isActive>
                <label>Re-Delivery</label>
            </value>
            <value>
                <fullName>Served</fullName>
                <isActive>false</isActive>
                <label>Served</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PaymentReceiptEmailSenderTest.cls
/**
 * Created by Gustavo on 12/06/24.
 */

@IsTest
private class PaymentReceiptEmailSenderTest {
    @IsTest
    static void testBehavior() {
        Contact contact = new Contact(
                FirstName = 'Test',
                LastName = 'Test',
                Email = 'test+test@gmail.com'
        );
        insert contact;

        Service__c service = new Service__c(
                Contact__c = contact.Id,
                Status__c = 'Processing'
        );
        TriggerManagement.disableTrigger('ServiceTrigger');
        insert service;

        Payment__c payment = new Payment__c(
                PaymentAmount__c = 10,
                PaymentMethod__c = 'DebitCard',
                Payee_Type__c = 'Client',
                Service__c = service.Id
        );

        insert payment;
        PaymentReceiptEmailSender.send(new Set<Id>{payment.Id});
        System.assert(Limits.getEmailInvocations() == 1);
    }
}